### ISSUE TITLE
Upgrade from 2.2.3 to 2.9p5

### ISSUE THREAD

**Issue by kpy3** [basho/riak#1001]
Hi,
we are going to upgrade our riak cluster from 2.2.3 to 2.9p5, can we do it directly or some  intermediate steps required?

Can we upgrade our cluster via adding additional nodes with 2.9p5 version (may be some configuration changes required?) or rolling upgrade is preferred way?

UPDATE: Is there a plan to upgrade basho's docker images (https://hub.docker.com/r/basho/riak-kv) for riak?

**Comment by martinsumner** [comment]
It depends if you want to change backends as part of the upgrade.  If no, then a rolling upgrade is preferred - the upgrade will be quicker, with less time in a mixed state.  There is nothing wrong with a mixed version state, but it is just a less well-known state.

If you intend to change to a leveled backend you should do that by adding additional nodes and doing a series of `replace` operations.  If you have a very large data set, this may take some time - so it may be preferable to do a rolling upgrade first.  This is the plan being followed by a large customer making that switch.

There should be no intermediate steps required.  We've done lots of testing from 2.0.x to 2.9p5 - so 2.2.3 will be fine.  

New configured features will be off by default, so if you leave your configuration as-is it should run with the old feature set.  Some new features (e.g. Tictac AAE, coverage participation) will therefore require new configuration, others (e.g. node confirms) will require extra bucket properties.

If you were not an enterprise customer on 2.2.3 - you will now end up with the enterprise features by default as part of the upgrade.  So the riak_repl module will be installed - but it should be inactive (although it can still generate some logs on startup/shutdown).

**Comment by martinsumner** [comment]
There are no plans on upgrading docker images that I'm aware of, but any contributions to move this forward would be welcome.

**Comment by kpy3** [comment]
So, I guess [this plan](https://github.com/basho/riak/issues/985#issuecomment-521257064) also suitable for upgrade riak to 2.9 (if we decide to change backed later)?

**Comment by martinsumner** [comment]
Yes

**Comment by kpy3** [comment]
Thanks! :)

**Comment by martinsumner** [comment]
@kpy3 is it OK to close the issue now?

**Comment by kpy3** [comment]
Yes.
