### ISSUE TITLE
Riak 3.0 @ Erlang 22

### ISSUE THREAD

**Issue by kpy3** [basho/riak#1003]
It seems riak 3.0 limited with erlang 20, how can I use latest erlang with develop-3.0 branch? Is there a plan to support latest erlang versions?

**Comment by martincox** [comment]
Some work has been completed on 21/22 compatibility by @ThomasArts. I don't think that it is finished yet, but it should not be too far away. It might just be a case of tweaking the otp_release_vsn in some rebar configs.
