### ISSUE TITLE
RPM 2.9.1-1 obsoleted by 2.9.0p4

### ISSUE THREAD

**Issue by kks69** [basho/riak#1007]
Hello,

and first, thank you for everyone involved in still developing RIAK.

I came across a small hick-up as I wanted to upgrade our development and testing environment to the latest RIAK with rpm from tiot.jp. My system complains as:

```
$ sudo yum install ./riak-2.9.1-1.el7.x86_64.rpm
"Cannot install package riak-2.9.1-1.el7.x86_64. It is obsoleted by installed package riak-2.9.0p4-1.el7.x86_64"

```
I did not yet try any magic yum spells to force the install, but just wanted to let you know about this.

Best Regards,

kks

**Comment by martinsumner** [comment]
I don't know what is happening with this.  I did notice that I forgot to update the riak release version with the last release (in reltool.config), but I'm not sure why this would cause this error.

**Comment by martinsumner** [comment]
This may be more relevant - https://github.com/basho/node_package/issues/152
