### ISSUE TITLE
Riak 3.0 state

### ISSUE THREAD

**Issue by kpy3** [basho/riak#1015]
Hello,

As far as I can see there is a release tagged as 3.0 exists on release page, but there is no additional info about it. Could you share the state of riak 3.0 development and release info? Is riak 3.0 is production ready or what are the stoppers for it?

**Comment by martinsumner** [comment]
3.0 is for non-production testing only at the moment.  Apologies, progress has slowed recently, and communication about this hasn't been good.

The intention had been to focus on 3.0 from the start of this year, but there has been a pressing need for further work on 2.9 which has taken attention away from 3.0.  Outstanding work for 3.0 includes:

- There is some work on packaging that is nearly complete I think (@martincox).

- The updates from 2.9 need to be merged in.

- There may a couple of issues to resolve with future compatibility (e.g. dialyzer fixes for OTP 22)

- There is some parallel work on forks of Riak 2 to merge in, especially work on replication improvements by bet365.

- There is work to enable Riak to be built with TLS-based inter-node encryption.

- There is work from bet365 to overhaul and improve the granularity of the stats framework.

Some of this work may be deferred to a 3.1 release.

I'm hoping to get 2.9.2 finished off next week, and then I can spend some time on 3.0 again.  I know @martincox is busy on 3.0 at the moment.  Hopefully in early April we can offer a more definitive timetable around the completion of 3.0 and 3.1.  However the priorities of some of the organisations funding Riak development are quite volatile at the moment.

**Comment by kpy3** [comment]
Thanks for sharing the information, looking forward to see 3.0 release!
