### ISSUE TITLE
Support for Yokozuna in 3.0

### ISSUE THREAD

**Issue by pma** [basho/riak#1038]
Hi @martinsumner, @Bob-The-Marauder,

The Solr seach feature is not compiled in the 3.0 packages. Are there any plans for alternative packages with the search feature on, or will this be only available when compiling from sources.

The release notes mention the possibility of data loss when upgrading from 2.9 to 3.0. Do these same issues apply if doing a riak-repl transfer of data from a 2.9 cluster to a new 3.0 cluster?

Thank your for all the effort in keeping Riak alive!

**Comment by martinsumner** [comment]
The primary problem of data loss in the upgrade is related to the incompatibility of the solr versions, as I understand it.  riak 2.9 to riak 3.0 is a big leap in solr versions.

You may be able to avoid this with more creative solutions, such as using repl as you suggest which seems like a reasonable idea.   However, no such ideas have been subject to testing, so you would have to plan and prove this yourself (or find a commercial support partner willing to work with you on it).

The primary issue overall with yokozuna is some failing riak_test tests - see comment thread on [this PR](https://github.com/basho/yokozuna/pull/765).  These tests may reflect issues which aren't relevant to most people (e.g. changes to unicode handling) or they may be indication of fundamental issues,  Unfortunately, at this stage, no-one has had the time/motivation to work through these test failures and produce either updated code or an updated set of tests.  Without a sound test base it is hard to formally release a 3.0 with yokozuna, and commit to continuing to keep it up to date.

If you wish to make your own packages with solr, you can do this by including solr in rebar.config and running `make package` on your target platform.  It should work.

**Comment by pma** [comment]
@martinsumner Thanks for the info which is enough to get me going. I'm interested in the search feature so I'll put some work into testing the repl approach as an upgrade path and having a go at the failing tests.
