### ISSUE TITLE
yum repositories failing

### ISSUE THREAD

**Issue by adrmaas** [basho/riak#1042]
The installs from the yum repositories at packagecloud are failing:
```
failure: repodata/repomd.xml from basho_riak: [Errno 256] No more mirrors to try.
https://packagecloud.io/basho/riak/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 402 - Payment Required
```
Who would be responsible for the upkeep of the repos?  Is there another source for the RPM packages?

I did try an s3 location (s3.amazonaws.com/downloads.riak.com) that I found referenced in the documents but that returned `301 Moved Permanently`.

**Comment by martinsumner** [comment]
https://files.tiot.jp/riak/kv/ is the primary source for packages now.

These are maintained by @Bob-The-Marauder from TI Tokyo

**Comment by adrmaas** [comment]
> https://files.tiot.jp/riak/kv/ is the primary source for packages now.
> 
> These are maintained by @Bob-The-Marauder from TI Tokyo

Thanks!
