### ISSUE TITLE
PUT /search/schema/some_schema doesn't work in 3.0.7

### ISSUE THREAD

**Issue by vkatsuba** [basho/riak#1083]
Hi All,

I'm try create create schema in `riak 3.0.7` use:
```sh
curl -XPUT "http://localhost:8098/search/schema/some_schema" \
  -H 'content-type:application/xml' \
  --data-binary @some_schema.xml
```
But get error:
```sh
 <HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></BODY></HTML>
 ```
 Same error is provided when I will try create new index:
 ```sh
 curl -i -XPUT http://localhost:8098/search/index/some_index
```
But at the same time all is working as expected in `2.X` version of `riak`.
I tried to find information about how the API has changed, but unfortunately I cannot find it.
This is a some bug or API path or behaviors was changed in `3.X`? Many thanks for your time.

**Comment by martinsumner** [comment]
By default, Riak 3.x does not include yokozuna support (https://github.com/basho/riak/blob/develop-3.0/RELEASE-NOTES.md#riak-kv-301-release-notes).  As stated, you can add it back in yourself if you wish.

It was dropped from the formal packages, as there were a number of tests that broke after the solr uplift, and that included tests which appeared to be broken by changes in URL endpoints - https://github.com/basho/yokozuna/pull/767.  At the time there was no-on using Riak with yokozuna available to fund or work on an investigation to fix these things.

Are you using a special package with Yokozuna re-enabled?

**Comment by vkatsuba** [comment]
Hi @martinsumner, many thanks for feedback. I'm try to use package from https://files.tiot.jp/riak/kv/3.0/3.0.7/ as you recommend in topic https://githubmemory.com/repo/basho/riak_kv/issues/1791. The main reason of using of latest version is that the `2.X` is builded use OPT 20 where the `tlsv1.3` is not supported. I see that [riak_api/src/riak_api_ssl.erl#L37](https://github.com/basho/riak_api/blob/develop-3.0/src/riak_api_ssl.erl#L37) is used by default `'tlsv1.2'` but can be configured, but at the same time if `riak` is builded with using oldest OTP version we cannot use ``tlsv1.3`` :disappointed:.

**Comment by vkatsuba** [comment]
I suppose this ticket can be closed. Many thanks for your help @martinsumner!

**Comment by martinsumner** [comment]
Apologies, I've not had time to look again at yokozuna/3.x since we hit the original issues.  It might not be hard to fix.  The schema API problem seems like something basic with webmachine routes not loading. 

If I get some spare time, I may perhaps try again to investigate.

**Comment by vkatsuba** [comment]
Thanks!
