### ISSUE TITLE
Build fails on Fedora 35 on Erlang OTP-24 

### ISSUE THREAD

**Issue by ghost** [basho/riak#1091]
[grigorii@Manolin ~]$ cd riak
[grigorii@Manolin riak]$ make rel
/home/grigorii/riak/rebar3 compile
===> Fetching rebar3_cuttlefish (from {git,"https://github.com/basho/rebar3_cuttlefish",
                             {tag,"0.2.0"}})
===> Fetching cuttlefish (from {git,"git://github.com/basho/cuttlefish.git",{tag,"2.1.0"}})
===> Fetching getopt (from {git,"git://github.com/jcomellas/getopt.git",{tag,"v1.0.1"}})
===> Fetching lager (from {git,"git://github.com/erlang-lager/lager.git",{tag,"3.8.0"}})
===> Fetching goldrush v0.1.9
===> Version cached at /home/grigorii/.cache/rebar3/hex/hexpm/packages/goldrush-0.1.9.tar is up to date, reusing it
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/tmp/cirrus-ci-build/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:29: compile] Ошибка 127

**Comment by martinsumner** [comment]
OTP 24 is not supported yet.  OTP 22 is the most advanced version you can use with `develop-3.0`

**Comment by martinsumner** [comment]
We're planning to start work on OTP 24 support in January.

**Comment by ghost** [comment]
Thank you very much, Martin!
