### ISSUE TITLE
I got an error when I executed `riak-admin cluster join node` 

### ISSUE THREAD

**Issue by dongwooklee96** [basho/riak#1105]
hi,
I cloned source code from develop branch from now on.
and do `make devrel`.

![Screen Shot 2022-03-25 at 13 51 31](https://user-images.githubusercontent.com/14002238/160056606-fffe24a6-98f4-4aef-a8fa-e1d3b93f0757.png)

and I started `dev1`, `dev2`, `dev3` node then I executed `./riak-admin cluster join dev1@127.0.0.1`
I got an error like below.

```
./riak-admin: 238: relx_nodetool: not found
```

Who can solve this problem?

**Comment by martincox** [comment]
@dongwooklee96 there will be unstable changes at the head of develop. You might want to try checking out the latest release on tag riak-3.0.9 👍🏻

**Comment by martincox** [comment]
Also, just to point out, not sure if it was because you were testing, but you shouldn't need to execute the riak-admin script directly, it can be invoked using the main riak bin script, like so `dev/dev1/riak/bin/riak admin cluster join dev1@127.0.0.1`

**Comment by dongwooklee96** [comment]
@martincox 
thank you for your reply!  but I got another error while configuring

![Screen Shot 2022-03-25 at 16 45 44](https://user-images.githubusercontent.com/14002238/160076960-e98d90e2-8215-4bab-8dee-ae469f607988.png)

Failed to fetch and copy dep: {git,"git://github.com/basho/canola.git",
                                  {ref,
                                      "2cd39378442f3dc727de22289243b3c4d56f25fd"}}

**Comment by martincox** [comment]
Ah, this is because github have deprecated the use of the git:// protocol, which some dependencies used in the last release (spill over legacy stuff). To overcome this, you can set git config, like so `git config --global url."https://github".insteadOf git://github`

**Comment by dongwooklee96** [comment]
I can build now thank you! but I still got the same problem in branch `riak-3.0.9`
```
git checkout 
make devrel

dev/dev1/riak/bin/riak start
dev/dev2/riak/bin/riak start
dev/dev3/riak/bin/riak start

dev/dev2/riak/bin/riak-admin cluster join dev1@127.0.0.1
```
![Screen Shot 2022-03-25 at 17 01 44](https://user-images.githubusercontent.com/14002238/160079269-f764d9aa-daa6-4731-8234-db149223b9f7.png)

**Comment by martincox** [comment]
Try with no hyphen between `riak admin`.


👍🏻 `dev/dev1/riak/bin/riak admin cluster join dev1@127.0.0.1`
👎🏻 `dev/dev1/riak/bin/riak-admin cluster join dev1@127.0.0.1`

Out of curiosity, what docs have you referred to? A change was put out some time ago, where the commands move from `riak-admin` to `riak admin` (confusing, I know). Wondering what docs need updating to make it clear.

**Comment by dongwooklee96** [comment]
It works now. you're my hero thank you :smile:

![Screen Shot 2022-03-25 at 17 21 58](https://user-images.githubusercontent.com/14002238/160082314-844de731-8aee-4c16-94fd-d5547c2b0bf5.png)




I'm reading this book [seven-database-weeks](https://www.amazon.com/Seven-Databases-Weeks-Modern-Movement/dp/1934356921) but it seems hasn't been revised. or maybe I have an old version.

**Comment by martincox** [comment]
That makes sense, it probably references a pre 3.* release of riak 👍🏻
