### ISSUE TITLE
upgrade folsom

### ISSUE THREAD

**Issue by joewilliams** [basho/riak#1140]
Hello 👋 I am the maintainer of folsom, long ago it moved to https://github.com/folsom-project/folsom when Boundary (the company I worked for) stopped existing. It looks like riak uses an old fork from the original project at https://github.com/boundary/folsom that I no longer have access to. I tagged 1.0 a while back and it might be good to upgrade https://github.com/folsom-project/folsom/releases/tag/1.0 and move over to the maintained repo.

**Comment by martinsumner** [comment]
Hello @joewilliams.  I double-checked and Riak is pulling in folsom vie exometer_core 1.6.1 - https://github.com/basho/riak_core/blob/develop/rebar.config#L26 - which I believe fetches version 1.0 from hex.  This is true on both Riak's current release streams (develop/3.2.n, develop-3.0/3.0.n).  So I think Riak is lined up with you, unless I've made a mistake.  Thanks for the continued work.

**Comment by joewilliams** [comment]
Oh great, somehow I missed that completely. I think I saw this old fork (https://github.com/basho/folsom) and got concerned riak was still using it. Thanks for taking a look!
