### ISSUE TITLE
All the Download Links are Broken 

### ISSUE THREAD

**Issue by faradawn** [basho/riak#1141]
Hi,

I have been trying to download Riak KV, but all the links on the [office download page](https://docs.riak.com/riak/ts/latest/downloads/index.html) seemed broken. For example: the [Ubuntu download link](http://s3.amazonaws.com/downloads.riak.com/riak/2.2/2.2.3/ubuntu/precise/riak_2.2.3-1_amd64.deb ) had this error:
```
<Error>
<Code>PermanentRedirect</Code>
<Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
<Endpoint>downloads.riak.com.s3.amazonaws.com</Endpoint>
<Bucket>downloads.riak.com</Bucket>
<RequestId>1274HYXYH7591G7C</RequestId>
<HostId>2i3r3x0cU9yRa1WnZbSUIyTZh/ZIUXmTXtV3GTrv2IXhwp0GIrwfA/IYQpsdMzgDCC68DG9di8s=</HostId>
</Error>
```

How can I download KV? Thanks in advance!

**Comment by sinban04** [comment]
@faradawn (cc. @martinsumner )
Hi i'm just a passer-by, and take a look this issue: https://github.com/basho/riak_kv/issues/1821
new link available: https://files.tiot.jp/riak/kv/

**Comment by faradawn** [comment]
Hi @sinban04,

The links were fixed! Thanks very much for leaving the comment!

Best,
Faradawn
