### ISSUE TITLE
relx_nodetool: not found - what is relx_nodetool?

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak#1144]
After building 3.0.16 from source with OTP 22.3.4.26 on Ubuntu 22.04 the following error happens:

`$ sudo riak-admin status
/usr/local/riak/bin/riak-admin: 740: relx_nodetool: not found`

What is relx_nodetool and where to find one? It does not come with either **relx** library or **rebar3** or Riak KV itself

**Comment by martinsumner** [comment]
Use `sudo riak admin status` not `riak-admin`.  All admin commands are in now this form since Riak 3.0.

**Comment by oleksiyk** [comment]
Thanks!
