### ISSUE TITLE
libssl0.9.8 missing

### ISSUE THREAD

**Issue by pilt** [basho/riak#119]
```
$ uname -a
Linux server-53911 3.0.0-12-virtual #20-Ubuntu SMP Fri Oct 7 18:19:02 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux
$ riak version
Attempting to restart script through sudo -u riak
riak (1.0.2 2011-11-17) Debian x86_64
```

Installed from deb file: `dpkg -i riak_1.0.2-1_amd64.deb`.

From `/var/log/riak/error.log`:

```
2012-02-11 15:46:15.288 [error] <0.322.0> Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /usr/lib/riak/lib/crypto-2.0.3/priv/lib/crypto: 'libcrypto.so.0.9.8: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.
2012-02-11 15:46:15.308 [error] <0.311.0> webmachine error: path="/mapred"{error,{error,undef,[{crypto,sha,[<<131,104,3,98,0,0,5,48,98,0,14,225,71,98,0,4,89,11>>]},{riak_kv_mrc_pipe,'reduce2pipe',5},{riak_kv_mrc_pipe,'-mr2pipe_phases/1-lc$^0/1-0-',3},{riak_kv_mrc_pipe,'-mr2pipe_phases/1-lc$^0/1-0-',3},{riak_kv_mrc_pipe,'mr2pipe_phases',1},{riak_kv_mrc_pipe,mapred_stream,1},{riak_kv_wm_mapred,pipe_mapred,2},{webmachine_resource,resource_call,3}]}}
```

`apt-get install libssl0.9.8` solves the error.

**Comment by jaredmorrow** [comment]
This bug was fixed, the proper dependencies are now listed, so the package installation will fail if the proper libssl library is not installed.

**Comment by bflueras** [comment]
Hi,  
I've got the same pb. Any hints other than manually installing?

OS: Linux version 2.6.32-279.el6.x86_64 (mockbuild@sl6.fnal.gov) (gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC) ) #1 SMP Thu Jun 21 07:08:44 CDT 2012

uname -a
Linux machine 2.6.32-279.el6.x86_64 #1 SMP Thu Jun 21 07:08:44 CDT 2012 x86_64 x86_64 x86_64 GNU/Linux
riak version
riak (1.2.1 2012-10-16) RedHat x86_64

openssl version #latest for my OS
OpenSSL 1.0.0-fips 29 Mar 2010

cat /var/log/

2013-02-06 12:36:45.527 [error] <0.1602.0> Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /usr/lib64/riak/lib/crypto-2.1/priv/lib/crypto: 'libcrypto.so.6: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

**Comment by jaredmorrow** [comment]
That is interesting.  What Riak package are you using?  If you uninstall Riak and try installing the package with Yum does that help the issue?  

The original bug was us not listing the dependency properly in the RPM package, but that has since been fixed, so I am really curious what is going on with your install.

**Comment by bflueras** [comment]
Hi Jared,
I reinstalled riak with yum and the problem was solved.
Thanks,

**Comment by jaredmorrow** [comment]
Bogdan,

Oh, great.  Did you happen to notice if the yum command installed anything else along side the riak package?

If you have any other troubles, feel free to email me jared at basho dot com.
