### ISSUE TITLE
bin/riak start does not like cd->pwd

### ISSUE THREAD

**Issue by davidmathei** [basho/riak#123]
Not really a big issue. But annoying anyway. 

The system I work on does a `pwd` after a `cd <dirname>`, causing 

   RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)

to receive two directory strings separated by white space. 

I changed it to 

   RUNNER_SCRIPT_DIR=$(cd ${0%/*} > /dev/null && pwd)

and it works again.

**Comment by jaredmorrow** [comment]
This part was removed in #268 so I will close this issue now.
