### ISSUE TITLE
Beams in basho-patches don't take precedence over existing code

### ISSUE THREAD

**Issue by dreverri** [basho/riak#126]
The code path "lib/basho-patches" was recently added to Riak's start up using the "-pa" flag:
https://github.com/basho/riak/blob/083f666f597c81b2a9a336d30421dcb18813c012/rel/files/riak#L232
https://github.com/basho/riak/blob/083f666f597c81b2a9a336d30421dcb18813c012/rel/files/riak-admin#L341
https://github.com/basho/riak/blob/083f666f597c81b2a9a336d30421dcb18813c012/rel/files/riak-admin#L361
https://github.com/basho/riak/blob/083f666f597c81b2a9a336d30421dcb18813c012/rel/files/riak-admin#L380
https://github.com/basho/riak/blob/083f666f597c81b2a9a336d30421dcb18813c012/rel/files/riak-admin#L398

Unfortunately, it does not appear that beams in this directory override existing beams. For example, Riak ships with a patched "etop_txt.beam" but on start up code:clash/0 indicates this version is hidden:

```
/usr/lib/riak/lib/observer-0.9.10/ebin/etop_txt.beam hides /usr/lib/riak/lib/basho-patches/etop_txt.beam
```

Also, code:which/1 does not show the patched version:

```
(riak@127.0.0.1)1> code:which(etop_txt).
"/usr/lib/riak/lib/observer-0.9.10/ebin/etop_txt.beam"
```

**Comment by Vagabond** [comment]
I just ran into this. It needs fixing.

**Comment by Vagabond** [comment]
I found out why this happens, RUNNER_LIB_DIR is wrong when we build a package (for local builds it is ./lib, which is correct).

Proof:

```
riak      2881 45.8 31.9 20680564 10537320 pts/2 Ssl+ Aug07 2137:20 /usr/lib/riak/erts-5.9.1/bin/beam.smp
 -K true -A 64 -W w -- -root /usr/lib/riak -progname riak -- -home /var/lib/riak -- -boot 
/usr/lib/riak/releases/1.2.0/riak -embedded -config /etc/riak/app.config -name riak@10.0.27.22 -setcookie
riak4_2itesting -pa /usr/lib/riak/basho-patches -- console
```

So you can see that -pa /usr/lib/riak/basho-patches is there

but:

```

athompson@r1s12:/usr/lib/riak/lib/basho-patches$ ls /usr/lib/riak/basho-patches/
ls: cannot access /usr/lib/riak/basho-patches/: No such file or directory
```

And in the riak script:

```
RUNNER_LIB_DIR={{platform_lib_dir}}
...
 -pa $RUNNER_LIB_DIR/basho-patches \
```

The path _should_ be /usr/lib/riak/lib/basho-patches/

RUNNER_LIB_DIR is used nowhere else in the file, so it should be safe to fix.

This happened with the ubuntu package, have not tested the others, but it also looks broken for the other platforms.

**Comment by jonmeredith** [comment]
Fixed.
