### ISSUE TITLE
ERROR: OTP release R15B01 does not match required regex R13B04|R14

### ISSUE THREAD

**Issue by spaquet** [basho/riak#131]
ERROR: OTP release R15B01 does not match required regex R13B04|R14
Blocking error while compiling RIAK on OS X Lion 10.7.3 with erlang R15B01 installed via "brew install erlang". Pretty strange as http://wiki.basho.com/Installing-on-Mac-OS-X.html mentions that  "Riak requires Erlang R14B03 or later"

**Comment by kamidev** [comment]
These four files contain regexes that assume R14 is the highest OTP version.

riak/rebar.config
riak/deps/cluster_info/rebar.config
riak/deps/riak_kv/rebar.config
riak/deps/riak_search/rebar.config

Fixing this makes everything compile under OS X Lion. The README sample code and basic tutorial stuff appear to work, too.

**Comment by spaquet** [comment]
Perfect.

I confirm that make all, make rel and mak devrel are working after this patch.

This would be great if included in next src or git release of risk.

**Comment by PharkMillups** [comment]
We're working on better out-of-the-box support for R15B01. Thanks for using the work-around for now.

**Comment by spaquet** [comment]
Great
