### ISSUE TITLE
riak-admin incomplete regex for node name

### ISSUE THREAD

**Issue by ghost** [basho/riak#135]
riak script:
`NAME_ARG=`egrep '^-s?name' $RUNNER_ETC_DIR/vm.args``

riak-admin script:
`NAME_ARG=`grep '-[s]*name' $RUNNER_ETC_DIR/vm.args``

This doesn't filter out commented node names.

**Comment by seancribbs** [comment]
@mirell PR? Should be a simple fix and make it before feature freeze.

**Comment by jaredmorrow** [comment]
Fixed here https://github.com/basho/riak/pull/175
