### ISSUE TITLE
Typo in riak_client:stream_list_keys/4

### ISSUE THREAD

**Issue by brianshumate** [basho/riak#142]
At line 543 in `riak_client`, the module name appears to be singular `build_filter` when perhaps it should be plural `build_filters`.

This report stems from a ticket (1429) so I am posting the report on behalf of the customer who noticed it. I did verify that the typo is present in Riak 1.1.2 release and Github master.

Thank you,

Brian

**Comment by seancribbs** [comment]
Duplicate of basho/riak_kv#326

**Comment by brianshumate** [comment]
Sorry about that. I did do a search for "riak_client:stream_list_keys" prior to submitting, but nothing came up.
