### ISSUE TITLE
Stats for JS MapReduce

### ISSUE THREAD

**Issue by subnetmarco** [basho/riak#158]
It would **really** useful to see some stats about the JS VM when running MapReduce jobs (like average number of VM used, average memory consumption for map and reduce phases, etc). This would be useful for perfect tuning.

**Comment by jaredmorrow** [comment]
Stats are being re-inestigated in 2.1 with the Exometer package, will set the milestone for 2.1.

See: https://github.com/basho/riak/pull/448

**Comment by martincox** [comment]
JS is dead now.
