### ISSUE TITLE
"riak reboot" shuts down the node

### ISSUE THREAD

**Issue by ghost** [basho/riak#162]
Right now, "riak reboot" shuts down the node if heartbeat is not enabled. This is non-intuitive, and misleading.

See https://issues.basho.com/show_bug.cgi?id=1332

**Comment by jaredmorrow** [comment]
Agreed, this needs to be fixed.  I will set the milestone to post 1.4 to look at redoing this.

**Comment by ghost** [comment]
It's kind of a shame it's been two years, and 'riak reboot' still does the same thing: https://github.com/basho/node_package/blob/develop/priv/base/runner#L270

I guess the documentation was updated at least to note the heartbeat. ...apparently not: http://docs.basho.com/riak/latest/ops/running/tools/riak/#reboot

Maybe it's documented in 'vm.args' ... http://docs.basho.com/riak/2.0.0pre5/ops/advanced/configs/configuration-files/#vm-args ...no.

Le Sigh.

**Comment by bsparrow435** [comment]
PR's welcome.

**Comment by ghost** [comment]
Considering it seems no one uses heartbeat, the optimal solution appears to
be to deprecate this function, note it in the man page, remove it from the
command list help output, add a sanity check to see if vm.args is
configured for heartbeat, and if not, refuse to run the command, and add
help text that they probably meant 'restart'.

That way, if anyone actually does use it as intended, it's not broken.

On Tuesday, December 24, 2013, Brian Sparrow wrote:

> PR's welcome.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak/issues/162#issuecomment-31172056
> .

## 

*===================| Tryn Mirell     || tryn@mirell.org tryn@mirell.org
|| +1.512.394.3620 |==================="Even imperfection itself may have
its ideal or perfect state." Thomas de Quincey *

**Comment by bsparrow435** [comment]
I believe after 2.0 the plan is to deprecate this as well as `riak restart` but the method for doing so has not yet been decided. Your proposed solution sounds great, if you have time to implement that would be great. Otherwise this will wait until a point release after 2.0 at the earliest i'd assume.

**Comment by jaredmorrow** [comment]
Removed reboot completely.  Restart will be reworked to continue working with our longer shutdown and startup times.
