### ISSUE TITLE
Using pkg_add on FreeBSD after installing Riak results in "no origin recorded" warnings

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak#167]
Sample output:
freebsd64_test1# pkg_add -r sudo
Fetching ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9.0-release/Latest/sudo.tbz... Done.
pkg_add: package riak-1.2.0pre1 has no origin recorded
pkg_add: package riak-1.2.0pre1 has no origin recorded
Fetching ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9.0-release/All/libiconv-1.13.1_1.tbz... Done.
pkg_add: package riak-1.2.0pre1 has no origin recorded
pkg_add: package riak-1.2.0pre1 has no origin recorded
Fetching ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9.0-release/All/gettext-0.18.1.1.tbz... Done.
pkg_add: package riak-1.2.0pre1 has no origin recorded
pkg_add: package riak-1.2.0pre1 has no origin recorded
pkg_add: package riak-1.2.0pre1 has no origin recorded

**Comment by ghost** [comment]
That's because the package is broken in several ways. I'm surprised you got it to install at all.
