### ISSUE TITLE
FreeBSD package totally broken

### ISSUE THREAD

**Issue by ghost** [basho/riak#168]
Trying to install the generated .tar.gz on FreeBSD gives me this:

$ pkg_info ~apeiron/build/riak/riak-1.2.0pre1.tar.gz
tar: +*: Not found in archive
tar: Error exit delayed from previous errors.
pkg_info: tar extract of /usr/home/apeiron/build/riak/riak-1.2.0pre1.tar.gz failed!
pkg_info: error during unpacking, no info for '/usr/home/apeiron/build/riak/riak-1.2.0pre1.tar.gz' available
$

If I fix this by moving the +\* files into the top level directory, I get this:

$ pkg_info ~apeiron/build/riak/riak-1.2.0pre1.tar.gz
pkg_info: unable to open +CONTENTS file
$

Was this package tested _at all_? It's completely unusable.

**Comment by jaredmorrow** [comment]
Try checking the `packages` directory, you were trying to do a pkg_info command on the source tarball.

``` shell
$ pkg_info riak-1.2.0pre1-FreeBSD-amd64.tbz 
Information for riak-1.2.0pre1-FreeBSD-amd64.tbz:

Comment:
Riak highly scalable, fault-tolerant distributed database


Description:
Riak is an open source, highly scalable, fault-tolerant distributed database.

WWW: http://basho.com/products/riak-overview/
```

> Was this package tested at all? It's completely unusable.

Thanks for being levelheaded and polite about it.

**Comment by ghost** [comment]
On Jun 19, 2012, at 18:31, Jared Morrow wrote:

> Try checking the `packages` directory, you were trying to do a pkg_info command on the source tarball.
> 
> ``` shell
> $ pkg_info riak-1.2.0pre1-FreeBSD-amd64.tbz 
> Information for riak-1.2.0pre1-FreeBSD-amd64.tbz:
> ```

I don't see any documentation in the source tree (aside from the Makefiles) pointing me the package/packages directory. Where would it be appropriate to document this, and would you accept a pull request for such documentation?

**Comment by jaredmorrow** [comment]
Documentation will be written for 1.2 (when FreeBSD will be supported) when 1.2 is released.  The output of the `make package RELEASE=1` command shows where the package is copied so for people building from master it will at least give a hint.
