### ISSUE TITLE
Basho Wiki Bug Report

### ISSUE THREAD

**Issue by affinity-matrix** [basho/riak#176]
http://wiki.basho.com/How-to-Report-a-Bug.html 

still pointing users toward the defunct BugZilla tracker, which has lead to at least one fairly important (but apparently not _that_ important since there is no data loss) bug being unattended since November 2011.

**Comment by PharkMillups** [comment]
Thanks for catching that. I'm not sure how we overlooked it for so long. I'll take a stab at rewriting the copy tomorrow and shoot the commit your way for approval. 

> ... which has lead to at least one fairly important (but apparently not that important since there is no data loss) bug being 
> unattended since November 2011

Which bug are you talking about?

**Comment by affinity-matrix** [comment]
https://issues.basho.com/show_bug.cgi?id=1269

My bad... October 2011 *

**Comment by PharkMillups** [comment]
I just [updated](https://github.com/basho/riak_wiki/commit/a14f8104dcf3633a71625d14d76a8e7115ba91e6) the bug filing info on the wiki. Also, I [migrated](https://github.com/basho/riak_pipe/issues/47) the JS Built-In issue over to GitHub. It's still in need of resolution, but it'll get some more love on the GitHub repo.

**Comment by affinity-matrix** [comment]
\o/
