### ISSUE TITLE
Add notion of SmartOS projects `projadd`

### ISSUE THREAD

**Issue by jaredmorrow** [basho/riak#184]
More installation customization can be done by adding the notion of a Riak [project](http://docs.oracle.com/cd/E19044-01/sol.containers/817-1592/rmtaskproj-1/index.html).  This could be a possible usability win to make setup even easier in SmartOS.

**Comment by seancribbs** [comment]
:+1:

**Comment by jaredmorrow** [comment]
Added https://github.com/basho/riak/commit/eced9827cf350fd11bedf9a8e203edc258c6337e
