### ISSUE TITLE
riak 1.2 is not starting on mac os x lion

### ISSUE THREAD

**Issue by sendtopms** [basho/riak#185]
I compiled both from source as well as from the zipped version by basho.

Erlang R15B (erts-5.9) [source] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true]

21:00:14.839 [info] Application lager started on node 'riak@127.0.0.1'
21:00:14.875 [error] CRASH REPORT Process <0.59.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(riak_core_stat_cache, {register,riak_api,{riak_api_stat,produce_stats,[]},5}) in application_master:init/4 line 138
{"Kernel pid terminated",application_controller,"{application_start_failure,riak_api,{bad_return,{{riak_api_app,start,[normal,[]]},{'EXIT',{noproc,{gen_server,call,[riak_core_stat_cache,{register,riak_api,{riak_api_stat,produce_stats,[]},5}]}}}}}}"}

Crash dump was written to: ./log/erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,riak_api,{bad_return,{{riak_api_app,start,[normal,[]]},{'EXIT',{noproc,{gen_server,call,[riak_core_stat_cache,{register,ria

**Comment by seancribbs** [comment]
This is already being addressed by basho/riak_api#6
