### ISSUE TITLE
Update file RELEASE-NOTES.org

### ISSUE THREAD

**Issue by yeysus** [basho/riak#186]
Hi. The file RELEASE-NOTES.org only contains release notes until 1.1.2, current is 1.1.4-1. Is this intended or is the GitHub version not in phase with your downloadable packages? In other words: In which url can the actual, current version of Riak be found, other than going through the file list in http://downloads.basho.com/riak/CURRENT/? Thanks, Jesus

**Comment by jaredmorrow** [comment]
http://basho.com/resources/downloads/ is the new downloads site and downloads.basho.com has been phased out.  The release notes are current for the 1.2 release.

**Comment by yeysus** [comment]
On Sun, Aug 26, 2012 at 6:57 AM, Jared Morrow notifications@github.comwrote:

> http://basho.com/resources/downloads/ is the new downloads site and
> downloads.basho.com has been phased out. The release notes are current
> for the 1.2 release.
> 
> Hello Jared,

The page http://basho.com/resources/downloads/ goes to a page that loads
javascript and you have to click to move down to Riak / CURRENT, it is not
an easy scriptable url to determine if you have a newer version available.
Is the number of the current version available somewhere else?

Thanks,

Jesus
