### ISSUE TITLE
reip does not change claimant designation after node is renamed

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak#188]
Renaming the claimant node does not change the claimant in the ring file.  Steps to reproduce:

new-host-5:bin bsparrow$ ./riak start

new-host-5:bin bsparrow$ ./riak-admin ring_status
================================== Claimant ===================================
Claimant:  'riak@127.0.0.1'
Status:     up
Ring Ready: true

============================== Ownership Handoff ==============================
No pending changes.

============================== Unreachable Nodes ==============================
All nodes are up and reachable

new-host-5:bin bsparrow$ ./riak stop
ok

new-host-5:bin bsparrow$ vi ../etc/vm.args  #CHANGE NODE NAME

new-host-5:bin bsparrow$ ./riak-admin reip riak@127.0.0.1 new_name@127.0.0.1
Backed up existing ring file to "./data/ring/riak_core_ring.default.20120719173335.BAK"
New ring file written to "./data/ring/riak_core_ring.default.20120719173434"

new-host-5:bin bsparrow$ ./riak start

new-host-5:bin bsparrow$ ./riak-admin status | grep name
1-minute stats for 'new_name@127.0.0.1'
nodename : 'new_name@127.0.0.1'
ring_members : ['new_name@127.0.0.1']
ring_ownership : <<"[{'new_name@127.0.0.1',64}]">>

new-host-5:bin bsparrow$ ./riak-admin ring_status
================================== Claimant ===================================
Claimant:  'riak@127.0.0.1'
Status:     down
Ring Ready: unknown

============================== Ownership Handoff ==============================
No pending changes.

============================== Unreachable Nodes ==============================
The following nodes are unreachable: ['riak@127.0.0.1']

WARNING: The cluster state will not converge until all nodes
are up. Once the above nodes come back online, convergence
will continue. If the outages are long-term or permanent, you
can either mark the nodes as down (riak-admin down NODE) or
forcibly remove the nodes from the cluster (riak-admin
force-remove NODE) to allow the remaining nodes to settle.

**Comment by ybiruk** [comment]
I have the same issue

**Comment by seancribbs** [comment]
@bsparrow435 The new `riak-admin cluster replace` might be more appropriate, since `reip` was always broken and required the node to be down.

**Comment by drhip** [comment]
unfortunately I'm using version 1.1.2 and it doesn't support riak-admin cluster command

**Comment by jaredmorrow** [comment]
Closing the issue in favor of using `riak-admin cluster replace` in `reip`'s place.
