### ISSUE TITLE
Permissions not checked on $PIPE_DIR in riak script

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak#192]
If the /tmp/riak/ directory is owned by root user, riak start will fail but riak console will succeed. Add a permissions check on this directory.  Will attach PR shortly.

**Comment by bsparrow435** [comment]
https://github.com/basho/riak/pull/194

Looking for comments.

**Comment by jaredmorrow** [comment]
Fixed in 1.3 and master (1.4)
