### ISSUE TITLE
Change Makefile dev targets to depend on all.

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak#197]
Running `make devrel` or `make stagedevrel` on a fresh checkout or a cleaned copy of `riak` or `riak_ee` fails. The dev targets should depend on `all`.

**Comment by kellymclaughlin** [comment]
`riak`: https://github.com/basho/riak/pull/196
`riak_ee`: https://github.com/basho/riak_ee/pull/80

**Comment by jaredmorrow** [comment]
Fixed in the about PR's.
