### ISSUE TITLE
Riak 1.2.0rc6 won't start in SmartOS 1.6.3 zone because of a permissions issue

### ISSUE THREAD

**Issue by dreverri** [basho/riak#200]
## Steps to reproduce

Create a SmartOS zone using the following dataset and login to the zone

`f9e4be48-9466-11e1-bc41-9f993f5dff36 smartos 2012-05-02 sdc:sdc:smartos64:1.6.3`

Download and install Riak 1.2.0rc6

``` bash
curl -O http://s3.amazonaws.com/downloads.basho.com/riak/1.2/1.2.0rc6/smartos/11/riak-1.2.0rc6-SmartOS-i386.tgz
pkg_add riak-1.2.0rc6-SmartOS-i386.tgz
```

Enable riak-epmd and riak services

``` bash
svcadm enable riak-epmd
svcadm enable riak
```

Attempt to ping the riak node

``` bash
riak ping
Attempting to restart script through sudo -H -u riak
cat: /opt/local/lib/riak/releases/start_erl.data: Permission denied
/opt/local/sbin/riak[97]: /opt/local/lib/riak/erts-/bin/escript: not found [No such file or directory]
```
## Workaround

Change permissions on `/opt/local/lib/riak/releases/start_erl.data`

``` bash
chown -R riak:riak /opt/local/lib/riak/releases/start_erl.data
```

**Comment by jonmeredith** [comment]
I've also noticed ownership problems with /opt/local/etc/riak/vm.args - I have to chown root:riak to make things work.

**Comment by jonmeredith** [comment]
Although I didn't have any problems with the start_erl.data - were you on EE or OSS?

```
root@somemachine:/var/log/riak# ls -l /opt/local/lib/riak/releases/start_erl.data
-rw-r--r-- 1 riak riak 12 Aug  3 20:16 /opt/local/lib/riak/releases/start_erl.data
```

**Comment by dreverri** [comment]
OSS
