### ISSUE TITLE
Master make rel fail with 15B02

### ISSUE THREAD

**Issue by mkuznetsov** [basho/riak#229]
uname -a
Darwin Mikes.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

==> rel (generate)
ERROR: Failed to generate target from spec: "read file info /opt/local/lib/erlang/erts-5.9.2/otp_src/lib/kernel/test/code_SUITE_data/clash/zork-0.8.ez/zork-0.8/ebin/flarp.beam: not a directory"
make: **\* [rel] Error 1

**Comment by jaredmorrow** [comment]
We haven't yet tested fully on 15B02, but it _should_ build.  I will get 15B02 installed and take a look.  Thanks for the bug filing.

**Comment by mkuznetsov** [comment]
## After reinstall of erlang and clean clone of git repository (previous was updated with pull). Sources compiled fine and release generated without errors. So far it works.

Sincerely yours,
Mikhail Kuznetsov

When best practices meet everyday life and lead to perfection...

Oct 15, 2012, â 18:06 , Jared Morrow íàïèñàë(à):

**Comment by jaredmorrow** [comment]
Thanks for the update @mkuznetsov I will close this issue for now, but will still start testing 15B02 as well.
