### ISSUE TITLE
Get/Put FSM counting

### ISSUE THREAD

**Issue by macshonle** [basho/riak#240]
The get/put FSM supervision was changed in 1.2-perf and needs to be merged in with master for 1.3.

How stats are reported needs to be changed to work with this. And there are two other issues Jon suggested be worked on:

1.) "at the point it's time to go to read repair https://github.com/basho/riak_kv/blob/master/src/riak_kv_get_fsm.erl#L306 you could check with the get-fsm-process-tracker-thing and abandon the read repair state and go straight to finalize so the process would exit sooner (possibly bonus points for making read repair less likely once a threshold was hit - always read repair while under 1000 (configurable), probability of read repair linearly reduces to 0 as you approach 2000 (configurable). "

2.) "making the default come from the appenv instead of here https://github.com/basho/riak_kv/blob/master/src/riak_kv_get_fsm.erl#L74  is probably smart too."

**Comment by russelldb** [comment]
Erm, woah. Can we talk, 'cos I'm worried about the merges for the stats work I've done with the fsms?

**Comment by lordnull** [comment]
@russelldb Sure, ping me when you've got a minute.

**Comment by jaredmorrow** [comment]
@mshonle @lordnull has this been merged in to master for 1.3 yet?

**Comment by lordnull** [comment]
Alas, not yet, there was an issue preventing it from being ready (yet).
