### ISSUE TITLE
nodetool needs to play better with common unix tools

### ISSUE THREAD

**Issue by evanmcc** [basho/riak#246]
I get a long hang and then this:

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

whenever I pipe shell output to 'head'.

**Comment by jaredmorrow** [comment]
Are you piping standard out, or standard error or all?

**Comment by evanmcc** [comment]
Just stdout.

**Comment by jaredmorrow** [comment]
This appears to be fixed in 2.0.
