### ISSUE TITLE
Investigate and correct NIF issues that lead to stuck schedulers

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak#247]
This issue is a catch all for work being done to correct NIF usage in Riak. Links to relevant issues will be added as comments.

**Comment by kellymclaughlin** [comment]
[Eleveldb write thread pool](https://github.com/basho/eleveldb/issues/43)

**Comment by jaredmorrow** [comment]
This was addressed in the Riak 1.3.0 release.
