### ISSUE TITLE
riak-admin backup should allow output to stdout

### ISSUE THREAD

**Issue by mrdrmmn** [basho/riak#249]
The backup functionality of riak-admin requires the user to specify an output file.  This means the system must write the backup locally (or to a network device).  When doing a dump of the entire cluster, this becomes somewhat problematic for a few reasons:
- The amount of IO on the node doing the backup is likely to cause performance problems.
- The node doing backups needs to have enough free space to store the entire contents of the cluster.

On a side note, I attempted to work around this limitation by using a named pipe as the output file and the streaming the data from the named pipe to STDOUT.  Unfortunately, the file:open command in erlang refuses to open anything that is not a regular file, so that is not possible.

**Comment by jaredmorrow** [comment]
This is a good idea and would add more flexibility to the backup process.  I know some other folks at Basho are rethinking backup/restore, but I do not know when that will land.

**Comment by jaredmorrow** [comment]
Backup/Restore is due for a complete rewrite in 2.1 as far as I know.

**Comment by jrwest** [comment]
`riak-admin backup` in its current incarnation has been deprecated. Given this is a feature request for that specific, deprecated, implementation I believe this should be closed as wontfix.

**Comment by jrwest** [comment]
backup was deprected in https://github.com/basho/riak_kv/pull/850
