### ISSUE TITLE
Riak logging provides no useful information

### ISSUE THREAD

**Issue by calston** [basho/riak#250]
Error log provides no useful insight to issues happening 

Eg. Supposedly this PUT request is wrong. It's impossible to see in what way aside from "badarg" which is meaningless. 

2012-11-30 11:49:01.998 [error] <0.4213.0> webmachine error: path="/riak/foo/foo1"
{error,{error,badarg,[{erlang,iolist_to_binary,[{hook_crashed,{riak_search_kv_hook,precommit,error,badarg}}],[]},{wrq,append_to_response_body,2,[{file,"src/wrq.erl"},{line,204}]},{riak_kv_wm_object,handle_common_error,3,[{file,"src/riak_kv_wm_object.erl"},{line,998}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,169}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,128}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,accept_helper,0,[{file,"src/webmachine_decision_core.erl"},{line,583}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,554}]}]}}

**Comment by calston** [comment]
Obviously the above error was because search was disabled in Riak but enabled in the bucket metadata. Obviously. I mean you can all see it, right? It didn't waste hours of my time for a really simple config mismatch for nothing, right??

**Comment by beerriot** [comment]
Indeed, you've found two different problems: basho/riak_search#134 and basho/riak_kv#443. Sorry about that. This is partially left over from the days before Search was included in the regular Riak distribution, when it was impossible to disable it.

I assure you that there are many people worked up about improving our error-reporting.
