### ISSUE TITLE
Ubuntu init scripts returns incorrect status code

### ISSUE THREAD

**Issue by erikgrinaker** [basho/riak#252]
The Ubuntu package downloaded from http://downloads.basho.com.s3-website-us-east-1.amazonaws.com/riak/CURRENT/ubuntu/precise/riak_1.2.1-1_amd64.deb has an init script which returns a 0 status code for the status command even when Riak is not running:

```
$ /etc/init.d/riak status
riak is stopped
$ echo $?
0
```

The script should return zero when Riak is running, and non-zero when it isn't. This creates problems with Puppet and other configuration management systems that uses the status code of the init script to determine whether the service is running.

**Comment by jaredmorrow** [comment]
Yes, this was a bug in 1.2.1 when 'status' was added.  It has been fixed in this issue basho/riak#232 and will be available in the next release.

I will close this issue based on the existence of issue #232.
