### ISSUE TITLE
missing Erlang source

### ISSUE THREAD

**Issue by asomov** [basho/riak#255]
The README file says that the source is in 'app' folder. But this folder is not present in master branch. Where can I find the source ?

**Comment by jaredmorrow** [comment]
The source for erlang is a separate download and installation.  Please see [this page on our docs](http://docs.basho.com/riak/latest/tutorials/installation/Installing-Erlang/) for full instructions on how to install erlang.

**Comment by asomov** [comment]
The problem is that the WIKI is very misleading (because it says that the source is under the 'app' folder)

**Comment by jaredmorrow** [comment]
Agreed, that was very misleading.  It was referring to Riak source, not erlang source, but even then it was no longer in the App folder.  I have since removed that line.  We'll update the README in the coming months to get it more in line with docs.basho.com.
