### ISSUE TITLE
What are build prerequisites

### ISSUE THREAD

**Issue by asomov** [basho/riak#256]
I try to build from source and I get this error:

~/projects/riak$ make rel
./rebar get-deps
/usr/bin/env: escript: No such file or directory
make: **\* [deps] Error 127

What has to be installed ? (I am afraid the wiki page is out of date...)

**Comment by kuenishi** [comment]
Do you have erlang properly installed? Try running commands like erlc or
escript from the same console you tried make.

On Thursday, December 13, 2012, Andrey Somov wrote:

> I try to build from source and I get this error:
> 
> ~/projects/riak$ make rel
> ./rebar get-deps
> /usr/bin/env: escript: No such file or directory
> make: **\* [deps] Error 127
> 
> What has to be installed ? (I am afraid the wiki page is out of date...)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak/issues/256.

## 

Sent from Gmail Mobile, iPhone

**Comment by jaredmorrow** [comment]
Please look at [this page](http://docs.basho.com/riak/latest/tutorials/installation/) for the most up-to-date and accurate docs for installing both Erlang and Riak.

If you need more help, consider [joining our mailing-list](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com) or look us up on IRC, in #riak on Freenode.

**Comment by asomov** [comment]
I understand the problem now.  The '. ~/erlang/r15b01/activate' command is valid for a session only. It is so easy to forget it. 
Probably this page can be improved: http://docs.basho.com/riak/latest/tutorials/installation/Installing-Erlang/
