### ISSUE TITLE
http API /stats not working

### ISSUE THREAD

**Issue by kuenishi** [basho/riak#258]
Different result at different platform, but looks like a single-originated problem, When Riak is configured to use `riak_kv_eleveldb_backend` (or multi backend with eleveldb configured)

at current master ( d4414a7efe3b50067fb7 ),

:at MacOS: process down with following message:

mmap with hint 0x20000000 returned code memory 0xa6be1000

:at Linux: curl hangs and no reply

at released version (1.2.1),

riak returns 500 to curl. a message like function_cluase

**Comment by jonmeredith** [comment]
I'd be interested what'd in the error logs for the Linux 1.2.1 failure.

On OSX I suspect you've hit an issue with HiPE mmapping to 512Mb for native code (currently used by bear).  You could either try building the erlang VM with HiPE disabled, or you could modify deps/bear/src/bear.erl and comment out the -compile([native]) line.

**Comment by kuenishi** [comment]
OH, I tried again today and failed to reproduce at Linux with 1.2.1.

at MacOS as you said I just hit on the HiPE issue. and, 1.2.1 release on MacOS was caused this problem by using R15B03 (not supported) :

https://github.com/basho/riak_kv/issues/411
