### ISSUE TITLE
Integration Testing with Javascript

### ISSUE THREAD

**Issue by asomov** [basho/riak#260]
This is a proposal for a new test suite. The idea comes from CouchDB. They use the web-client (Futon) for integration tests. 

http://answers.oreilly.com/topic/1395-introduction-to-couchdbs-futon-administration-interface/

**Comment by seancribbs** [comment]
See [basho/riak_test](//github.com/basho/riak_test).

**Comment by asomov** [comment]
This is not a solution. It is far too heavy to install. It also requires Erlang knowledge to contribute. If the test suite is written in JavaScript then many more users may contribute their use cases.

**Comment by jaredmorrow** [comment]
We had a tool written in Python, but since Basho is primarily an Erlang shop we didn't contribute to it as much as we hoped as a team.  We wrote riak_test in erlang so that the primary test writers (the developers) would be more comfortable and able to write good tests quickly.

**Comment by asomov** [comment]
The idea is to be able to run tests with ZERO installation. You just point your browser to the URL and press a button.
This proposal does not mean that developers do not write Erlang tests. It just means that the tests can be written and run by anyone. If the project provides a basic framework to launch tests, the community can help to deliver more functional tests.
