### ISSUE TITLE
riak start failure after several seconds 

### ISSUE THREAD

**Issue by zhangwz** [basho/riak#263]
Hello, is there anyone could help me?

I just clone the riak from github, and everything is ok until i am running it.
 Riak will show some error message.

{"Kernel pid terminated",application_controller,"{application_terminated,os_mon,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,os_mon,shutdown})

My Erl Version:
Erlang R15B03 (erts-5.9.3) [source] [64-bit] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]

OS: Mac OSX 10.8.2

P.S. I did not meet the problem in https://github.com/basho/riak_api/pull/6 . My risk_api.app is ok.

{application,riak_api,
             [{description,"Riak Client APIs"},
              {vsn,"1.2.0"},
              {applications,[kernel,stdlib,lager,riak_core]},
              {registered,[riak_api_sup,riak_api_pb_sup]},
              {mod,{riak_api_app,[]}},
              {env,[]},
              {modules,[riak_api_app,riak_api_basic_pb_service,
                        riak_api_pb_frame,riak_api_pb_listener,
                        riak_api_pb_registrar,riak_api_pb_registration_helper,
                        riak_api_pb_server,riak_api_pb_service,
                        riak_api_pb_sup,riak_api_stat,riak_api_sup]}]}.

![ 2012-12-29 11 03 18 1](https://f.cloud.github.com/assets/876534/35289/0623fffa-51c9-11e2-9932-11e4ed13035b.png)

**Comment by PharkMillups** [comment]
Hello there, 

A quick glance at this makes me think it's related to R15B03 and/or your version of OS X (both of which I don't think we've tested against extensively yet). 

At any rate, this isn't a bug (yet), so it'll be easier to get it resolved on the [Riak Mailing List](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com). When you have five minutes, subscribe and post it over there. I'm going to close this for now. Free to reopen if you think it's warranted.
