### ISSUE TITLE
Unable to generate spec: read file info /usr/lib/erlang/man/man1/tasm.1.gz failed [JIRA: RIAK-3107]

### ISSUE THREAD

**Issue by alx** [basho/riak#270]
Hi,

I'm trying to build riak from source on Debian Wheezy, and Ive got the following error during `make rel`:

```
==> Entering directory `/home/alx/code/riak/rel'
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/tasm.1.gz failed
make: *** [generate] Error 1
```

Full logs: http://paste.kafe-in.net/6w

Could someone give me an hint?

thanks a lot,

Alex

**Comment by alx** [comment]
Solved this issue by removing tasm man files:

```
cd /usr/lib/erlang/man/man1/
sudo rm tasm*
```

**Comment by SnehaSahu05** [comment]
thanks for the solution.
I tried updating ElevelDB, editing 'rabar.config', but only this simple solution solved my issue
------------------
==> rel (generate)
ERROR: Unable to generate spec: read file info /deps/riak_control/test/javascripts/admin/css/css/css... failed
make: *** [generate] Error 1
------------------
solution
$ cd deps/riak_control/test/javascripts
$ sudo rm admin*
$ make rel
