### ISSUE TITLE
Unable to run riak after compilation

### ISSUE THREAD

**Issue by binarykitchen** [basho/riak#277]
Hello

I just compiled riak exactly according to http://docs.basho.com/riak/latest/tutorials/installation/Installing-on-Debian-and-Ubuntu/ on my Ubuntu 12.10 machine (because for 12.10 there is no apt-get repository for riak).

The make process was fine, no errors. Then I set the path to /home/xxx/projects/riak-1.2.1/rel/riak/bin

Now, when I run `riak start` it shows lots of warnings. The first one is:

!!!!
!!!! WARNING: /home/michael.heuberger/projects/riak-1.2.1/rel/riak/log not writable; logs and crash dumps unavailable.
!!!!

When I try `sudo riak start`, it says:
sudo: riak: command not found

Looks like the user `riak` and the riak service itself aren't installed yet.

I wonder if you could fix the installation guideline over there and explain how to create the user and the service after compilation?

Thanks,
Michael

**Comment by jaredmorrow** [comment]
The easiest option is to install the Ubuntu 12.04 package.  It will create a user for you, add a /etc/init.d script and make sure things are installed in the right spot.  

You can get the package and install it via:

```
wget http://downloads.basho.com.s3-website-us-east-1.amazonaws.com/riak/1.2/1.2.1/ubuntu/precise/riak_1.2.1-1_amd64.deb
sudo dpkg -i riak_1.2.1-1_amd64.deb
```

For the future, I will update the documentation for building from source to add some notes in there about creating a Riak user.  Sorry for the confusion.

**Comment by binarykitchen** [comment]
Thanks, will do!
