### ISSUE TITLE
Consider moving `ulimit` checks to nodetool

### ISSUE THREAD

**Issue by jaredmorrow** [basho/riak#278]
Right now we check `ulimit -n` in the `riak` script itself which tells you the ulimit on the active shell process, not necessarily the Erlang VM.  For users who give Erlang special limits the shell can falsely warn that ulimit is set too low.

**Comment by evanmcc** [comment]
If we're considering this, we should also consider moving the check into
riak_kv and logging from there. Maybe a start-up check and log of all the
system's arbitrary limits?

**Comment by jaredmorrow** [comment]
@evanmcc also a great idea

**Comment by savar** [comment]
yep.. would be great..

**Comment by evanmcc** [comment]
These two commits should take care of the issue.  Any opinions?

**Comment by jaredmorrow** [comment]
Still no riak_kv reviewer??  @evanmcc crack the whip!

**Comment by evanmcc** [comment]
jwest is on the case

**Comment by evanmcc** [comment]
both PRs merged, closing

**Comment by jaredmorrow** [comment]
Awesome, thanks @evanmcc
