### ISSUE TITLE
IPv6 broken in 1.3.0

### ISSUE THREAD

**Issue by tomascharvat** [basho/riak#279]
2013-02-24 01:12:51.206 [error] <0.1351.0>@riak_core_handoff_sender:start_fold:226 ownership_handoff transfer of riak_search_vnode from 'riak@vm2.**_.cz' 639406966332270026714112114313373821099470487552 to 'riak@bq.**_.cz' 639406966332270026714112114313373821099470487552 failed because of error:{badmatch,{error,nxdomain}} [{riak_core_handoff_sender,start_fold,5,[{file,"src/riak_core_handoff_sender.erl"},{line,101}]}]

host bq.**_.cz
bq.**_.cz has address 1.1.1.1
bq.***.cz has IPv6 address 2aaa:430:2ae::2

handoff port can be accessed via telnet over ipv6

I also found problem with epmd. By default it doesn’t listen on ipv6.
I tried to add -proto_dist inet6_tcp to the vm.args and then epmd binded to tcp6 but connection via telnet was not possible.

I'm curious in what setup did you find Ipv6 working.

**Comment by tomascharvat** [comment]
According to erlang R16A release notes, there shall be CPPFLAGS=-DEPMD6 to enable IPv6 support in epmd.
Compiled both erlang and riak with DEPMD6. EPMD finaly listen at tcp6 and its possible to connect via telnet. However riak cant start.
 sudo -u riak riak console
Exec: /usr/lib/riak/erts-5.9.1/bin/erlexec -boot /usr/lib/riak/releases/1.3.0/riak             -embedded -config /etc/riak/app.config             -pa /usr/lib/riak/basho-patches             -args_file /etc/riak/vm.args -- console
Root: /usr/lib/riak
{error_logger,{{2013,2,24},{14,2,23}},"Protocol: ~p: register error: ~p~n",["inet6_tcp",{{badmatch,{error,epmd_close}},[{inet6_tcp_dist,listen,1,[{file,"inet6_tcp_dist.erl"},{line,74}]},{net_kernel,start_protos,4,[{file,"net_kernel.erl"},{line,1314}]},{net_kernel,start_protos,3,[{file,"net_kernel.erl"},{line,1307}]},{net_kernel,init_node,2,[{file,"net_kernel.erl"},{line,1197}]},{net_kernel,init,1,[{file,"net_kernel.erl"},{line,357}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}]}
{error_logger,{{2013,2,24},{14,2,23}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.21.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.195>,<0.18.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,24},{reductions,443}],[]]}
{error_logger,{{2013,2,24},{14,2,23}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['riak@localhost',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2013,2,24},{14,2,23}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2013,2,24},{14,2,23}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}

**Comment by seancribbs** [comment]
@tomascharvat In the release notes we mentioned that IPv6 is not fully supported for the Erlang distribution protocol, but only that handoff and the HTTP and Protocol Buffers APIs supported it.  Until disterl/epmd and the name-resolution code fully support it, you will have to use IPv4 addresses for node names. See also http://erlang.org/pipermail/erlang-patches/2013-February/003528.html

**Comment by tomascharvat** [comment]
Thanks for link, appreciated. Do you refer to -name in vm.args by node name ?
So vm.args shall have -name riak@1.2.3.4, and then handoff may bind to ::0
Do members of the ring get handoff IPv6 trough gossip that use riak@1.2.3.4 ?
Is handoff, http, PB dual stack or IPv[4or6]only

**Comment by seancribbs** [comment]
Yes, the `-name` vm.args configuration parameter is different than the `handoff_ip` setting. Once connected over disterl, the nodes will query each other over that channel for the handoff IP before establishing handoff connections.

Currently, only HTTP is dual-stack, specified via multiple listeners. PB only supports one listener at the moment, so it will only allow one stack, the same is the case for handoff. I plan to look into multiple PB listeners for Riak 1.4.
