### ISSUE TITLE
Master branch does not build with the latest webmachine

### ISSUE THREAD

**Issue by jj1bdx** [basho/riak#280]
`riak start` did not work, i.e., the node was not coming up, with the latest webmachine, of https://github.com/basho/webmachine/commit/75203f1355064d3ebf3d3ca1d5a13d529933ed5f

Reverting the webmachine back before the commit to https://github.com/basho/webmachine/commit/64176ef9b270294ec940cd78fdf41ac5c1738a34
by `git checkout HEAD^^` and rebuilding the release by `make devrel` solved the problem.

This has been confirmed on R15B03 on Ubuntu 12.10 x86_64 FreeBSD 9.1-STABLE/amd64.

**Comment by seancribbs** [comment]
See basho/webmachine#128

**Comment by jj1bdx** [comment]
After the rollback on https://github.com/basho/riak_core/commit/161816de8cb690a9a958ae7b661aeb9152b2b9bf I confirmed now Riak started normally by `riak start`.
