### ISSUE TITLE
embedded option 

### ISSUE THREAD

**Issue by dergraf** [basho/riak#288]
In https://github.com/basho/riak/blob/master/rel/files/riak#L273 the erl option -embedded is used. The option -embedded doesn't exist in http://www.erlang.org/doc/man/erl.html, but the option '-mode embedded' therefore exists. If you use '-mode embedded'  instead a staging release can't boot anymore since it can't resolve the symlinked dependencies (missing vsn-suffix). 
My guess is that booting a staging release worked because of 'erl' ignoring the' -embedded' option and switched back to the default interactive mode. 

I tested this behavior on Mac OSX 10.8.2 and Erlang R15B03 (erts-5.9.3.1)

**Comment by jaredmorrow** [comment]
Thanks for reporting this, looks like it is an ancient holdover from Erlang R13 days.

**Comment by jaredmorrow** [comment]
Fixed in the above PR's, thanks for reporting it!
