### ISSUE TITLE
Add a max_object_size parameter to prevent customers uploading objects which are too large.

### ISSUE THREAD

**Issue by simonvc** [basho/riak#297]
To prevent the uploading of unreasonably large files to riak there should be a max_object_size parameter in app_config, with a sensible default that can be changed by the user.

Maybe: Have it return a 500 server error if the content type length is too large, with the error text being a recommendation to investigate riak-cs

**Comment by jaredmorrow** [comment]
Right now this would be incredibly customer-dependent as some networks would work fine with 500kb object sizes and some would fall on their face.  Closing due to lack of progress on this.

**Comment by jonmeredith** [comment]
Worth noting that you can now set maximum sizes though.

**Comment by jrwest** [comment]
related PR (for 1.4) https://github.com/basho/riak_kv/pull/836. the changes also exist today on [`develop`](https://github.com/basho/riak_kv/blob/develop/src/riak_kv_vnode.erl#L1516-L1523)
