### ISSUE TITLE
Missing "export_type" (try build riak-1.3.0 from source on R16B) 

### ISSUE THREAD

**Issue by adaptunit** [basho/riak#300]
mochiweb - to get rid of the message "parameterized modules..." I had to take manually  version 2.5.0 of mochiweb.

 . . . 

Missing announcements:  "export_type()."

Add "-export_type([db_ref/0,itr_ref/0])." to : 

riak-1.3.0/deps/eleveldb/src/eleveldb.erl
 . . . 

Add "-export_type([state/0])." to : 

riak-1.3.0/deps/riak_pipe/src/riak_pipe_vnode_worker.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_fwd.erl:37
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_rec_countdown.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_pass.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_tee.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_crash.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_builder.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_fitting.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_xform.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_w_reduce.erl
riak-1.3.0/deps/riak_pipe/src/riak_pipe_vnode.erl
riak-1.3.0/deps/riak_kv/src/riak_kv_pipe_index.erl
riak-1.3.0/deps/riak_kv/src/riak_kv_pipe_get.erl
riak-1.3.0/deps/riak_kv/src/riak_kv_mrc_map.erl
riak-1.3.0/deps/riak_kv/src/riak_kv_pipe_listkeys.erl
 . . . 

...compile totally crash with message:

riak-1.3.0/deps/riak_kv/src/riak_client.erl:25: parameterized modules are no longer supported

 . . . 

I hope that soon "riak_client" will be improve. 
with best regards...

**Comment by jaredmorrow** [comment]
There is nothing wrong with riak, we don't support Erlang 16b because our 1.3 branch of releases was developed when only Erlang 15b was available.  If you install Erlang 15B01, things will work as expected.
