### ISSUE TITLE
Wrong ERTS_PATH configuration on ubuntu/precise riak package

### ISSUE THREAD

**Issue by yssk22** [basho/riak#306]
Hi, I found a minor bug on init script included in riak_1.3.1-1_amd64.deb package.

init script says on https://github.com/basho/riak/blob/master/package/deb/debian_riak_init#L19

   ERTS_PATH=/usr/lib/riak/erts-5.7.5/bin

but the actual built package published on http://s3.amazonaws.com/downloads.basho.com/riak/1.3/1.3.1/ubuntu/precise/riak_1.3.1-1_amd64.deb contains erts-5.9.1 so that we need to modify the init script or put the correct configuration on /etc/default/riak to override after package installation.

It would be nice to fix this to make the build version configured in the init script.

**Comment by jaredmorrow** [comment]
This is indeed a bug, I will fix it as soon as possible.  Thank you for reporting it.

**Comment by jaredmorrow** [comment]
This is fixed by PR #268
