### ISSUE TITLE
riak-admin test should test against local node and/or each node in cluster

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak#307]
Proposed change: riak-admin test local and riak-admin test cluster

local: Do a read/write for a value where the local node is in the preflist
cluster: Do a batch of read/writes that cover preflists containing all nodes

riak-admin test can use legacy behavior or be switched to local functionality.

**Comment by jaredmorrow** [comment]
+100

**Comment by jonmeredith** [comment]
I believe Swift does something similar to the cluster test.  Agreed we should do something like this.  Question is what to do about exposing the keys to list buckets / list keys, although I suppose the current test code writes a visibile key/value.

**Comment by reiddraper** [comment]
Just use bucket `nothing-to-see-here-move-along-this-could-not-possibly-collide-with-a-user-bucket`

**Comment by jaredmorrow** [comment]
Setting milestone to 1.4++ unless you want to tell me something different @bsparrow435
