### ISSUE TITLE
Objects in Riak Search sometimes match based on their old values

### ISSUE THREAD

**Issue by rspeer** [basho/riak#315]
I believe this is the same issue reported here: http://riak-users.197444.n3.nabble.com/Issue-on-riak-search-when-update-bucket-tt4026629.html

Here's what's happening in my tests:
1. test_riak_10717-docs is a DB with about five documents in it. I have enabled search on it, via PUT /riak/test_riak_10717-docs, with the value {"props":{"search":true}}.
2. I PUT a document like this to /riak/test_riak_10717-docs/uuid-623bb1d0f9384fc4a3d76eacf47cc6e7?w=3&r=3 :
   {"text": "The sun is a mass of incandescent gas"}

(There are actually more fields in the document, but they seem irrelevant unless someone tells me that they're not.)
1. I GET /riak/test_riak_10717-docs/uuid-623bb1d0f9384fc4a3d76eacf47cc6e7?r=3 :
   {"text": "The sun is a mass of incandescent gas"}
2. I PUT a revised document to /riak/test_riak_10717-docs/uuid-623bb1d0f9384fc4a3d76eacf47cc6e7?w=3&r=3, using the X-Riak-Vclock header that I just got in step 3:
   {"text": "The sun is a miasma of incandescent plasma"}
3. I GET /solr/test_riak_10717-docs/select?wt=json&q=text:mass
   {"text": "The sun is a miasma of incandescent plasma"}
4. I GET /solr/test_riak_10717-docs/select?wt=json&q=text:miasma
   {"text": "The sun is a miasma of incandescent plasma"}

The document is indexed under both "mass" and "miasma", even though it does not contain the word "mass".

This happens maybe 1/3 of the time. The other times, it works correctly, only matching searches for "miasma".

How do I fix this? Is it a bug in Riak Search or a bug in how I'm using it?

**Comment by jaredmorrow** [comment]
This is a really stale bug that didn't appear to get looked at.  Sorry @rspeer, have you looked at Yokozuna in Riak 2.0?  

/cc @rzezeski on handling of this issue (close, keep open, etc.).

**Comment by rzezeski** [comment]
There are no plans to investigate this with the deprecation of legacy riak_search and the introduction of new search (Yokozuna).

**Comment by rspeer** [comment]
We have looked at Yokozuna, but we're not migrating to an unreleased version of Riak for it.

Currently we use secondary indices for text search, as a temporary measure. We are in the process of moving our searchable text off of Riak altogether. As this bug report shows, our use case hasn't been well supported by Riak.
