### ISSUE TITLE
ERROR: OTP release R16B does not match required regex R14B0[234]|R15

### ISSUE THREAD

**Issue by henglinli** [basho/riak#319]
Not support OTP R16B

**Comment by jaredmorrow** [comment]
This is not a bug, we haven't tested on 16B from 15B01.  The next step will be 15B03, then sometime down the road will be 16B.  Some people run Riak to the edge of what erlang can handle, so performance testing a new release is a difficult and time consuming task. For now, you can fork Riak and change the regex for your source builds.

**Comment by quantumpotato** [comment]
Where do I look up what to change it to?
