### ISSUE TITLE
Is Debian deprecation planned?

### ISSUE THREAD

**Issue by 1100110** [basho/riak#320]
It is no longer possible to install the Debian packages on any system that uses Debian as it's upstream package repository.  

Ah, I see.  You are building the packages on Ubuntu(guess), both OpenSSL AND glibc are too new, at least.  

If you need me to, I'll tell you which versions you should use and/or build a new Debian package that should work.

Debian Unstable has libc6 <= 2.13, Riak packages require  >= 2.15

**Comment by jaredmorrow** [comment]
We have separate Debian 6 packages available, that I build on a Debian 6 machine.

It has this libc installed

```
ii  libc-dev-bin                         2.11.3-4        
ii  libc6                                   2.11.3-4               
ii  libc6-dev                             2.11.3-4   
```

And here is the machine's version information:

```
buildbot@build-debian-6-64:~$ cat /etc/debian_version
6.0.7
buildbot@build-debian-6-64:~$ uname -rv
2.6.32-5-amd64 #1 SMP Mon Feb 25 00:26:11 UTC 2013
```

Are you using the Debian packages [found here?](http://docs.basho.com/riak/latest/downloads/)

**Comment by jaredmorrow** [comment]
Oh, to answer your deprecation question, we have no plans to deprecate Debian support.  The only deprecation plans we have coming up is dropping 32bit support in Riak 1.4.

**Comment by 1100110** [comment]
Sorry! I confused my attempts with the Ubuntu Packages.  The Ubuntu gives the (expected) libc error, the Debian package gives a "Error: Dependency is not satisfiable: libssl0.9.8 (>=0.9.8m-1)"

**Comment by jaredmorrow** [comment]
This is what I have

```
$ dpkg -l | grep libssl0.9.8
ii  libssl0.9.8                          0.9.8o-4squeeze14            SSL shared libraries
```

So either you don't have libssl0.9.8 installed or it is older version that should be updated.  Try simply `udo apt-get install libssl0.9.8` to see if it is installed.

**Comment by 1100110** [comment]
Ah, I see...  I've updated my system partially to unstable.
This is the libssl I have: libssl1.0.0:amd64 1.0.1e-2

Ok, I'm retarded. I can fix that. Thanks for the help!

**Comment by jaredmorrow** [comment]
FYI you can have libssl0.9.8 and libssl1.0.0 installed at the same time since they are two separate packages and not two versions of the same package.
