### ISSUE TITLE
Multi GET following a Search

### ISSUE THREAD

**Issue by remialvado** [basho/riak#321]
Hi,

for performance purposes, we'd like to implement a way to limit HTTP requests after a search. for the moment, we are doing : 
- 1 X GET on /solr/myBucket/search?...&fl=id
- 50 X GET on /riak/myBucket/...

We have already moved from sequential curl requests to parallelized ones but it is not enough. We are facing three possibilities : 
- add a new option to the /solr endpoint to return the full object stored in Riak KV. Something like /solr/myBucket/search?...&fl=@object. In this case, we'd change the "result" result node from 

``` xml
<result name="response" numFound="2" start="0" maxScore="0.0">
  <doc>
    <str name="id">myId1</str>
  </doc>
  <doc>
    <str name="id">myId2</str>
  </doc>
</result>
```

to 

``` xml
<result name="response" numFound="2" start="0" maxScore="0.0">
  <doc>
    <object id="myId1">
      <headers>
        <header name="Content-Type">application/json</header>
        ...
      </headers>
      <body>
{"foo":"bar"}
      </body>
    </object>
    <object id="myId2">
      <headers>
        <header name="Content-Type">application/json</header>
        ...
      </headers>
      <body>
{"foo":"baz"}
      </body>
    </object>
  </doc>
</result>
```
- add a new 'POST /riakmulti' endpoint which takes a list of ids as a parameter and returns a list of objects probably in the same format described above.
- use mapred endpoint with an erlang or javascript script to perform this but du to our high number of objects in our cluster (> 10M), it is not really fast for now :(

Second question is : should we do this in our own code or are you open to include such a feature into Riak mainstream if we create it and open a Pull Request for it ?

Thanks.

**Comment by abolibibelot** [comment]
Actually this is not only search-related, a multi-GET for the plain kv part would be nice too.

**Comment by jaredmorrow** [comment]
Setting milestone to 1.4.9, for lack of a better resolution as we are moving towards Yokozuna in Riak 2.0

**Comment by jrwest** [comment]
imo we should close as "wontfix". Riak Search has been deprecated in favor of Riak Search 2 in Riak 2.0 and 1.4.x releases will only contain bug fixes not new features. Multi-get for k/v data has been implemented at the client layer in most (if not all?) official clients. Perhaps @rzezeski @gburd @michellep have a different opinion though?

**Comment by remialvado** [comment]
We did not create a pull request for this one last year but we did implement the first option and it works quite well. cc @awetzel

**Comment by rzezeski** [comment]
The 1st option will never be added to legacy riak_search because it has been deprecated. I think considering a native multi-get feature for new search (Yokozuna) is an interesting idea but it need to be discussed by Basho and would likely not be done as suggested above since it a) assumes the Solr endpoint for querying (I'd like to see more general query + multi-get), b) assumes an XML content-type for return body and c) doesn't use a CDATA section.

**Comment by jaredmorrow** [comment]
Well since this is related to deprecated search, I'm closing this issue for now.
