### ISSUE TITLE
riak-debug does not found app_epath.sh

### ISSUE THREAD

**Issue by jj1bdx** [basho/riak#325]
when you do the following on the master branch

```
make rel
cd rel
riak/bin/riak start
riak/bin/riak-debug
```

The `riak-debug` cannot find the necessary `app_epath.sh` and gives the error as:

```
Required file app_epath.sh not found. Expected here:
/Users/kenji/src/riak/rel/riak/bin/../lib/app_epath.sh
See 'riak-debug -h' and manpage for help.
```

Copying the necessary file with this command

```
cp ../../riak/deps/node_package/priv/base/app_epath.sh ./lib/
(at rel/riak directory)
```

will solve this issue.  Installation problem?

(Working environment: OS X 10.8.3, R15B03-1)

**Comment by jaredmorrow** [comment]
Yes, this is a bug, app_epath.sh needs to be installed in the `rel/reltool.config` file.  /cc @fprimex have time to fix this  before 1.4 freeze?  Thanks for catching that @jj1bdx
