### ISSUE TITLE
Request to make Ubuntu 12.10 install docs clearer

### ISSUE THREAD

**Issue by ghost** [basho/riak#332]
I have spent about six hours over the past two days trying to get Riak working on Ubuntu 12.10. Why was it so difficult? Let me tell you.

[The installation documentation on the Basho website](http://docs.basho.com/riak/1.3.1/tutorials/installation/Installing-on-Debian-and-Ubuntu/) tells users to update their apt sources list and then simply `sudo apt-get install riak`.
This generates 403 errors for 12.10 (Quantal) because it looks for the package in the Quantal folder, which doesn't exist. [This Ask Ubuntu thread](http://askubuntu.com/questions/265347/how-to-install-riak-on-ubuntu-12-10) explains the issue well.

```
http://s3.amazonaws.com/downloads.basho.com/riak/1.3/1.3.1/ubuntu/ **PRECISE** /riak_1.3.1-1_amd64.deb
```

I also tried the [Installing From Package](http://docs.basho.com/riak/1.3.1/tutorials/installation/Installing-on-Debian-and-Ubuntu/#Installing-From-Package) and [Installing Riak From Source](http://docs.basho.com/riak/1.3.1/tutorials/installation/Installing-on-Debian-and-Ubuntu/#Installing-Riak-From-Source), the first not actually having any information on the site (it's just different headings with nothing underneath them), and the source installation, which I may be too much of a linux noob to use (but that didn't stop me from trying four different times to use source).

As a new user to the Basho website, I had no way of knowing what the correct solution was. I was taken directly to the [apt-get installation](http://docs.basho.com/riak/1.3.1/tutorials/installation/Installing-on-Debian-and-Ubuntu/). Another page told me that a git clone installation would work (it didn't), and that the git page would have more information. The git page simply says

"Assuming you have a working Erlang (R14B02 or later) installation, building Riak should be as simple as:

```
$ cd $RIAK
$ make rel
```

"

It took some time for me to stumble upon [this solution for riak 1.2.1](https://github.com/basho/riak/issues/277). It worked instantly for me, so I have modified it for 1.3.1 and tested it.
### This installs the very latest for Ubuntu 12.10 users

```
wget http://downloads.basho.com.s3-website-us-east-1.amazonaws.com/riak/1.3/1.3.1/ubuntu/precise/riak_1.3.1-1_amd64.deb
sudo dpkg -i riak_1.3.1-1_amd64.deb
```

Please put it somewhere other users of 12.10 will be able to see it

**Comment by jaredmorrow** [comment]
@worldhack this is indeed a bug in our documentation, we have the section you were looking for, but it was behind a version regex filter that didn't include 1.3.1.  I'm really sorry you had to take so much time to figure it out on your own.  The below linked PR will fix this issue moving forward.

**Comment by ghost** [comment]
Thank you for this
