### ISSUE TITLE
Another issue with documentation for 1.3.1

### ISSUE THREAD

**Issue by ghost** [basho/riak#334]
Riak 1.3.1
Ubuntu 12.10

I found one more thing in the documentation that has lead me to a dead end. The installation leads on to The Riak Fast Track, which leads on to [Building a Development Environment](http://docs.basho.com/riak/1.2.0/tutorials/fast-track/Building-a-Development-Environment/) where it asks new users to `make devrel`, which will deploy four development nodes. Apparently [this doesn't work with anything other than source installations](http://stackoverflow.com/questions/11139407/riak-os-x-installation?answertab=votes#tab-top), which makes 2/3rds of the previous installation section unapplicable without any warning. If I want to be able to follow The Riak Fast Track, do I now need to uninstall riak again and install it from source?

**Comment by jaredmorrow** [comment]
These are just suggested things you can do to find out more about Riak.  

When you click on "Riak" from the main docs.basho.com page, you are presented with a Getting Started page that lists the Fast Track first. 

![screen shot 2013-05-29 at 10 33 55 am](https://f.cloud.github.com/assets/718326/579996/c37a9fac-c87d-11e2-8037-9fd4825da850.png)

 You instead started at the install page, so it suggested other places to explore.
