### ISSUE TITLE
Too uneven balance when going from 4 to 5 nodes in 64 partion cluster

### ISSUE THREAD

**Issue by mwl** [basho/riak#348]
Due to some rounding issues in [wants_claim_v2/2](https://github.com/basho/riak_core/blob/master/src/riak_core_claim.erl#L174:L187) one node will claim 25% of all partitions when going from 4 to 5 nodes in a ring with 64 partitions.

Description by @rsltrifork:

> Every node checks if it should claim one or more partitions from other nodes. It does this, by calulating: 
> 
>    **ring_size div nodes > partitions_already_owned_by_me**
> 
> Which for ring_size=64 and a distribution of 12,12,12,12,16 returns false for all nodes:
> 
> 64 div 5 = 12, which is not more than the 12 already owned.

**Comment by jaredmorrow** [comment]
This is a known issue with the claim_v2 algorithm.  It is also why we suggest running with 5 nodes as a minimum.  There are already plans to fix this issue in the next version of the claim algorithm that is being written.
