### ISSUE TITLE
Broken APT Repository for Ubuntu Precise and Riak 1.4.0

### ISSUE THREAD

**Issue by MJDSys** [basho/riak#349]
The APT repository for Ubuntu Precise appears to have incorrect metadata in it, preventing Riak 1.4.0 from installing.  You can see the effect here: https://drone.io/github.com/MJDSys/goriakpbc/12 .

**Comment by jaredmorrow** [comment]
Sorry for the trouble.  We had some issues with packages and the repos
needed to be repopulated and this has obviously caused some issues.  We
will investigate and fix as soon as we can.

**Comment by jaredmorrow** [comment]
We have rebuilt the repos, please let us know if this has not fixed your issue @MJDSys 

Thanks for reporting it.

**Comment by UtahDave** [comment]
Thanks for the quick fix!

**Comment by MJDSys** [comment]
Everything is work great now!  Thanks for fixing it.
