### ISSUE TITLE
1.4.0 OS X i386 build?

### ISSUE THREAD

**Issue by xpe** [basho/riak#352]
I'm updating the Riak homebrew recipe. I don't see any link for a i386 build for 1.4.0. Does that mean 32 bit builds are gone? I don't personally need a 32 bit build; I just don't want to remove 32 bit support from the homebrew recipe if you guys are still supporting it.

Note: 1.4.0rc1 had a 32 bit build: http://docs.basho.com/riak/1.4.0rc1/tutorials/installation/Installing-on-Mac-OS-X/

**Comment by jaredmorrow** [comment]
That RC1 link was actually just broken and the documentation was not updated yet.  We no longer support 32bit builds on any platform.  Currently there is no plan to go back to 32bit in the future.

**Comment by xpe** [comment]
1.4.0 release notes are here: https://github.com/basho/riak/blob/master/RELEASE-NOTES.md (for reference)

**Comment by jaredmorrow** [comment]
That link will not always be for 1.4.

1.4 release notes are here https://github.com/basho/riak/blob/1.4/RELEASE-NOTES.md
