### ISSUE TITLE
Documentation on links is broken, refers to old link format

### ISSUE THREAD

**Issue by agemooij** [basho/riak#353]
All the docs on links at http://docs.basho.com/riak/ refer to the old "/riak/bucket/key" format for specifying a link target. Riak 1.3 and 1.4 reject (!) this format with a bad request error since the new format should be /buckets/BUCKET/keys/KEY

```
http put "localhost:8098/buckets/foo/keys/5" 'Link: </riak/foo/1>; riaktag="buddy"' data="awesome"

HTTP/1.1 400 Bad Request
Content-Length: 89
Content-Type: text/plain
Date: Fri, 12 Jul 2013 20:46:50 GMT
Server: MochiWeb/1.1 WebMachine/1.9.2 (someone had painted it blue)

Invalid Link header. Links must be of the form
</buckets/BUCKET/keys/KEY>; riaktag="TAG"
```

Im not sure when the old format was deprecated and I don't have riak 1.2 and earlier handy to test but for 1.3 and 1.4 the docs are clearly incorrect.

Most obviously incorrect docs:
- http://docs.basho.com/riak/1.3.0/references/appendices/concepts/Links/
- http://docs.basho.com/riak/1.4.0/references/appendices/concepts/Links/
- http://docs.basho.com/riak/1.3.0/cookbooks/Link-Walking/
- http://docs.basho.com/riak/1.4.0/cookbooks/Link-Walking/

All example outputs on the entire docs site also contain incorrect link headers

**Comment by jaredmorrow** [comment]
For future reference, documentation issues should be filed against the docs repo here https://github.com/basho/basho_docs

I don't think this is still an issue, but in case I'll /cc @lucperkins and @coderoshi   Please close if this is no longer relevant.
