### ISSUE TITLE
Add Bucket Types to Riak

### ISSUE THREAD

**Issue by jrwest** [basho/riak#362]
Today, keys in Riak are made up of two parts: the bucket they belong to and a unique identifier within that bucket. Buckets act as a namespace and allow for similar keys to be grouped. In addition, they provide a means of configuring how Riak treats that data.

In the next release of Riak several new features will take advantage of this namespacing. In discussing these features, it has become apparent that to properly support them a change to Riak's key structure must be made. The change is to introduce another layer of namespacing called the "Bucket Type". With Bucket Types each key is now made up of three parts: the bucket type it belongs to, a unique bucket within that type, and a unique identifier within that bucket.
## Why?

The primary driver for adding Bucket Types is the introduction of features like security and strong consistency which may wish to deal with groups of buckets (see the [Security RFC's](https://github.com/basho/riak/issues/355) wildcard
proposal). Without Bucket Types these features must rely using special prefixes in Bucket names. Since Bucket names have never been restricted this has undesireable edge cases. By introducing a new layer of namespacing these features can refer to groups of Buckets by Bucket Type.

There is an additional user-facing benefit of Bucket Types. In Riak, currently, users have the choice of either: a) conforming all buckets to the default bucket properties (stored in app.config) or b) setting many custom properties for buckets, which is known to scale poorly. This is especially frustrating if the user has buckets that
fit the default properties and another set that all use a different set of properties. Using Bucket Types, users will be able to define groups of buckets that share the same properties and only store information about each Bucket Type instead of individual buckets. In addition to internal changes made in Riak to help this issue, this will scale much better.
## Goals and Requirements
- Opt-In: All changes must not affect old APIs. For existing bucket (with or without custom properties) and data stored within them access and storage will remain the same.
- Zero data migration on upgrade (or downgrade if the user has not stored any data in a Bucket Type other than the default type).
- Properties can be set on Bucket Types. Buckets within that type are "inherited" by the Bucket. Any properties set on the Bucket override those set in the Bucket Type.
- Unlike Buckets, Bucket Types must be explicitly created. If a Bucket Type does not exist requests for data stored in that type will be rejected. This makes listing types quick and painless (a common gripe with Buckets).
## The Default Bucket Type

Internally, Riak will be changed to be aware of Bucket Types as necessary. However, they are still an opt-in feature and as such existing data (and new data written to existing buckets) must be handled appropriately.

To allow existing data to live in the world of Bucket Types, all existing buckets are assigned to the `default` type. Riak's existing APIs will inject and strip the type information where necessary.

To opt-in, a user must write data to in a non-default bucket type using new APIs. Unfortunately, this means additional work for client developers but since Riak will continue to happily work with the old APIs it is not necessary for clients to be updated before the release.
## APIs

As mentioned previously, no changes wil be made to existing APIs and in the case of protocol buffers all fields added will be optional.
### Create/Update/Read Bucket Types

HTTP endpoints and PB messages will be added to create, update and fetch the properties associated with a Bucket Type. In HTTP, this _might_ look like:

```
POST /types/<type>/props
PUT  /types/<type>/props
GET /types/<type>/props
```
### Object/Key API

The HTTP Fetch/Store/Delete API will be mirrored to take the Bucket Type. This _might_ look like:

```
GET /types/<type>/buckets/<bucket>/keys/<key>
PUT /types/<type>/buckets/<bucket/keys/<key>
..etc..
```

The correspoding protocol buffers messages will have an `optional` Bucket Type field added.
### 2i

The HTTP 2i API will be mirrored to take the Bucket Type. This _might_ look like:

```
GET /types/<type>/buckets/<buckets>/index/<index>/...
```

The corresponding protocol buffers messages will have an `optional` Bucket Type field added.
### Link Walking

Link walking will only be supported for data stored within the `default` bucket type. No API changes will be made.
### MapReduce

MapReduce will be extended to take inputs and queries in buckets other than the default type.
### Datatypes API

How the counters API will be extended is still undecided since work is ongoing to extend the API to support other datatypes. Of course the existing API will continue to work as promised by this RFC.
## Upgrading and Downgrading

Upgrading is handled naturally by the treatment of all existing data as a member of the `default` type.

Downgrading, however, is a bit more complicated. If a user has not opted-in by using the new APIs (or only writing to the `default` bucket type) then downgrading stands as it does for all versions of Riak.

For users that have opted in to the new features downgrading becomes more painful because older versions of Riak will not understand data stored in Bucket Types other than `default`. A user should only opt-in after upgrading to the new release and using the existing APIs until satisified that the upgrade does not harm the application. Rolling back to a version that does not support bucket types will require removing (or moving to the side) all data stored in the non-default type.

**Comment by gideondk** [comment]
Very good addition IMHO. Next to easier bucket configuration, a extra dimension really helps in structuring equally named buckets for different scenario's (instead of prefixing it yourself). 

Don't see any large problems in client implementation though... :-)

**Comment by brunogirin** [comment]
Is there any particular reason why link walking will be restricted to the `default` bucket type?

**Comment by peschkaj** [comment]
I don't see any large problems in client implementation, either. I'm going to guess that the .proto implementation will include an optional field for `type` which means sane protocol buffers clients shouldn't have to make any changes or do any version detection dance.

Barring a sudden introduction of new PBC methods, this looks good to me.

**Comment by jrwest** [comment]
@gideondk @peschkaj great! glad to hear you guys won't find it too be too much of a pain.

@brunogirin There is no technical reason why it cannot be added. We may do so in a future release depending on demand but for the upcoming release it probably won't make it in. For existing link walking users nothing will break, which I think is the most important thing. As usual an early community contribution is always welcome and I'll be happy to squeeze in a review where I can.

**Comment by uberbrady** [comment]
These don't really feel like types to me - more like "bucket groups". Separately, there seem to be some optional settings you can put in for all buckets that are in one group.

I don't know if I'm just bikeshedding here - but I feel like you could just allow for some "/" characters in a bucket - a sort of simple bucket hierarchy - and get most of what you need.

Buckets that aren't in any group - (normal-looking Riak URL's) would maybe stay the same; and grouped buckets would just have another slash in the bucket part of the URL.

e.g.

```
GET /riak/bucket/key
```

would be a GET for an object in a classic 'default' bucket

```
GET /riak/mygroup/bucket/key
```

would be a GET for an object in a grouped one.

I'm just looking at this from the point of someone who doesn't know the internals of Riak at all - so there could be all kinds of terrible things wrong with my counterproposal.

And ultimately I don't think it matters too much. But I do like the fact that the URL's I'm fetching things from stay looking pretty much the same, even if I use the new features.

**Comment by seancribbs** [comment]
@uberbrady I think it's more constructive to think of them outside the context of the HTTP API. It clouds the issue.

**Comment by jrwest** [comment]
@uberbrady one thing I didn't realize upon first read is your version used the already "old" API and the RFC uses the "newer" APIs. The APIs you are referring to are not yet deprecated within Riak but they are also not commonly extended ([for example](https://github.com/basho/riak_kv/pull/422)). The effect will be the same and the API you refer to will continue to work for at-least buckets in the default type (it may be extended as well depending on time, further discussion).

**Comment by jadeallenx** [comment]
We have hit one of the problems described with the current design which is: we have some data where "last write wins" is fine and other data where "allow_multi: true" is the right way to handle things. So I support this proposal because it sounds like we can easily share the riak infrastructure even though we might want mixed behaviors about concurrent writes within the same cluster.

**Comment by brunogirin** [comment]
@jrwest Thanks for the answer. If there is no technical blocker, that's brilliant and it makes complete sense to me that you would want to limit the scope of a first delivery.

From a point of view of what it would solve for me, it would make the multi backend concept more usable by being able to configure one backend for one bucket type and a different backend for another bucket type. I also like @mrallen1 's use case.

**Comment by lafka** [comment]
I'v been doing some minor testing and have some questions:
- Currently there is no way to delete a bucket type, is the only way around this to  delete the datadir?
- Calling `riak_core_bucket_type:reset/1` will only set the default values for some keys, for instance `yz_index` is not altered. Should reset be equivalent of calling 
- When using `riak-admin`, should some bucket properties be read only? (like `active` should not be changeable through `bucket-type update`). It's already there for `datatype`.
- Is there a way to store custom custom attributes in the bucket properties? i.e. I would like to store information about the structure of the keys in this bucket.

**Comment by jrwest** [comment]
Awesome to see you taking things for a spin! My comments are below.

> I'v been doing some minor testing and have some questions:
> - Currently there is no way to delete a bucket type, is the only way
>   around this to delete the datadir?
>   
>   There is not currently a way to delete a bucket type similar to buckets in
>   Riak. This is not something we plan to address for Riak 2.0 (but we may in
>   the future).
> - Calling riak_core_bucket_type:reset/1 will only set the default
>   values for some keys, for instance yz_index is not altered. Should
>   reset be equivalent of calling

As mentioned elsewhere, `reset` is not ready for use and the example you
found is one reason why. This will be addressed or reset will be removed
before Riak 2.0.

>    -
> - When using riak-admin, should some bucket properties be read only?
>   (like active should not be changeable through bucket-type update).
>   It's already there for datatype.

Good catch. We are aware not all validation is completely implemented,
however there was no issue tracking these specific cases so I opened one:
https://github.com/basho/riak_core/issues/442

>    -
> - Is there a way to store custom custom attributes in the bucket
>   properties? i.e. I would like to store information about the structure of
>   the keys in this bucket.

You should be able to store your own properties. The validation does not
take into account custom properties and should not reject them. However,
you may have problems using the same property names Riak uses (e.g.
datatype or n_val).

**Comment by lafka** [comment]
@jrwest the custom attribute is limited by `list_to_existing_atom/1` in `riak_kv_wm_utils:erlify_bucket_prop`. The same conversion is used in HTTP API, so might not be feasible to use `list_to_atom/1`.

**Comment by jrwest** [comment]
@lafka ah right. There is nothing stopping you from using internal APIs but the command-line parsing code will prevent it. Although we may not stay w/ JSON [1]  for the `riak-admin bucket-type` commands I'm not sure if this restriction will be lifted. I haven't run into this issue myself as a user of Riak but I imagine there are existing workarounds (loading a module w/ your atoms?) since buckets have had the same restriction when setting them via the API.

[1] https://github.com/basho/riak/issues/424
