### ISSUE TITLE
apt-get install instructions fail for ubuntu 12.04

### ISSUE THREAD

**Issue by jasonfisher** [basho/riak#367]
Simply following the instructions to use apt-get to install riak on Ubuntu 12.04 (32 bit) as found on http://docs.basho.com/riak/latest/ops/building/installing/debian-ubuntu/, I end up with a failure at the very last step:
➜  ~  sudo apt-get install riak
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package riak

After googling around it seems I am not the only one to have this issue, but nobody has solved it.  I followed all the previous steps successfully but failed here.  

"sudo apt-key list" does result with the final entry as basho, so that part seems to have worked:
pub   2048R/DDF2E833 2012-09-10 [expires: 2017-09-09]
uid                  Basho Technologies (Debian / Ubuntu signing key) packager@basho.com

However, the package is apparently not there:
➜  ~  apt-cache showpkg riak  
N: Unable to locate package riak

My sysadmin skills are weak, and I don't have a deep understanding of apt-get, but I figured following the simple instructions would get me where I wanted to go.  I tried a few fixes suggested on a couple of developer forums but those failed me.  While reading those, I found that many others had this issue, and that trying to build from source gave them equal or even greater problems.  

So, before I try another route, I am hoping perhaps somebody can give me insight as to what steps I might take to install Riak on ubuntu 12.04.

Thanks

**Comment by jaredmorrow** [comment]
There is no Riak package built for Ubuntu 32bit, that is why you are getting the errors about not finding Riak.  We only support 64bit platforms.
