### ISSUE TITLE
Getting Unsupported Media Type on /mapred

### ISSUE THREAD

**Issue by phillipfurtado** [basho/riak#370]
Hi, I'm doing direct requests to /mapred with -H 'Content-Type: octet-stream' I'm getting Unsupported Media Type. Do you know any other way to retrieve all binary objects from a Riak bucket?

This is my request:

curl -v -d '{"inputs":[["test", "key"]],"query":[{"map":{"language":"javascript", "source":"function(value,keyData, arg) { var dats = Riak.mapValues(value)[0]; return [typeof dats];}"}}]}' -H "Content-Type: application/octet-stream" http://localhost:8098/mapred

**Comment by ramunasd** [comment]
Riak does not supports binary data in javascript map reduce functions.
You can stream/get all bucket keys using special functions. I.e. python api - http://basho.github.io/riak-python-client/bucket.html#listing-keys
