### ISSUE TITLE
Add Default Bucket Properties to the Riak Configuration Schema

### ISSUE THREAD

**Issue by joedevivo** [basho/riak#373]
Currently, the defaults are set here:
https://github.com/basho/riak_kv/blob/develop/src/riak_kv_app.erl#L80-93

We'll need to decide which values to expose in the schema, and document them.

**Comment by joedevivo** [comment]
The following is from the 1.4.2.documentation

**default_bucket_props** These are properties used for buckets that have not been explicitly defined (as outlined in the HTTP API). They are useful for setting default bucket behavior such as:

``` erlang
{default_bucket_props, [
    {n_val,3},
    {allow_mult,false},
    {last_write_wins,false},
    {precommit, []},
    {postcommit, []},
    {chash_keyfun, {riak_core_util, chash_std_keyfun}},
    {linkfun, {modfun, riak_kv_wm_link_walker, mapreduce_linkfun}}
    ]}
```
- **n_val** - the number of replicas stored. Note: See CAP Controls for further discussion.
- Read, Write and Delete quorum values. Valid options include numeric values (e.g. {r, 2}), and the following symbolic values:  **quorum** (a majority of the replicas must respond, equivalent to n_val / 2 + 1)
  **all** (all N replicas must respond)
  - **r** - Read quorum value (the number of Riak nodes which must return results for a GET request before it is considered successful). Default: quorum.
  - **pr** - Primary read quorum (the number of primary, non-fallback nodes that must return results for a successful GET request). Default: 0. Note: See Eventual Consistency for an explanation of primary nodes.
  - **w** - Write quorum value (the number of Riak nodes which must accept a PUT request). Default: quorum.
  - **dw** - Durable write quorum (the number of Riak nodes which have received an acknowledgment of the write from the storage backend). Default: quorum.
  - **pw** - Primary write quorum (the number of primary, non-fallback nodes that must accept a PUT request). Default: 0.
  - **rw** - Delete quorum. Default: quorum.
- **allow_mult** - whether or not siblings are allowed. Note: See Vector Clocks for a discussion of sibling resolution.
- **precommit** - global pre-commit hook functions, either in Javascript or Erlang.
- **postcommit** - global post-commit hook functions. Erlang only.

**Comment by joedevivo** [comment]
Track work here: https://github.com/basho/riak_kv/pull/695

**Comment by jaredmorrow** [comment]
This looks to be fixed / closed in riak_kv.  Closing unless @joedevivo disagrees.

**Comment by joedevivo** [comment]
+1 to closing
