### ISSUE TITLE
"sh: 1: exec: sysctl: not found"

### ISSUE THREAD

**Issue by westhand** [basho/riak#376]
Hi,

I raised this issue on the mailing list, but was asked to post it here as well.

"riak-admin diag" returns:

```
RPC to 'riak@riak1.westhand.de' failed: {'EXIT',
                                         {badarg,
                                          [{erlang,list_to_integer,
                                            ["sh: 1: exec: sysctl: not found"],
                                            []},
                                           {riaknostic_check_sysctl,
                                            check_params,2,
                                            [{file,
                                              "src/riaknostic_check_sysctl.erl"},
                                             {line,80}]},
                                           {riaknostic_check,check,1,
                                            [{file,"src/riaknostic_check.erl"},
                                             {line,74}]},
                                           {riaknostic,'-run/1-fun-1-',2,
                                            [{file,"src/riaknostic.erl"},
                                             {line,106}]},
                                           {lists,foldl,3,
                                            [{file,"lists.erl"},{line,1197}]},
                                           {riaknostic,run,1,
                                            [{file,"src/riaknostic.erl"},
                                             {line,105}]},
                                           {rpc,'-handle_call_call/6-fun-0-',
                                            5,
                                            [{file,"rpc.erl"},{line,203}]}]}}
```

I can easily explain why:
Riak runs under a UID > 0. Now consider /etc/profile:

```
if [ "`id -u`" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH
```

So the "else"-branch is chosen, but sysctl resides in /sbin.

System infomation:
Debian 7, using
- Erlang from the distribution (version 15.b.1-dfsg-4)
- Riak Debs for Debian 6, as well as libssl0.9.8 from Debian 6

I have no idea how other distributions treat nonroot system users, so maybe this is more of a Debian than a Riak issue., but here it is anyway.

**Comment by bsparrow435** [comment]
Hi @westhand this is a known [issue](basho/riaknostic#62). It has been resolved by removing `sysctl` checks from Riaknostic but can be resolved in your environment by adding `/sbin` to PATH.

**Comment by westhand** [comment]
I forgot:
I have several ideas for a workaround, but which one is recommended?
Symlinking sysctl to a path?
Editing /etc/profile?
Adding a home directory to the riak user and fix $PATH in .bashrc?
Aliasing?
Running as root? _cough_

**Comment by westhand** [comment]
Hi Brian

sorry, you posted while I was writing my Annex.
Thanks for the answer.

**Comment by bsparrow435** [comment]
The easiest change would probably be `sudo ln -s /sbin/sysctl /bin/`. Anytime!
