### ISSUE TITLE
Cluster integrity as a function of physical nodes number, bucket n_val and ring size

### ISSUE THREAD

**Issue by georgepsarakis** [basho/riak#381]
The number of physical servers your data gets written on is not clearly stated. 
This can lead to unexpected behaviour. 

Example:
- Ring size (Partitions) = 64
- physical nodes N = 5
- n_val = 3

In this case all data are kept in 3 partitions and each partition resides on a different physical server. You can lose any 2 servers and still have all your data. 
Now, if we add 2 more physical servers (N=7, n_val=3) you _cannot_ lose **any** 2 servers and still have all your data.
This is because we now have **2 sequential partitions served by the same physical server** (first and last partition in the ring).

**General rule**: your data is stored in n_val different servers unless `Partitions % N == 1`. In this case some data are only stored in `n_val - 1` physical servers.

**Edit**: There are actually more cases where this may happen. For example, for N = 5 server and Ring Size = 32 and n_val = 3, at the end of the ring the same physical node pair occurs twice, which means that data will be written on 2 physical nodes and not 3. So perhaps the documentation could be clearer on this matter and state the relation and importance of the ring size in respect to the number of physical nodes that can be lost from the cluster.

**Comment by jaredmorrow** [comment]
Closing in favor of basho/basho_docs#946
