### ISSUE TITLE
Build fails on mac os x 10.8.4 missing CodeFragments.h

### ISSUE THREAD

**Issue by thehappycoder** [basho/riak#384]
Installed erlang R15B01 from source, tried to build riak-1.4.2 with gcc and clang but got stuck with same error about missing CodeFragments.h:
gcc -o prlink.o -c     -m32  -Wall -fno-common -pthread -O2 -fPIC  -UDEBUG  -DNDEBUG=1 -DXP_UNIX=1 -DDARWIN=1 -DHAVE_BSD_FLOCK=1 -DHAVE_SOCKLEN_T=1 -DXP_MACOSX=1 -DHAVE_LCHOWN=1 -DHAVE_STRERROR=1  -DFORCE_PR_LOG -D_PR_PTHREADS -UHAVE_CVAR_BUILT_ON_SEM -D_NSPR_BUILD_ -I../../../dist/include/nspr -I../../../pr/include -I../../../pr/include/private -I/Developer/Headers/FlatCarbon  prlink.c
prlink.c:48:27: error: CodeFragments.h: No such file or directory
prlink.c:49:23: error: TextUtils.h: No such file or directory
prlink.c:50:19: error: Types.h: No such file or directory
prlink.c:51:21: error: Aliases.h: No such file or directory
prlink.c:52:19: error: CFURL.h: No such file or directory
prlink.c:53:22: error: CFBundle.h: No such file or directory
prlink.c:54:22: error: CFString.h: No such file or directory
prlink.c:55:26: error: CFDictionary.h: No such file or directory
prlink.c:56:20: error: CFData.h: No such file or directory
prlink.c:119: error: expected specifier-qualifier-list before ‘CFragConnectionID’
prlink.c: In function ‘_PR_InitLinker’:
prlink.c:237: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c: In function ‘pr_LoadCFBundle’:
prlink.c:625: error: ‘CFURLRef’ undeclared (first use in this function)
prlink.c:625: error: (Each undeclared identifier is reported only once
prlink.c:625: error: for each function it appears in.)
prlink.c:625: error: expected ‘;’ before ‘bundleURL’
prlink.c:626: error: ‘CFBundleRef’ undeclared (first use in this function)
prlink.c:626: error: expected ‘;’ before ‘bundle’
prlink.c:627: error: ‘PATH_MAX’ undeclared (first use in this function)
prlink.c:629: error: ‘CFStringRef’ undeclared (first use in this function)
prlink.c:629: error: expected ‘;’ before ‘pathRef’
prlink.c:636: error: ‘pathRef’ undeclared (first use in this function)
prlink.c:636: warning: implicit declaration of function ‘CFStringCreateWithCString’
prlink.c:636: error: ‘kCFStringEncodingUTF8’ undeclared (first use in this function)
prlink.c:638: error: ‘bundleURL’ undeclared (first use in this function)
prlink.c:638: warning: implicit declaration of function ‘CFURLCreateWithFileSystemPath’
prlink.c:639: error: ‘kCFURLPOSIXPathStyle’ undeclared (first use in this function)
prlink.c:641: error: ‘bundle’ undeclared (first use in this function)
prlink.c:641: warning: implicit declaration of function ‘CFBundleCreate’
prlink.c:642: warning: implicit declaration of function ‘CFRelease’
prlink.c:647: error: ‘PRLibrary’ has no member named ‘bundle’
prlink.c:627: warning: unused variable ‘pathBuf’
prlink.c: In function ‘pr_LoadViaDyld’:
prlink.c:654: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:655: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:656: error: ‘PRLibrary’ has no member named ‘image’
prlink.c:658: error: ‘PRLibrary’ has no member named ‘image’
prlink.c:669: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:669: error: ‘PRLibrary’ has no member named ‘image’
prlink.c: In function ‘pr_LoadLibraryByPathname’:
prlink.c:792: error: ‘cfragNoLibraryErr’ undeclared (first use in this function)
prlink.c: In function ‘PR_UnloadLibrary’:
prlink.c:1024: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:1025: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:1040: error: ‘PRLibrary’ has no member named ‘connection’
prlink.c:1041: warning: implicit declaration of function ‘CloseConnection’
prlink.c:1041: error: ‘PRLibrary’ has no member named ‘connection’
prlink.c:1042: error: ‘PRLibrary’ has no member named ‘bundle’
prlink.c:1043: error: ‘PRLibrary’ has no member named ‘bundle’
prlink.c:1044: error: ‘PRLibrary’ has no member named ‘wrappers’
prlink.c:1045: error: ‘PRLibrary’ has no member named ‘wrappers’
prlink.c: In function ‘pr_FindSymbolInLib’:
prlink.c:1140: error: ‘PRLibrary’ has no member named ‘bundle’
prlink.c:1141: error: ‘CFStringRef’ undeclared (first use in this function)
prlink.c:1141: error: expected ‘;’ before ‘nameRef’
prlink.c:1142: error: ‘nameRef’ undeclared (first use in this function)
prlink.c:1143: warning: implicit declaration of function ‘CFBundleGetFunctionPointerForName’
prlink.c:1143: error: ‘PRLibrary’ has no member named ‘bundle’
prlink.c:1143: warning: assignment makes pointer from integer without a cast
prlink.c:1147: error: ‘PRLibrary’ has no member named ‘connection’
prlink.c:1148: error: ‘Ptr’ undeclared (first use in this function)
prlink.c:1148: error: expected ‘;’ before ‘symAddr’
prlink.c:1149: error: ‘CFragSymbolClass’ undeclared (first use in this function)
prlink.c:1149: error: expected ‘;’ before ‘symClass’
prlink.c:1150: error: ‘Str255’ undeclared (first use in this function)
prlink.c:1150: error: expected ‘;’ before ‘pName’
prlink.c:1154: warning: implicit declaration of function ‘c2pstrcpy’
prlink.c:1154: error: ‘pName’ undeclared (first use in this function)
prlink.c:1156: warning: implicit declaration of function ‘FindSymbol’
prlink.c:1156: error: ‘PRLibrary’ has no member named ‘connection’
prlink.c:1156: error: ‘symAddr’ undeclared (first use in this function)
prlink.c:1156: error: ‘symClass’ undeclared (first use in this function)
prlink.c:1156: error: ‘noErr’ undeclared (first use in this function)
prlink.c:1165: error: ‘PRLibrary’ has no member named ‘main’
prlink.c:1167: error: ‘PRLibrary’ has no member named ‘image’
prlink.c:1169: error: ‘PRLibrary’ has no member named ‘image’
prlink.c:1195: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:1197: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c: In function ‘PR_LoadStaticLibrary’:
prlink.c:1349: error: ‘PRLibrary’ has no member named ‘dlh’
prlink.c:1349: error: ‘PRLibrary’ has no member named ‘dlh’
make[6]: **\* [prlink.o] Error 1
make[6]: Leaving directory `/Users/anton/riak/riak-1.4.2/deps/erlang_js/c_src/nsprpub/pr/src/linking'
make[5]: *** [export] Error 2
make[5]: Leaving directory`/Users/anton/riak/riak-1.4.2/deps/erlang_js/c_src/nsprpub/pr/src'
make[4]: **\* [export] Error 2
make[4]: Leaving directory `/Users/anton/riak/riak-1.4.2/deps/erlang_js/c_src/nsprpub/pr'
make[3]: *** [export] Error 2
make[3]: Leaving directory`/Users/anton/riak/riak-1.4.2/deps/erlang_js/c_src/nsprpub'
make[2]: **\* [/Users/anton/riak/riak-1.4.2/deps/erlang_js/c_src/system/lib/libnspr4.a] Error 2
make[2]: Leaving directory `/Users/anton/riak/riak-1.4.2/deps/erlang_js/c_src'
make[1]: *** [c_src] Error 2
make[1]: Leaving directory`/Users/anton/riak/riak-1.4.2/deps/erlang_js'
ERROR: Command [compile] failed!
make: **\* [compile] Error 1

However, there is CodeFragments.h file in the system.

**Comment by vinoski** [comment]
This is caused by trying to build Riak with a 32-bit Erlang rather than a 64-bit Erlang. Try rebuilding with a 64-bit Erlang and you'll be successful.

**Comment by cmeiklejohn** [comment]
See basho/erlang_js#40.  We might need to make an additional change for Mavericks.

**Comment by vinoski** [comment]
I've built and run Riak on Mavericks and only eleveldb changes are needed. See [eleveldb/pull/76](https://github.com/basho/eleveldb/pull/76) and [leveldb/pull/104](https://github.com/basho/leveldb/pull/104).
