### ISSUE TITLE
Bundled SSL certificate problems.

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak#399]
See basho/riak_control#162.

Our development certificates are generated with an invalid CA certificate, which is not bundled in the repo along with the certificate and keyfile.  When enabling SSL and using Riak Control with the bundled certificates, this generates an "accept failed" and causes the browser to throw up a warning page because the CA certificate is not present.

On the latest version of Riak, with R16B02, we are no longer seeing the "accept failed" from mochiweb in the log, but getting a failure somewhere which is causing an invalid certificate to be returned to the user.  

Is there any reason we even have to be keeping SSL certificates in the repository?  We don't want anyone using the provided ones anyway (especially considering they are signed to Jeff Massung) and have been signed with an invalid CA.

@jaredmorrow @Vagabond @jonmeredith @seancribbs @jgnewman

**Comment by Vagabond** [comment]
I argued against bundling these SSL certs in the first place, so I'd be happy to see them go.

**Comment by jaredmorrow** [comment]
+1 for them to be gone.  The original request from Jeff was to make proper docs or a platform-independent script to generate the certificates easily so users won't have any barrier to testing.

**Comment by Vagabond** [comment]
On Wed, Oct 02, 2013 at 10:27:44AM -0700, Jared Morrow wrote:

> +1 for them to be gone.  The original request from Jeff was to make proper docs or a platform-independent script to generate the certificates easily so users won't have any barrier to testing.

I was actually playing with the one bundled with OTP, that OTP uses for
testing SSL to use in riak_test for testing revoked certificates. If
that works out maybe we can adapt it.

Andrew

**Comment by cmeiklejohn** [comment]
Cool; I'm going to open a PR to have them removed.

**Comment by jaredmorrow** [comment]
Associated PR here https://github.com/basho/riak/pull/401
