### ISSUE TITLE
Fold Hangs Vnodes in Mixed 1.X - 2.0.0pre3 Clusters

### ISSUE THREAD

**Issue by beerriot** [basho/riak#407]
# Summary

In a mixed 1.X - 2.0.0pre3 cluster, if a vnode running on a 2.0.0 node receives a v1 fold_req command, that vnode will stick in a loop trying to upgrade the command record.
# Reproduction
1. Setup a two-node cluster, one node on the latest from the develop branch (what I'm calling 2.0.0pre3 here), and one node on 1.4.2
2. Stop the 1.4.2 cluster
3. Load some data into the 2.0.0pre3 cluster (enough that you're spinning up at least one fallback vnode - ex. `for x in {1..1000}; do curl -X PUT -H "content-type: text/plain" http://localhost:10028/buckets/bryan/keys/$x --data $x; done`).
4. Restart the 1.4.2 node
5. Wait until you see messages about starting handoff on some vnodes
6. On the 1.4.2 side you'll eventually see messages that the handoff timed out after processing 0 objects.

If you attach to the 2.0.0pre3 node, you'll see that `riak_core_handoff_manager:status()` shows that the handoffs reported in the logs are still "active".

If you dig through process info, you'll find one or more in the middle of `riak_core_util:make_fold_req/4` (use `[ P || P <- processes(), {riak_core_util, make_fold_req, 4} == proplists:get_value(current_function, process_info(P)) ].` or similar)

Asking for the vnode's status via `riak_kv_vnode:vnode_status([{Index, Pid}])` hangs, because the vnode is directly calling its own `handle_command` function, not sending itself a new message.
# Cause

As hinted above, the cause is an interplay between `riak_core_util:make_req/4` and `riak_kv_vnode:handle_command`.

The `riak_core_util:make_fold_req/4` function uses capabilities to determine whether to create a `riak_core_fold_req_v1` or `…_v2` record. With a 1.X node in the mix, it always chooses v1. When the `riak_kv_vnode:handle_command/3` function of a 2.0.0pre3 node receives a `…_v1` record, it attempts to use `make_fold_req/4` to upgrade it, and then calls `handle_command/3` recursively with the result. Unfortunately, the result is still a `…_v1` record, so it ends up in a tight loop doing nothing.

The vnode will only become unstuck once all nodes are upgraded to 2.0.0pre3, and the fold capability is renegotiated to v2.
# Notes

The fix might be as simple as exposing a `riak_core_util:upgrade_fold_req` that always upgrades to the latest version, or teaching `riak_kv_vnode:handle_command` to pull apart a v1 record directly. Since fold reqs are a little hairy, and the problem reveals itself as a stuck vnode instead of an error, it seemed like a good idea to spread knowledge wider before spending time on the fix, though.

KV-specific concerns:
- seems like it might effect both handoff and aae rebuild
- behavior is an unresponsive spinning vnode

Search-specific concerns:
- code is copy-paste from riak_kv
- behavior is an unresponsive spinning vnode

Pipe-specific concerns:
- pipe only handles v2 (due to macro recompilation), ignoring v1
- behavior is ignored fold command, with a log about an "Unhandled command"

~~I'm working on an automated test, but it won't be finished in time for this weekend's runs.~~

Automated test is now available at https://github.com/basho/riak_test/pull/400

**Comment by slfritchie** [comment]
This all worked nicely before I added the riak_core_capability negotiation in a later PR.  :-(

I've reopened these PRs and added bugfix commits:
- https://github.com/basho/riak_core/pull/354
- https://github.com/basho/riak_kv/pull/626

**Comment by jaredmorrow** [comment]
This appears fixed in the above referenced PR's.  Correct me if I'm wrong @slfritchie

**Comment by slfritchie** [comment]
Correct
