### ISSUE TITLE
EC ciphers causing Riak Control failure

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak#408]
EC ciphers need to be disabled for the SSL interface for Riak, or Riak Control will fail to operate on SSL using self-signed certificates.

**Comment by cmeiklejohn** [comment]
Tagging @Vagabond.

**Comment by Vagabond** [comment]
Description of bug and patch for OTP available here:

http://erlang.org/pipermail/erlang-bugs/2013-October/003782.html

**Comment by cmeiklejohn** [comment]
Tracking a OTP fix for this here: http://erlang.org/pipermail/erlang-bugs/2013-October/003782.html

Thanks @Vagabond

**Comment by jaredmorrow** [comment]
This is fixed in our shipped Erlang with Riak (R16b02-basho4) as well as Erlang 17 to be released soon.

**Comment by Vagabond** [comment]
It was fixed in R16B03 by OTP-11370.
