### ISSUE TITLE
riak-admin reip uses hardcoded app.config

### ISSUE THREAD

**Issue by jaredmorrow** [basho/riak#412]
https://github.com/basho/riak/blob/develop/rel/files/riak-admin#L526

WIth cuttlefish around, we need to change this to use the proper config.

**Comment by jaredmorrow** [comment]
Closing this, instead we should remove reip entirely since it is deprecated.

**Comment by jaredmorrow** [comment]
`reip` needs to stay, so this needs fixing.

**Comment by cmeiklejohn** [comment]
Yeah; I'm working on this right now.

**Comment by cmeiklejohn** [comment]
I believe this is resolved by #188, but would love confirmation.

**Comment by jaredmorrow** [comment]
It no longer references a hard coded path, closing.
