### ISSUE TITLE
riak-admin bucket-type create should support passing no props

### ISSUE THREAD

**Issue by jrwest** [basho/riak#423]
and use the default ones. That way, creating types w/ the default props doesn't require passing some empty json string (the json is a whole different issue)

e.g. `riak-admin bucket-type create mytype` fails instead of creating the type w/ default props.

**Comment by jaredmorrow** [comment]
@jrwest setting to 2.1 unless you tell me otherwise.

**Comment by jrwest** [comment]
moved to `2.0-RC`. I was hoping leaving it would anger people enough I'd get asked to remove the JSON, but it didn't work. The "no props" version should work at a minimum.
