### ISSUE TITLE
vm.args needs to have -name while start riak

### ISSUE THREAD

**Issue by wb14123** [basho/riak#436]
Erlang version: Erlang R16B02 (erts-5.10.3) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Riak version: riak-2.0.0pre5
OS: Archlinux 64bits

step:
1. make rel
2. ./rel/riak/bin/riak start

Nothing is started and errors are outputed:

```
vm.args needs to have a -name parameter.
  -sname is not supported.
```

**Comment by jaredmorrow** [comment]
@wb14123 can you run

```
./rel/riak/bin/riak chkconfig
```

And paste the ouptut here.  I'm curious what app.config / vm.args your build is picking up.  My guess is the config is not being generated correctly for something reason on your build.

I don't have an arch linux setup I can use, so I'll try to walk through this with you if you don't mind running some commands here and there.

**Comment by wb14123** [comment]
Thanks for the help.

I  rebuild it with `make clean; make rel` and no error is outputed.

When I run `./rel/riak/bin/riak chkconfig`, the output is the same:

```
vm.args needs to have a -name parameter.
  -sname is not supported.
```

Should I check some config files?

**Comment by joedevivo** [comment]
Yes @wb14123, please check your riak.conf for `nodename` and let me know what the line says

**Comment by wb14123** [comment]
I only find `riak.conf` in `deps/cuttlefish/test/riak.conf` and there is no `nodename`. The content of it:

```
ring_size = 32
anti_entropy = debug
log.error.file = /var/log/error.log
log.console.file = /var/log/console.log
log.syslog = on
listener.http.internal = 127.0.0.1:8098
listener.http.external = 10.0.0.1:80
```

And I found `nodename` in `rel/riak/etc/cuttlefish.conf`:

```
nodename = riak@127.0.0.1
```

The files in some of my directories which I think may include the config files are:

```
wangbin@bin-macair ~/open_source/riak (3bd9938) > ls rel
files  gen_dev  rebar.config  reltool.config  riak  vars  vars.config

wangbin@bin-macair ~/open_source/riak (3bd9938) > ls rel/vars
dev1_vars.config  dev2_vars.config  dev3_vars.config  dev4_vars.config  dev5_vars.config  dev_vars.config.src  perf_vars.config.src

wangbin@bin-macair ~/open_source/riak (3bd9938) > ls rel/riak/etc 
cuttlefish.conf  solr-log4j.properties
```

**Comment by joedevivo** [comment]
@wb14123 the problem is that your cuttlefish repo is too new for your riak repo.

If you have riak checked out from github, go head and pull develop. That'll get you the up to date version you need.

**Comment by wb14123** [comment]
What if I want to use a stable version? Should the deps in rebar.config specify the git tag?

**Comment by jaredmorrow** [comment]
The 'develop' branch is a work in progress and you shouldn't use it for production.  If you want a stable version, download the source package of 1.4.2 from the bottom of this page http://docs.basho.com/riak/latest/downloads/

Also, browse around the docs.basho.com site for some good walkthroughs and getting started pages.

Installing from source instructions can be found here http://docs.basho.com/riak/latest/ops/building/installing/from-source/

For 1.4.2 the currently support erlang is R15B01, when 2.0 comes out it will use R16B02.

**Comment by wb14123** [comment]
Because of my OS only has official Erlang package with version R16B02. I'd like to install riak 2.0. Waiting for the release...

**Comment by jaredmorrow** [comment]
Building erlang from source is quite easy and we also have documentation on
that page about how to do it if you would rather not wait.

We also have release candidates for 2.0 coming in December.
