### ISSUE TITLE
Segmentation fault on Ubuntu 12.04 after issuing riak restart

### ISSUE THREAD

**Issue by deanproctor** [basho/riak#437]
On Ubuntu 12.04, it is possible to reliably generate a segmentation fault with Riak 1.4.2 by issuing a `riak restart` command on a running node.  I have so far only been able to produce this behavior with the leveldb backend.  The restart behavior generates a segfault on both joined and unjoined nodes and with or without data.

Process transcript: https://gist.github.com/deanproctor/cc4c89217cfcd4991f6a

The segmentation fault is logged with one of the following messages:
beam.smp[27434]: segfault at 7f6b4b6e9f48 ip 00007f6b4b6e9f48 sp 00007f6ae77bde80 error 14 in libcrypto.so.1.0.0[7f6b4b71e000+1b1000]

beam.smp[28395]: segfault at 7f7f12407f48 ip 00007f7f12407f48 sp 00007f7eb1fbae80 error 14 in crypto.so[7f7f124db000+a000]

beam.smp[24680]: segfault at 7f5aeb7c2f48 ip 00007f5aeb7c2f48 sp 00007f5a82fc4e80 error 14 in libz.so.1.2.3.4[7f5aeb7e2000+16000]

System info:
Example server: r2s19
Riak version 1.4.2
Ubuntu 12.04
Kernel 3.2.0-55
libssl1.0.0 version 1.0.1-4ubuntu5.10

A core dump is available here: https://dl.dropboxusercontent.com/u/5425291/core-beam.smp-11-107-113-27958-1384439768

Riak config: https://gist.github.com/deanproctor/6b26d5232abfa38a8a92

**Comment by jaredmorrow** [comment]
Going to close this as no further investigation was done at the time.  We will reinvestigate if we see this in 2.0.
