### ISSUE TITLE
Really increase the default zdbbl buffer size.

### ISSUE THREAD

**Issue by nathanaschbacher** [basho/riak#445]
We're seeing clusters tip over for customers and prospects alike, making Riak look very bad and contradicting our operational ease and stability story.

Often the cause of these issues boils down to a flood of busy_dist_port errors in their installations and deployments.

Further confusing is that we put a better value there, but comment it out.  A common convention is to show defaults and comment it out, but that's not the default.  To actually get that value you have to uncomment it.

https://github.com/basho/riak/blob/1.4/rel/files/vm.args#L40

Since the above text says that we at Basho recommend this change anyway, can we just uncomment that line and make the actual default be the default we recommend?  Are there any scenarios where Riak should be deployed or even considered well tested with a zdbbl value of 1024?

**Comment by slfritchie** [comment]
Notes:
1. See also: Basho internal dev discussion
2. This issue also affect's the riak_ee repo's packaging.

**Comment by jaredmorrow** [comment]
This is fixed in cuttlefish https://github.com/basho/cuttlefish/blob/develop/priv/erlang_vm.schema#L178

**Comment by joedevivo** [comment]
If this change to the default configuration is made, it should be done as an override in riak.schema, not in the erlang_vm.schema. have a nice day.

**Comment by rzezeski** [comment]
Okay so this issue should be reopened then if the default is still 1024.

**Comment by jaredmorrow** [comment]
But why then is in commented at 32mb?  That is so confusing, if I see a comment that says 32mb, I'm going to assume that's the default unless I uncomment and change it.

**Comment by jrwest** [comment]
another vote for raising it? https://github.com/basho/riak/issues/508

**Comment by jaredmorrow** [comment]
Okay, going to do just make a branch and get this done, PR... incoming..

**Comment by evanmcc** [comment]
the strongest possible :+1: from me, this absolutely needs to be done.

**Comment by jaredmorrow** [comment]
@evanmcc 32mb reasonable to you, that was our previous suggestion?

**Comment by evanmcc** [comment]
32MB sounds good to me.

**Comment by jaredmorrow** [comment]
I have a branch with the fix, but there is currently a bug in cuttlefish.  Leaving this as a placeholder so no one else starts it.
