### ISSUE TITLE
Unable to install Riak from source

### ISSUE THREAD

**Issue by crshovrd** [basho/riak#449]
I can't install Riak from source. I get the following error:

`protobuffs (compile) ERROR: compile failed while processing riak-1.4.2/deps/protobuffs: rebar_abort`

Ubuntu
Release 12.04 (precise) 64-bit
Kernel Linux 3.5.0-44-generic
GNOME 3.4.2

$ erl
Erlang R14B04 (erts-5.8.5) [source] [64-bit] [smp:8:8] [rq:8] [async-threads:0] [kernel-poll:false]

Eshell V5.8.5  (abort with ^G)
1> 

$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

$ ls
riak-1.4.2  riak-1.4.2.tar.gz
$ cd riak-1.4.2/
$ make rel
fatal: Not a git repository (or any of the parent directories): .git
./rebar get-deps
==> node_package (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> syslog (get-deps)
==> lager_syslog (get-deps)
==> cluster_info (get-deps)
==> poolboy (get-deps)
==> meck (get-deps)
==> protobuffs (get-deps)
==> basho_stats (get-deps)
==> riak_sysmon (get-deps)
==> mochiweb (get-deps)
==> ibrowse (get-deps)
==> webmachine (get-deps)
==> bear (get-deps)
==> folsom (get-deps)
==> ranch (get-deps)
==> riak_core (get-deps)
==> sidejob (get-deps)
==> erlang_js (get-deps)
==> bitcask (get-deps)
==> ebloom (get-deps)
==> getopt (get-deps)
==> eper (get-deps)
==> eleveldb (get-deps)
==> edown (get-deps)
==> sext (get-deps)
==> riak_pipe (get-deps)
==> riak_pb (get-deps)
==> riak_api (get-deps)
==> riak_kv (get-deps)
==> merge_index (get-deps)
==> lucene_parser (get-deps)
==> riak_search (get-deps)
==> erlydtl (get-deps)
==> riak_control (get-deps)
==> riaknostic (get-deps)
==> rel (get-deps)
==> riak-1.4.2 (get-deps)
./rebar compile
==> node_package (compile)
==> goldrush (compile)
Compiled src/glc.erl
Compiled src/glc_ops.erl
Compiled src/glc_lib.erl
Compiled src/gr_context.erl
Compiled src/gre.erl
Compiled src/glc_code.erl
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_transform.erl
Compiled src/lager_handler_watcher_sup.erl
Compiled src/lager_config.erl
Compiled src/lager_app.erl
Compiled src/lager_default_formatter.erl
Compiled src/lager_sup.erl
Compiled src/lager_trunc_io.erl
Compiled src/lager_file_backend.erl
Compiled src/error_logger_lager_h.erl
Compiled src/lager.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager_console_backend.erl
Compiled src/lager_msg.erl
Compiled src/lager_stdlib.erl
Compiled src/lager_backend_throttle.erl
Compiled src/lager_crash_log.erl
Compiled src/lager_format.erl
==> syslog (compile)
Compiled src/syslog_app.erl
Compiled src/syslog_sup.erl
Compiled src/syslog.erl
Compiling c_src/syslog_drv.c
c_src/syslog_drv.c: In function ‘encode_error’:
c_src/syslog_drv.c:60:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c: In function ‘syslogdrv_control’:
c_src/syslog_drv.c:109:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:116:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:119:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:136:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:142:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:147:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:152:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:162:20: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:172:13: warning: passing argument 1 of ‘driver_create_port’ makes integer from pointer without a cast [enabled by default]
/usr/lib/erlang/erts-5.8.5/include/erl_driver.h:566:13: note: expected ‘long int’ but argument is of type ‘ErlDrvPort’
c_src/syslog_drv.c:172:22: warning: assignment makes pointer from integer without a cast [enabled by default]
c_src/syslog_drv.c:177:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:192:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c: In function ‘syslogdrv_call’:
c_src/syslog_drv.c:204:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
c_src/syslog_drv.c:214:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
==> lager_syslog (compile)
Compiled src/lager_syslog_backend.erl
==> cluster_info (compile)
Compiled src/cluster_info_ex.erl
Compiled src/cluster_info_basic.erl
Compiled src/cluster_info.erl
==> poolboy (compile)
Compiled src/poolboy_worker.erl
Compiled src/poolboy_sup.erl
Compiled src/poolboy.erl
==> meck (compile)
Compiled src/meck_args_matcher.erl
Compiled src/meck_history.erl
Compiled src/meck_ret_spec.erl
Compiled src/meck_expect.erl
Compiled src/meck_matcher.erl
Compiled src/meck.erl
Compiled src/meck_cover.erl
Compiled src/meck_util.erl
Compiled src/meck_code_gen.erl
Compiled src/meck_code.erl
Compiled src/meck_proc.erl
==> protobuffs (compile)
ERROR: compile failed while processing /home/yader/tmp/riak-1.4.2/deps/protobuffs: rebar_abort
make: **\* [compile] Error 1

I also installed erlang-dev which fixed other compile errors but I can't figure this one out.

I'm trying to change where Riak is installed by modifying the vars.config file found under the `rel` folder. Is this correct? Is there a way I can see the spec files for riak-1.4.2-1.el6.src.rpm? Is there an easier way of changing the installation / running / logs / bin / etc directories? Normally I would do something like

`./configure --path=/path/to/install/app && make`

**Comment by crshovrd** [comment]
I found a spec file example:

https://gist.github.com/hiroakis/5272527

**Comment by jaredmorrow** [comment]
Modifying the spec is somewhat difficult, but can be done.  The spec is generated from a template and can actually be found here [in node_package](https://github.com/basho/node_package/blob/develop/priv/templates/rpm/specfile).

I'm more concerned that you cannot build from source from our source tarball. 

I just tried to do it fresh

```
$ tar -zxf riak-1.4.2.tar.gz
$ cd riak-1.4.2
$ make rel
.... <snip> ...
Compiled src/riaknostic_check_dumps.erl
Compiled src/riaknostic_check_ring_membership.erl
Compiled src/riaknostic_check_disk.erl
Compiled src/riaknostic.erl
==> rel (compile)
==> riak-1.4.2 (compile)
Compiled src/etop_txt.erl
./rebar generate
==> rel (generate)
$ echo $?
0
```

I think a problem might be in you using the erlang that ships with your OS.  Typically they are configured badly and do not have everything you need.  We highly recommend building erlang from source.   You can find instructions [on our docs page about installing erlang](http://docs.basho.com/riak/latest/ops/building/installing/erlang/)  We ship Riak 1.4.2 with erlang 15B01, so we recommend using that when building from source.

**Comment by crshovrd** [comment]
Looks like compiling erlang from source fixes those issues. Thank you.
