### ISSUE TITLE
Print out ignored app.config options to console.log on startup

### ISSUE THREAD

**Issue by dgrnbrg** [basho/riak#458]
Today I discovered that riak 1.3 doesn't understand `object_format`. It'd be nice if the console.log would let me know when I'm using config options that it doesn't understand--this would help with backported configurations and typos.

**Comment by jaredmorrow** [comment]
Cuttlefish (the new configuration system introduced in 2.0) fixes this issue.  Sorry for the troubles in 1.3.

**Comment by dgrnbrg** [comment]
I don't think cuttlefish fixes this, unless there's a tool to automatically
convert a legacy config to the cuttlefish config. We have a pretty large
and complex config, and porting it isn't cost-effective, but this type of
validation is really valuable to guard against typos.
