### ISSUE TITLE
not mounted with noatime

### ISSUE THREAD

**Issue by conradwt** [basho/riak#461]
Hi, I'm getting the following notice within when I execute 'riak-admin diag' on Mac OS 10.9 with Riak 1.4.6:

```
notice] Data directory /Applications/riak-1.4.6/bin/../data/leveldb is not mounted with 'noatime'. Please remount its disk with the 'noatime' flag to improve performance.
```

If I'm using Riak within the development context, does this setting need to be enabled?  If so, how does such a setting effect my overall development environment?  I ask this question because the docs says the following:

```
eLevelDB is very aggressive at reading and writing files. As such, you can get a big speed boost by adding the noatime mounting option to /etc/fstab. This will disable the recording of the “last accessed time” for all files. If you need last access times but you'd like some of the benefits of this optimization you can try realtime.
```

**Comment by bsparrow435** [comment]
@conradwt This setting will provide a performance boost regardless of backend as Riak does a lot of reading/writing of files on disk and `noatime` makes these operations more efficient.

The warning is coming from the `riaknostic` package which periodically warns against common configuration settings that can effect performance and data integrity. I highly recommend using this setting if you are doing any sort of performance or load testing. If you are simply developing against riak and don't currently care about performance, then it does not matter.
