### ISSUE TITLE
Riak 2.0 download link is broken

### ISSUE THREAD

**Issue by conradwt** [basho/riak#474]
Hi, I'm not sure if this is the right place but it appears that the following link is broken:

```
http://docs.basho.com/riak/2.0.0pre8/downloads/
```

**Comment by jaredmorrow** [comment]
Pre8 was not packaged and released into the wild.  I don't know why the URL
is pointing you there in error.  If you try the same URL but with "pre5"
you should be all set.  I'll forward this along to the docs team.
