### ISSUE TITLE
Warning on php 5.5.x

### ISSUE THREAD

**Issue by allinora** [basho/riak#478]
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /library/3rdparty/riak-php-client/src/Basho/Riak/Utils.php on line 239

Thanks for looking into it.

**Comment by reiddraper** [comment]
Please file this issue against [basho/riak-php-client](https://github.com/basho/riak-php-client). Thanks.

**Comment by allinora** [comment]
oops. sorry about that.
