### ISSUE TITLE
Add cuttlefish schema for kernel inet_dist_listen_min/max settings

### ISSUE THREAD

**Issue by jtuple** [basho/riak#479]
Erlang by default binds to wildcard port for distributed Erlang. Which is a PITA for those with firewalls and whitelist ports. Thus, our docs on firewalls suggest folks bind Erlang to a narrow range of their choice (we suggest 6000 to 7999):
http://docs.basho.com/riak/2.0.0pre11/ops/advanced/security

Ran into a user today trying out 2.0 and converting their `app.config` over to `riak.conf`, and since there wasn't a setting for these parameters he decided to not port them over. Which resulted in wildcard ports, and firewall woes.

We should add schema rules for this setting with commented out defaults and update the docs to use the new `riak.conf` syntax.

**Comment by joedevivo** [comment]
We do have these, they're in erlang_vm.schema

**Comment by joedevivo** [comment]
https://github.com/basho/cuttlefish/blob/develop/priv/erlang_vm.schema#L229-L240

**Comment by seancribbs** [comment]
This seems evidence that we also need to document and proclaim the purpose of `advanced.config` very loudly. This would not be an issue if they just copied them into `advanced.config`.
