### ISSUE TITLE
Compilation problem on ARM (armv7h)

### ISSUE THREAD

**Issue by vbmithr** [basho/riak#480]
```
ld -shared  -o Linux_All_OPT.OBJ/libjs.so Linux_All_OPT.OBJ/jsapi.o Linux_All_OPT.OBJ/jsarena.o Linux_All_OPT.OBJ/jsarray.o Linux_All_OPT.OBJ/jsatom.o Linux_All_OPT.OBJ/jsbool.o Linux_All_OPT.OBJ/jscntxt.o Lin
ux_All_OPT.OBJ/jsdate.o Linux_All_OPT.OBJ/jsdbgapi.o Linux_All_OPT.OBJ/jsdhash.o Linux_All_OPT.OBJ/jsdtoa.o Linux_All_OPT.OBJ/jsemit.o Linux_All_OPT.OBJ/jsexn.o Linux_All_OPT.OBJ/jsfun.o Linux_All_OPT.OBJ/jsgc
.o Linux_All_OPT.OBJ/jshash.o Linux_All_OPT.OBJ/jsinterp.o Linux_All_OPT.OBJ/jsinvoke.o Linux_All_OPT.OBJ/jsiter.o Linux_All_OPT.OBJ/jslock.o Linux_All_OPT.OBJ/jslog2.o Linux_All_OPT.OBJ/jslong.o Linux_All_OPT
.OBJ/jsmath.o Linux_All_OPT.OBJ/jsnum.o Linux_All_OPT.OBJ/jsobj.o Linux_All_OPT.OBJ/jsopcode.o Linux_All_OPT.OBJ/jsparse.o Linux_All_OPT.OBJ/jsprf.o Linux_All_OPT.OBJ/jsregexp.o Linux_All_OPT.OBJ/jsscan.o Linu
x_All_OPT.OBJ/jsscope.o Linux_All_OPT.OBJ/jsscript.o Linux_All_OPT.OBJ/jsstr.o Linux_All_OPT.OBJ/jsutil.o Linux_All_OPT.OBJ/jsxdrapi.o Linux_All_OPT.OBJ/jsxml.o Linux_All_OPT.OBJ/prmjtime.o   -lm -L/var/abs/lo
cal/riak-git/src/riak-git/deps/erlang_js/c_src/system/lib -lnspr4                                                                                                                                                
ld: Linux_All_OPT.OBJ/jsinterp.o: relocation R_ARM_MOVW_ABS_NC against `__stack_chk_guard' can not be used when making a shared object; recompile with -fPIC                                                     
Linux_All_OPT.OBJ/jsinterp.o: error adding symbols: Bad value                                                                                                                                                    
rules.mk:125: recipe for target 'Linux_All_OPT.OBJ/libjs.so' failed                                                                                                                                              
make[4]: *** [Linux_All_OPT.OBJ/libjs.so] Error 1                                                                                                                                                                
make[4]: Leaving directory '/var/abs/local/riak-git/src/riak-git/deps/erlang_js/c_src/js/src'
```

Riak (HEAD) does not compile on ARM (Archlinux armv7h).

**Comment by jaredmorrow** [comment]
We do not currently support ARM as an architecture.  We would most likely have to change our erlang_js to use a javascript VM that supported ARM.  It has been discussed in the past, but it is not currently on our roadmap as far as I know. 

@gburd might know more regarding any possibility of supporting it in the future.  For now I will close this.

**Comment by gburd** [comment]
@vbmithr we don't currently develop or test on ARM architecture CPUs, we may in the future.  If this is a critical architecture for you please let us know.  Pull requests are always welcome!

**Comment by vbmithr** [comment]
On 31/01/2014 22:39, Gregory Burd wrote:

> @vbmithr https://github.com/vbmithr we don't currently develop or test
> on ARM architecture CPUs, we may in the future. If this is a critical
> architecture for you please let us know. Pull requests are always welcome!

Strangly enough, I managed to make it work. It was an issue on erlang_js
when compiled in a submodule of riak. I then checked out erlang_js in a
different directory and managed to get it working.

So far riak (HEAD) works on my ARM test machines.

**Comment by jaredmorrow** [comment]
Out of curiosity are you using ARM based servers or is this on an embedded
device?   Greg and I would love to hear more as this topic has come up
quite a bit.

**Comment by vbmithr** [comment]
On 01/02/2014 16:37, Jared Morrow wrote:

> Out of curiosity are you using ARM based servers or is this on an embedded
> device? Greg and I would love to hear more as this topic has come up
> quite a bit.

It is embedded devices indeed: Beaglebone-style boards, like the
cubieboard2, the odroid XU, …

In my case, I'm working on an Internet of Things project that requires
the nodes to share a DB, with a strong need for fault tolerance, and
consistency. I'm trying to use Riak for that. It seems to me that it is
the most suitable DB for this use, even though I don't care much about
the distribution of data, more the replication.
