### ISSUE TITLE
Riak 2.0: Create and activate bucket type with PBC

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak#484]
Is there a way to create and activate a bucket type with protocol buffers client? E.g. do what the following commands do:

``` bash
riak-admin bucket-type create mytype '{"props": {"datatype": "set", "allow_mult": "true"}}'
riak-admin bucket-type activate mytype
```

Sending a `RpbSetBucketTypeReq` request with the following data 

``` javascript
{
    type: 'mytype', // 'mytype' doesn't exist yet
    props: {
        datatype: 'set',
        allow_mult: true
    }
}
```

fails with `Error: Invalid bucket properties: not_active`. It works well when `mytype` already exists

**Comment by seancribbs** [comment]
No, we explicitly omitted that feature for this release, to be revisited later. Note that on activated types, some properties may also be immutable.

**Comment by oleksiyk** [comment]
Ok, thanks.
