### ISSUE TITLE
Riak 2.0: Cannot activate datatype in cluster:  <type> has been created but cannot be activated yet

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak#485]
Got the following error when tried to activate newly created datatype in a Riak 2.0 cluster: `mytype has been created but cannot be activated yet`. `mytype` was listed as `not active` on all nodes but any attempt to activate it was unsuccessful. What can be the reason for this? 

Ring was up and ready, with no pending changes. Riak 2.0.pre11

**Comment by seancribbs** [comment]
Did you run `riak-admin bucket-type activate mytype` after creating it?

**Comment by oleksiyk** [comment]
Yes:

```
$ riak-admin bucket-type create mytype '{"props": {"datatype": "set", "allow_mult": "true"}}'
mytype created
$ riak-admin bucket-type activate mytype
mytype has been created but cannot be activated yet
```

**Comment by oleksiyk** [comment]
A snapshot from console:

```
$ riak-admin bucket-type activate mytype
mytype has been created but cannot be activated yet
$ riak-admin bucket-type list
mytype (not active)
$ riak-admin bucket-type activate mytype
mytype has been created but cannot be activated yet
```

**Comment by seancribbs** [comment]
Are all of the nodes in your cluster up and reachable? A bucket-type can't be activated until all nodes have seen it.

**Comment by oleksiyk** [comment]
Yes, that was the output of ring_status:

```
$ riak-admin ring_status
================================== Claimant ===================================
Claimant:  'oleksiy@192.168.1.99'
Status:     up
Ring Ready: true

============================== Ownership Handoff ==============================
No pending changes.

============================== Unreachable Nodes ==============================
All nodes are up and reachable
```

**Comment by jrwest** [comment]
are there any errors in your logs @oleksiyk? also, could you attach to one of your riak nodes and run the following at the erlang shell and paste the result back here?

```
riak_core_claimant:get_bucket_type(<<"mytype">>, undefined, false).
```

**Comment by oleksiyk** [comment]
Sorry, that was a testing environment so its already gone :( I've tried to replicate the problem later but no luck.

**Comment by jrwest** [comment]
Ok thanks for the update. if recent attempts on newer builds are working and it can no longer be reproduced I'm going to go ahead and close this out. If you run into this again please re-open and let us know
