### ISSUE TITLE
requiretty + /etc/sudoers

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#486]
I discovered an issue in an environment where this line is present in `/etc/sudoers`:

```
Defaults    requiretty
```

Since no tty is present on system init, Riak fails to start. This also prevents using daemons like `monit` to manage Riak stop/start.

Should `su` be investigated as a replacement for `sudo` in administrative scripts?

**Comment by jaredmorrow** [comment]
This has been reported here https://github.com/basho/node_package/issues/72 and is where the bug would be fixed if we decided to do that.  Changing from `sudo` to `su` has weird edge cases passing the environment through the calls, but I haven't looked at it again in a long time.
