### ISSUE TITLE
Riak 2.0: riak-admin bucket-type create JSON parsing error

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak#487]
The following command fails on Ubuntu 12.04 with riak_2.0.0pre11-1_amd64.deb

```
$ riak-admin bucket-type create dt-test-set '{"props": {"datatype": "set", "allow_mult": "true"}}'
Usage: riak-admin bucket-type create <type> '{"props": { ... }}'
```

The fix is to remove all whitespaces in JSON:

```
$ riak-admin bucket-type create dt-test-set '{"props":{"datatype":"set","allow_mult":"true"}}'
dt-test-set created
```

The same command (with whitespaces) works with 2.0.0pre11 on Mac

**Comment by jrwest** [comment]
@oleksiyk could you try `pre14`? This issue has previously been reported and I believe addressed [1]. Although, I thought the fix was included in `pre11` I'd like to make sure it doesn't affect the most recent builds before proceeding. 

[1] https://github.com/basho/riak/issues/471

**Comment by oleksiyk** [comment]
Is `pre14` available as package somewhere? Or only as source?

**Comment by jrwest** [comment]
sorry its not linked anywhere yet but it can be downloaded from: http://s3.amazonaws.com/builds.basho.com/riak/develop/2.0.0pre14/ubuntu/precise/riak_2.0.0pre14-1_amd64.deb

**Comment by oleksiyk** [comment]
The problem still exists with `pre14`:

```
vagrant@precise64:~$ curl -sO http://s3.amazonaws.com/builds.basho.com/riak/develop/2.0.0pre14/ubuntu/precise/riak_2.0.0pre14-1_amd64.deb
vagrant@precise64:~$ sudo dpkg -i riak_2.0.0pre14-1_amd64.deb
Selecting previously unselected package riak.
(Reading database ... 51127 files and directories currently installed.)
Unpacking riak (from riak_2.0.0pre14-1_amd64.deb) ...
Setting up riak (2.0.0pre14-1) ...
Adding group `riak' (GID 111) ...
Done.
Adding system user `riak' (UID 106) ...
Adding new user `riak' (UID 106) with group `riak' ...
Not creating home directory `/var/lib/riak'.
Processing triggers for ureadahead ...
ureadahead will be reprofiled on next reboot
Processing triggers for man-db ...
vagrant@precise64:~$ sudo service riak start
!!!!
!!!! WARNING: ulimit -n is 1024; 4096 is the recommended minimum.
!!!!
vagrant@precise64:~$ riak-admin bucket-type create dt-test-set '{"props": {"datatype": "set", "allow_mult": "true"}}'
Usage: riak-admin bucket-type create <type> '{"props": { ... }}'
```

**Comment by seancribbs** [comment]
Is this just a difference in shell-quoting? Is the shell you're using
ignoring the single-quotes?

On Wed, Feb 12, 2014 at 1:53 PM, Oleksiy Krivoshey <notifications@github.com

> wrote:
> 
> The problem still exists with pre14:
> 
> vagrant@precise64:~$ curl -sO http://s3.amazonaws.com/builds.basho.com/riak/develop/2.0.0pre14/ubuntu/precise/riak_2.0.0pre14-1_amd64.deb
> vagrant@precise64:~$ sudo dpkg -i riak_2.0.0pre14-1_amd64.deb
> Selecting previously unselected package riak.
> (Reading database ... 51127 files and directories currently installed.)
> Unpacking riak (from riak_2.0.0pre14-1_amd64.deb) ...
> Setting up riak (2.0.0pre14-1) ...
> Adding group `riak' (GID 111) ...
> Done.
> Adding system user`riak' (UID 106) ...
> Adding new user `riak' (UID 106) with group`riak' ...
> Not creating home directory `/var/lib/riak'.
> Processing triggers for ureadahead ...
> ureadahead will be reprofiled on next reboot
> Processing triggers for man-db ...
> vagrant@precise64:~$ sudo service riak start
> !!!!
> !!!! WARNING: ulimit -n is 1024; 4096 is the recommended minimum.
> !!!!
> vagrant@precise64:~$ riak-admin bucket-type create dt-test-set '{"props": {"datatype": "set", "allow_mult": "true"}}'
> Usage: riak-admin bucket-type create <type> '{"props": { ... }}'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak/issues/487#issuecomment-34909701
> .

## 

Sean Cribbs sean@basho.com
Software Engineer
Basho Technologies, Inc.
http://basho.com/

**Comment by oleksiyk** [comment]
The error is in riak-admin script on line 9: https://github.com/basho/riak/blob/develop/rel/files/riak-admin#L9

That line should read: `check_user "$@"` (quotes added)

**Comment by jrwest** [comment]
my apologies, it seems this issue does have a fix [1], but it has not yet been merged. thanks for the report. I'm going to close this out as a duplicate for now.

[1] https://github.com/basho/riak/pull/473

**Comment by oleksiyk** [comment]
Great, thanks!

**Comment by jaredmorrow** [comment]
#473 has been merged now.

**Comment by oleksiyk** [comment]
I'm afraid the problem has come back with beta1:

``` bash
$ sudo riak-admin bucket-type create dt-test-set '{"props":{"datatype":"set","allow_mult":"true"}}'
Cannot create bucket type dt-test-set: invalid json
```

Default Ubuntu 12.04 installation.
shell: /bin/bash 4.2.24

**Comment by oleksiyk** [comment]
And the breaking change is in `/usr/lib/riak/lib/env.sh`:

this won't work:
`exec su - $RUNNER_USER -c "$RUNNER_SCRIPT_DIR/$RUNNER_SCRIPT $ESCAPED_ARGS"`

this will work:
`exec sudo -H -u $RUNNER_USER -i $RUNNER_SCRIPT_DIR/$RUNNER_SCRIPT "$@`

**Comment by jaredmorrow** [comment]
I have a fix for this with 'su' that will be out in the next build.  Sorry
for the trouble.

**Comment by superstructor** [comment]
Do you have an ETA on the fix being rolled into another beta ? This is still an issue with the latest beta1  Ubuntu package on the Basho downloads page. Thanks.

**Comment by seancribbs** [comment]
@superstructor We'll be making the release candidate publicly available as soon as it's ready.
