### ISSUE TITLE
New release 1.4.8

### ISSUE THREAD

**Issue by georgepsarakis** [basho/riak#495]
Does anyone know when the Ubuntu repositories will be updated for the [new release](https://github.com/basho/riak/releases/tag/riak-1.4.8)?

Thanks!

**Comment by jaredmorrow** [comment]
Sorry for the early notice, I was trying out the GitHub releases feature.
 The plan is to send out the proper release announcement today sometime.

**Comment by georgepsarakis** [comment]
@jaredmorrow thanks for taking the time to answer!
