### ISSUE TITLE
Very high traffic between two nodes in cluster

### ISSUE THREAD

**Issue by ramunasd** [basho/riak#497]
After joining two new nodes and some map reduce fails one node are sending huge amounts of data to another one. Much bigger amounts than total cluster size. Receiver logs in console.log some strange info:

```
2014-02-26 16:02:03.928 [info] <0.25675.446>@riak_core_handoff_receiver:handle_info:77 Handoff receiver for partition undefined exited after processing 0 objects
```

error.log and crash.log is empty. Restarting riak on both sides does not helps.

Riak versions 1.4.7 and 1.4.8
Ubuntu 12.04 and 13.04 64bit

**Comment by ramunasd** [comment]
More info on that:
this node shows only itself in `riak-admin member-status` while other nodes shows all nodes(including problematic one).
`riak-admin ringready` from another node gives error `[...]list different partition owners`.
After `riak-admin cluster join...` problematic node really starts hinted handoffs. No more errors `Handoff receiver for partition undefined exited after processing 0 objects`.
Huge traffic between nodes was due to AAE.

**Comment by jaredmorrow** [comment]
This looks like a split brain scenario where you actually appear to have two distinct clusters.  Are you still having the problem, or has it been resolved?  Are you on the [riak-users mailing list?](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com)  If not, we will be able to more easily help you there.

**Comment by ramunasd** [comment]
Except info about `Handoff receiver for partition undefined exited after processing 0 objects` i'm not getting any error.
