### ISSUE TITLE
SmartOS package bug in 2.0.0pre11

### ISSUE THREAD

**Issue by RyanGordon** [basho/riak#505]
Using the latest available SmartOS tarball the following output is produced:

[root@node1 / ] # pkg_add http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.0pre11/smartos/13.1/riak-2.0.0pre11-SmartOS-x86_64.tgz
Creating directory /var/db/riak owned by riak
Creating directory /var/log/riak owned by riak
Skipping directory creation of /var, directory already exists
Skipping directory creation of /var/db, directory already exists
Skipping directory creation of /var/db/riak, directory already exists
Creating directory /var/db/riak/ring owned by riak
Executing 'chmod o-r /opt/local/etc/riak/vm.args'
chmod: cannot access `/opt/local/etc/riak/vm.args': No such file or directory
pkg_add: command 'chmod o-r /opt/local/etc/riak/vm.args' failed
Executing 'chown -R root:riak /opt/local/etc/riak'
Executing 'chmod -R g+r+X /opt/local/etc/riak'
Executing 'chown -R riak:riak /opt/local/lib/riak'
Thank you for installing riak.

riak has been installed in /opt/local/lib/riak owned by user:group riak:riak

The primary directories are:

```
{platform_bin_dir, "/opt/local/sbin"}
{platform_data_dir, "/var/db/riak"}
{platform_etc_dir, "/opt/local/etc/riak"}
{platform_lib_dir, "/opt/local/lib/riak/lib"}
{platform_log_dir, "/var/log/riak"}
```

These can be configured and changed in the /opt/local/etc/riak/app.config.

Add /opt/local/sbin to your path to run the riak riak-admin search-cmd riak-debug directly.

Man pages are available for riak(1) riak-admin(1) search-cmd(1) riak-debug(1) 

//////////////////////////////////////////////////////////////////////////////

This package is SMF enabled, which means you can use SMF to 'enable',
'disable' or 'restart' the persistent daemon process, e.g.:

  $ svcadm enable -r riak

Two SMF manifests were created, "riak-epmd" and "riak". riak depends
on the "riak-epmd" service to be enabled, so either use "-r" to specify
to "svcadm" (as shown above) to recursively start dependencies or
start each service independent of each other.

  $ svcadm enable riak-epmd
  $ svcadm enable riak

You should _NOT_ stop or restart the "riak-epmd" service at any time,
if you need to restart riak, just restart the "riak" service.

See the SmartOS wiki on what's SMF and how to use it to your advantage:

  http://wiki.joyent.com/display/smart/About+the+Service+Management+Facility

//////////////////////////////////////////////////////////////////////////////

It seems like the only bug is:
Executing 'chmod o-r /opt/local/etc/riak/vm.args'
chmod: cannot access `/opt/local/etc/riak/vm.args': No such file or directory
pkg_add: command 'chmod o-r /opt/local/etc/riak/vm.args' failed

This is because the vm.args and riak.config files have been replaced with a new type of  config file in 2.0, the riak.conf file.

Seems like a pretty easy fix

Thanks for the great product!

**Comment by jaredmorrow** [comment]
Thanks for the report, you indeed are correct.  I'll get this fixed a.s.a.p.

**Comment by jaredmorrow** [comment]
Fixed, will be in our beta build.

**Comment by RyanGordon** [comment]
Thanks!
