### ISSUE TITLE
Issue with 2i sorting on Linux

### ISSUE THREAD

**Issue by wcamarao** [basho/riak#507]
I originally opened this in riak-ruby-client but it seems like it's in riak itself

https://github.com/basho/riak-ruby-client/issues/153
### How to reproduce
- Create 3 documents: A, B, C, each one with corresponding keys "a", "b", "c"
- Save A into a bucket; and save B and C into another bucket
- Index B on A with index name "foo"
- Index C on A with index name "foo"
- Lookup index name "foo" on A
### Expected:
- B, C (in this order, as the index name is the same, so then sorting should happen by key)
### Actual:
- As expected in OS X;
- Random on Linux. Sometimes you will get B, C, sometimes you will get C, B.
### Ruby script to reproduce it

``` ruby
require 'riak'

client = Riak::Client.new

docs = client.bucket('docs')
revs = client.bucket('revs')

a = Riak::RObject.new(docs, 'a').tap { |o| o.content_type = 'application/json'; o.data = {} }
b = Riak::RObject.new(revs, 'b').tap { |o| o.content_type = 'application/json'; o.data = {} }
c = Riak::RObject.new(revs, 'c').tap { |o| o.content_type = 'application/json'; o.data = {} }

b.indexes['foo_bin'] << 'a'
c.indexes['foo_bin'] << 'a'

a.store
b.store
c.store

keys = revs.get_index('foo_bin', 'a') || []

puts 'Expected keys: b, c'
puts "Actual: #{keys.join(', ')}"

a.delete
b.delete
c.delete
```
### Running on OS X

```
~/Projects ruby r2i.rb
Expected keys: b, c
Actual: b, c

~/Projects ruby r2i.rb
Expected keys: b, c
Actual: b, c
```

(always get the same output)
### Running on Linux

```
wagner@qa:~$ ruby 2i.rb
Expected keys: b, c
Actual: b, c

wagner@qa:~$ ruby 2i.rb
Expected keys: b, c
Actual: c, b

wagner@qa:~$ uname -a
Linux qa 3.2.0-54-virtual #82-Ubuntu SMP Tue Sep 10 20:31:18 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

(sorting order is random - so I included only two outputs)

**Comment by reiddraper** [comment]
cc @engel. Wondering if this is because we changed 2i to _not_ be sorted except when using pagination. @wcamarao what version of Riak are you using?

**Comment by wcamarao** [comment]
@reiddraper 1.4.1 on OSX and 1.4.6 on Linux

Just replied https://github.com/basho/riak-ruby-client/issues/153#issuecomment-37608478 with riak-admin status on both machines

**Comment by jaredmorrow** [comment]
This (I believe) https://github.com/basho/riak/blob/1.4/RELEASE-NOTES.md#sorting-in-non-paginated-queries explains the difference you are seeing.  

Closing this issue, since you have it filed against the ruby client as well.
