### ISSUE TITLE
SSL options in vm.args make nodetool stop working [JIRA: RIAK-1579]

### ISSUE THREAD

**Issue by 613038475** [basho/riak#509]
Hello,
I found use ssl options in vm.args will let nodetool (riak start, riak-admin status, etc...) stop working.
The reason is env.sh only pick up name and cookie from vm.args then pass to nodetool.
Here is a patch to fix this problem.
https://gist.github.com/613038475/9546619

Also I found this option is not valid.
-proto_dist inet_ssl
it should be
-proto_dist inet_tls

**Comment by bsparrow435** [comment]
I just confirmed this locally against develop. The fix is valid but we really should have a riak_test to validate this.

**Comment by 613038475** [comment]
That patch is not useable, it will make erl boot from "riak start" or "riak console" duplicate the ssl argument.

**Comment by seancribbs** [comment]
Note that previously, this was slurped in from a separate file. Unfortunately you cannot pass init arguments from the command line into an escript; they have to be specified in the comment line after the shebang. This means that any disterl-related arguments have to be in a file that is referred to in the comment line, which is what was done in `nodetool` in the past. Fixing this issue would require changes to OTP.

**Comment by tombriden** [comment]
This has recently been an issue for me, the attached patch doesn't appear to work with 2.0.5 but a slight variation on it works and there are no duplicate SSL variables when using "riak console" or "riak start"

```
SSL_ARGS=`grep -e '^\-ssl_dist_opt' -e '^\-proto_dist' $RUNNER_ETC_DIR/vm.args | tr '\n' ' '`
# Setup command to control the node
NODETOOL="eval ERL_FLAGS=\"$ERL_FLAGS $SSL_ARGS\" $ERTS_PATH/escript $ERTS_PATH/nodetool $NET_TICKTIME_ARG $NAME_ARG $COOKIE_ARG"
```

there's also a separate issue with some extra output from nodetool when using SSL making get_pid fail, fixable with

```
PID=`$NODETOOL getpid < /dev/null|head -1`
```

**Comment by ryanbamford** [comment]
have modded this additionally to include a check for the file 

if [ -f $RUNNER_ETC_DIR/vm.args ]; then
   SSL_ARGS=`grep -e '^\-ssl_dist_opt' -e '^\-proto_dist' $RUNNER_ETC_DIR/vm.args | tr '\n' ' '`
   NODETOOL="eval ERL_FLAGS=\"$ERL_FLAGS $SSL_ARGS\" $ERTS_PATH/escript $ERTS_PATH/nodetool $NET_TICKTIME_ARG $NAME_ARG $COOKIE_ARG"
else
   NODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NET_TICKTIME_ARG $NAME_ARG $COOKIE_ARG"
fi

so it can run with and without the vm.args file without errors 

not a full fix as we are using 2.0.5 which uses the generated vm.args and we are having to override them to get the tls settings in 

so we are reading the settings from the override location

**Comment by tombriden** [comment]
The mod to env.sh isn't a complete fix as some commands still fail, such as `riak-admin bucket-type create`

What actually works is to use an alias for nodetool rather than store the command in a variable. So, changing env.sh to

```
if [ -f $RUNNER_ETC_DIR/vm.args ]; then
    SSL_ARGS=$(grep -e '^\-ssl_dist_opt' -e '^\-proto_dist' $RUNNER_ETC_DIR/vm.args | tr '\n' ' ')
fi
alias NODETOOL="ERL_FLAGS=\"$ERL_FLAGS $SSL_ARGS\" $ERTS_PATH/escript $ERTS_PATH/nodetool $NET_TICKTIME_ARG $NAME_ARG $COOKIE_ARG"
```

and then updating env.sh and riak-admin so all `$NODETOOL` calls become just `NODETOOL`.

**Comment by Basho-JIRA** [comment]
Fixed by changing node_package to use an alias for nodetool instead of an environment variable. 

***[posted via JIRA by Brian Sparrow]***
