### ISSUE TITLE
Can't start riak (2.0 pre11.1)

### ISSUE THREAD

**Issue by chapani** [basho/riak#512]
I installed riak 2.0 from source (make rel). Also, installed basho/otp (patched erlang R16).

ps aux | grep riak shows no other riak instances. Rebooted my whole server. But I'm getting this:

``` bash
./riak start
riak failed to start within 15 seconds,
see the output of 'riak console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
```

riak console is outputting this:

``` bash
15:47:53.167 [warning] cuttlefish_util:filter_by_variable_starts_with/2 has been deprecated. use cuttlefish_variable:filter_by_prefix/2
config is OK
-config /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/app.2014.03.17.15.47.52.config -args_file /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args -vm_args /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args
Exec:  /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../erts-5.9.2/bin/erlexec -boot /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../releases/2.0.0pre11/riak               -config /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/app.2014.03.17.15.47.52.config -args_file /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args -vm_args /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args              -pa /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../lib/basho-patches -- console
Root: /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/..
{error_logger,{{2014,3,17},{15,47,53}},"Protocol: ~p: register error: ~p~n",["inet_tcp",{{badmatch,{error,duplicate_name}},[{inet_tcp_dist,listen,1,[{file,"inet_tcp_dist.erl"},{line,70}]},{net_kernel,start_protos,4,[{file,"net_kernel.erl"},{line,1314}]},{net_kernel,start_protos,3,[{file,"net_kernel.erl"},{line,1307}]},{net_kernel,init_node,2,[{file,"net_kernel.erl"},{line,1197}]},{net_kernel,init,1,[{file,"net_kernel.erl"},{line,357}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}]}
{error_logger,{{2014,3,17},{15,47,53}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.224>,<0.17.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,24},{reductions,510}],[]]}
{error_logger,{{2014,3,17},{15,47,53}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['riak@127.0.0.1',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2014,3,17},{15,47,53}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2014,3,17},{15,47,53}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}

Crash dump was written to: ./log/erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})
```

What am I doing wrong?

Thanks!

**Comment by seancribbs** [comment]
You already have a riak node running with that name -- this is indicated by
the `duplicate_name` error. Run `ps aux | grep riak` to see if there is an
existing Riak process running.

On Mon, Mar 17, 2014 at 10:50 AM, buriwoy notifications@github.com wrote:

> I installed riak 2.0 from source (make rel). Also, installed basho/otp
> (patched erlang R16).
> 
> ps aux | grep riak shows no other riak instances. Rebooted my whole
> server. But I'm getting this:
> 
> ./riak start
> riak failed to start within 15 seconds,
> see the output of 'riak console' for more information.
> If you want to wait longer, set the environment variable
> WAIT_FOR_ERLANG to the number of seconds to wait.
> 
> riak console is outputting this:
> 
> 15:47:53.167 [warning] cuttlefish_util:filter_by_variable_starts_with/2 has been deprecated. use cuttlefish_variable:filter_by_prefix/2
> config is OK
> -config /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/app.2014.03.17.15.47.52.config -args_file /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args -vm_args /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args
> Exec:  /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../erts-5.9.2/bin/erlexec -boot /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../releases/2.0.0pre11/riak               -config /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/app.2014.03.17.15.47.52.config -args_file /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args -vm_args /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.47.52.args              -pa /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../lib/basho-patches -- console
> Root: /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/..{error_logger,{{2014,3,17},{15,47,53}},"Protocol: ~p: register error: ~p~n",["inet_tcp",{{badmatch,{error,duplicate_name}},[{inet_tcp_dist,listen,1,[{file,"inet_tcp_dist.erl"},{line,70}]},{net_kernel,start_protos,4,[{file,"net_kernel.erl"},{line,1314}]},{net_kernel,start_protos,3,[{file,"net_kernel.erl"},{line,1307}]},{net_kernel,init_node,2,[{file,"net_kernel.erl"},{line,1197}]},{net_kernel,init,1,[{file,"net_kernel.erl"},{line,357}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}]}{error_logger,{{2014,3,17},{15,47,53}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.224>,<0.17.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,24},{reductions,510}],[]]}{error_logger,{{2014,3,17},{15,47,53}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['riak@127.0.0.1',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_t
>  ype,worker}]}]}{error_logger,{{2014,3,17},{15,47,53}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}{error_logger,{{2014,3,17},{15,47,53}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}
> 
> Crash dump was written to: ./log/erl_crash.dump
> Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})
> 
> What am I doing wrong?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak/issues/512
> .

## 

Sean Cribbs sean@basho.com
Software Engineer
Basho Technologies, Inc.
http://basho.com/

**Comment by chapani** [comment]
I did that before and it didn't help. Here is the fresh one:

``` bash
ps aux | grep riak
ld        4134  0.0  0.0   7404   596 ?        S    15:31   0:00 /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../erts-5.9.2/bin/epmd -daemon
ld        4142  0.0  0.0  14824   808 ?        S    15:31   0:00 /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../erts-5.9.2/bin/run_erl -daemon /tmp//home/ld/apps/riak-2.0.0pre11/rel/riak/bin/..// /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../log exec /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/riak console
ld        4145  4.6  6.9 7738420 70168 pts/6   Ssl+ 15:31   3:19 /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../erts-5.9.2/bin/beam.smp -P 256000 -e -Q -A 64 -K true -W w -- -root /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/.. -progname riak -- -home /home/ld -- -boot /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../releases/2.0.0pre11/riak -config /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/app.2014.03.17.15.31.47.config -setcookie riak 256000 65536 -name riak@127.0.0.1 -smp enable -vm_args /home/ld/apps/riak-2.0.0pre11/rel/riak/data/generated.configs/vm.2014.03.17.15.31.47.args -pa /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../lib/basho-patches -- console
ld        4395  0.0  0.0   4288   608 ?        Ss   15:31   0:00 /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../lib/os_mon-2.2.10/priv/bin/memsup
ld        4396  0.0  0.0   4288   352 ?        Ss   15:31   0:00 /home/ld/apps/riak-2.0.0pre11/rel/riak/bin/../lib/os_mon-2.2.10/priv/bin/cpu_sup
```

**Comment by chapani** [comment]
``` bash
ld$ ps aux | grep riak
ld        7080  0.0  0.0   9380   936 pts/4    S+   16:49   0:00 grep --color=auto riak
ld$ ./riak start
riak failed to start within 15 seconds,
see the output of 'riak console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
ld$
```

**Comment by seancribbs** [comment]
Just because it doesn't appear to have started according to the launcher/control script, doesn't it mean that it didn't start. Use `ps aux` and `tail -f` on the console log file to be sure.

**Comment by chapani** [comment]
did you mean this:

``` bash
ld$ ps aux | tail -f
ld        2935  0.0  1.0  29468 10820 pts/0    Ss   15:30   0:00 -bash
ld        3121  0.0  0.1  17792  1164 pts/0    S+   15:30   0:00 tmux new -s processes
ld        3123  0.1  0.1  26540  1896 ?        Ss   15:30   0:05 tmux new -s processes
ld        3124  0.0  1.0  29520 10840 pts/1    Ss+  15:30   0:01 -bash
ld        3310  0.0  1.0  29520 10848 pts/2    Ss+  15:31   0:01 -bash
ld        3460  0.0  1.0  29520 10844 pts/3    Ss+  15:31   0:01 -bash
ld        5219  0.0  1.0  29552 10948 pts/4    Ss   15:42   0:01 -bash
root      7756  0.0  0.0      0     0 ?        S    16:49   0:00 [kworker/u16:2]
ld        8003  0.0  0.1  18156  1272 pts/4    R+   17:05   0:00 ps aux
ld        8004  0.0  0.0   7192   680 pts/4    S+   17:05   0:00 tail -f
ld$ ps aux | grep riak
ld        8006  0.0  0.0   9380   936 pts/4    S+   17:05   0:00 grep --color=auto riak
ld$ ./riak start
riak failed to start within 15 seconds,
see the output of 'riak console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
```

**Comment by cheeseplus** [comment]
Is there an epmd process running?

**Comment by chapani** [comment]
thanks!

I don't know what epmd is. How can I check it?

**Comment by cheeseplus** [comment]
It's a a supervisory Erlang process that doesn't necessarily die when you stop Riak. You should be able to grep for `epmd` in a process list and kill it.

**Comment by cheeseplus** [comment]
This is a classic Riak error and this ML post sums it up well: http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-March/007806.html

**Comment by chapani** [comment]
I killed both epmd and beam.smp, but it didn't help. I rebooted, checked ports and they were free. Still having the "WAIT_FOR_ERLANG" error.

Btw, I was able to start my old Riak. So, it must be something only 2.0-related.

**Comment by chapani** [comment]
the last build was successfully started: riak-2.0.0pre15

thanks guys,
Buriwoy

**Comment by chapani** [comment]
Finally figured out the reason. It was /home/user/.erlang.cookie. After deleting it, riak started successfully. Hope it will help someone :)
