### ISSUE TITLE
Riak 2.0: How to setup multi backend

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak#515]
Can you please suggest how to setup multi backend in riak.conf for Riak 2.0?

I tried the following but it din't work:

```
storage_backend = multi

multi_backend.default.storage_backend = leveldb
multi_backend.default.leveldb.data_root = ./data/leveldb/default

multi_backend.fs_files.storage_backend = leveldb
multi_backend.fs_files.leveldb.data_root = ./data/leveldb/fs.files

multi_backend.fs_chunks.storage_backend = leveldb
multi_backend.fs_chunks.leveldb.data_root = ./data/leveldb/fs.chunks
```

Riak didn't start up with the following message:

```
17:33:42.991 [warning] cuttlefish_util:filter_by_variable_starts_with/2 has been deprecated. use cutt
lefish_variable:filter_by_prefix/2

17:33:42.994 [error] Error generating configuration in phase apply_translations

17:33:42.994 [error] Error running translation for riak_kv.multi_backend, [error, function_clause].

Error generating config with cuttlefish
```

Also I was not able to find cuttlefish mapping for the following leveldb params:
`max_open_files`
`block_size`
`cache_size`

Thanks!

**Comment by jrwest** [comment]
I've marked this for milestone `2.0-RC`, it will be investigated at the latest by that release. However, I'm sure @joedevivo can shed some light on this a bit sooner.

**Comment by joedevivo** [comment]
basho/cuttlefish#130 has resolved this issue. You can try building from develop to use your multi_backend config.
