### ISSUE TITLE
riak-debug enhancement suggestions

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#522]
- logs: `/var/log/kern.log` should be included if present. It has human-readable dates, as opposed to `dmesg`.
- `netstat`: It would be great to have the PID of processes owning the connection. In general this is done using the `-p` argument.
- Recursive long list of Riak data directories and summary of data directory size.

**Comment by bsparrow435** [comment]
Adding more enhancements:
- riak-cs logs
- stanchion logs
- flag for riak-cs access logs

**Comment by lukebakken** [comment]
`riak-debug` should list the contents of the `basho-patches` directory

**Comment by reiddraper** [comment]
+1, these are great

**Comment by jonasrichard** [comment]
About the basho-patches it would be good to do a

```
m(riak_patched_module).
```

for all files in the `lib/basho-pacthes` in order to see when it was compiled, what kind of export it has, etc. It would be good to see some kind of commit hash.

**Comment by binarytemple** [comment]
My PR from 24th Oct 2014 - https://github.com/basho/riak/pull/614 check ulimits are set in /etc/default/riak save someone a day sometime.
