### ISSUE TITLE
Starting Riak using a Puppet agent will not work

### ISSUE THREAD

**Issue by siddhuwarrier** [basho/riak#526]
I am writing a bunch of Puppet scripts for Riak and Riak CS, and I found that I could not start my service when running `puppet agent -tv` on Centos 6.x

The underlying reason is that Riak is started up using `sudo -H` - sudo cannot be executed by default if there is no tty. I have had to manually disable `requiretty` for the root user in order for the puppet scripts to work.

I would suggest that Riak's startup script uses `su -c` instead. 

Riak version: riak-1.4.8

**Comment by jaredmorrow** [comment]
This has been reported before and we have plans to fix this in our packaging scripts post-2.0.

https://github.com/basho/node_package/issues/125

**Comment by jaredmorrow** [comment]
@siddhuwarrier the plan to push this past 2.0 is canceled since we found some time to fix it for 2.0 beta :)
