### ISSUE TITLE
Riak DT api doesn't honor content types

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak#529]
```
➜  riak git:(develop) curl -X GET http://127.0.0.1:8098/types/counters/buckets/goals/datatypes/pominville -H "content-type: application/xml" -d 1
{"type":"counter","value":1}%
```

Appears to return JSON, regardless.

**Comment by seancribbs** [comment]
`Content-Type` header from the client specifies the **request** media-type, not the acceptable ones. You also cannot update via `GET`.

If you use `-H "Accept: application/xml"` you should get the appropriate 406 response.

**Comment by cmeiklejohn** [comment]
sigh, it's Friday, I'm off my game. :)

**Comment by seancribbs** [comment]
np, been off my game all week

**Comment by PharkMillups** [comment]
Even Jordan had off days.

**Comment by andrewjstone** [comment]
A wild @PharkMillups appears

**Comment by rzezeski** [comment]
How'd your `Accept` game come up?

**Comment by cmeiklejohn** [comment]
Poorly.
