### ISSUE TITLE
Support for Erlang R17

### ISSUE THREAD

**Issue by sendtopms** [basho/riak#534]
Since R17 is released, support would be nice. I tried running on R17 with few changes to  crypto API(MD5/SHA) call seems simple to just for running R17. But looking at backward support for changes/deprecated API in crypto module needs some thought.

**Comment by jaredmorrow** [comment]
We are shipping Riak 2.0 with R16 + our patches for crypto.  It will probably be some time before we support R17 officially.

**Comment by sendtopms** [comment]
Thats nice. It will be great if it applies based on detected erl. Thanks.

**Comment by sumerman** [comment]
@jaredmorrow Please, allow others to compile riak & riak_core with r17 without fixing all the `rebar.config`s?
