### ISSUE TITLE
Datatypes, i2 and Search

### ISSUE THREAD

**Issue by prepor** [basho/riak#538]
Hello!

Does Datatypes support by i2 and Search? I can't find answer in docs and api but do not understand this restriction in low level. 
For search it's just new extractor, isn't it? And for i2 it's just API problem, isn't it?

Thanks

**Comment by russelldb** [comment]
Hi Prepor,
Please use our excellent mailing list for questions like this, issues are for issues.

http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com Is this best place to discuss this sort of thing. I'm happy to elaborate there. Short answer is no to 2i (and it is more than an API thing, or we'd have done it) and yes to riak-search 2.0, it was just an extractor.

I'm going to close this issue now. Thanks.
