### ISSUE TITLE
Riak Search 2

### ISSUE THREAD

**Issue by 3goats** [basho/riak#545]
Hi, I've been following the search 2 tutorial using Solr and I'm a liitle confused. If I run the following query using curl as per the example: 

```
curl "$RIAK_HOST/search/famous?wt=json&q=name_s:Lion*" | jsonpp

I get this response: 

"response": {
    "numFound": 1,
    "start": 0,
    "maxScore": 1.0,
    "docs": [
      {
        "leader_b": true,
        "age_i": 30,
        "name_s": "Lion-o",
        "_yz_id": "animals_cats_liono_10",
        "_yz_rk": "liono",
        "_yz_rt": "animals",
        "_yz_rb": "cats"
      }
    ]
  }
}
```

However, If I run the same query within Solr's web console e.g. `name_s:Lion*` I get this response:

```
"response": {
    "numFound": 3,
    "start": 0,
    "docs": [
      {
        "leader_b": true,
        "age_i": 30,
        "name_s": "Lion-o",
        "_yz_id": "animals_cats_liono_10",
        "_yz_rk": "liono",
        "_yz_rt": "animals",
        "_yz_rb": "cats"
      },
      {
        "leader_b": true,
        "age_i": 30,
        "name_s": "Lion-o",
        "_yz_id": "animals_cats_liono_11",
        "_yz_rk": "liono",
        "_yz_rt": "animals",
        "_yz_rb": "cats"
      },
      {
        "leader_b": true,
        "age_i": 30,
        "name_s": "Lion-o",
        "_yz_id": "animals_cats_liono_12",
        "_yz_rk": "liono",
        "_yz_rt": "animals",
        "_yz_rb": "cats"
      }
    ]
  }
```

Is this expected ?

**Comment by rzezeski** [comment]
> However, If I run the same query within Solr's web console e.g. name_s:Lion\* I get this response:

You will not get correct results from Solr's HTTP port or its web console.  Yokozuna handles the distributed bits and you need to query via Yokozuna in order for the appropriate distributed query to be run.  All use of Solr's HTTP port should be avoided.

**Comment by 3goats** [comment]
Thanks this makes sense now. Might be worth highlighting this useful info in the docs.
