### ISSUE TITLE
Riak Search 2

### ISSUE THREAD

**Issue by 3goats** [basho/riak#550]
Ok, So I created my own custom Solr schema and added it to Riak using this:

`curl -XPUT "$RIAK_HOST/search/schema/custom" -H 'content-type:application/xml' --data-binary @../custom_schemas/default_schema.xml`

I can see it via this:
`curl -XGET "$RIAK_HOST/search/schema/custom"`

```
<?xml version="1.0" encoding="UTF-8" ?>

<schema name="scans" version="1.5">
 <fields>

    <!--Custom Field names  -->
   <field name="scan_id" type="string" indexed="true" stored="true"/>
   <field name="hex_encoded_data" type="string" indexed="true" stored="true"/>
   <field name="data1" type="string" indexed="true" stored="true"/>
   <field name="data2" type="int" indexed="true" stored="true"/>
   <field name="data3" type="int" indexed="true" stored="true"/>..............
```

Then I created a new search index like this:

`curl -XPUT "$RIAK_HOST/search/index/ved" -H 'content-type:application/json' -d '{"schema":"custom"}`

I can see it here: 

`curl -XGET "$RIAK_HOST/search/index/"`
`[{"name":"ved","n_val":3,"schema":"custom"}]`

I then try to create a new bucket type that references the new search index:

`./riak-admin bucket-type create scans '{"props":{"search_index":"ved"}}'`

Which returns this:

`Error creating bucket type scans: [{search_index,<<"ved does not exist">>}]`

Am a missing something here?

**Comment by 3goats** [comment]
OK - So I sorted this problem. I had a duplicate field within my custom schema. This was visible in the Solr Web UI. Are there any plans to validate the schema at this stage? 

`curl -XPUT "$RIAK_HOST/search/index/ved" -H 'content-type:application/json' -d '{"schema":"custom"}`

or is there a command to check the status for the Solr core that gets created via the above command. Since #545 ("All use of Solr's HTTP port should be avoided") suggests keeping well a way from Solr's HTTP interface there needs to be a way to check the status for the schema.

**Comment by slfritchie** [comment]
@rzezeski @coderoshi Any thoughts on a milestone assignment?

**Comment by rzezeski** [comment]
> OK - So I sorted this problem. I had a duplicate field within my custom schema. This was visible in the Solr Web UI. Are there any plans to validate the schema at this stage?

There is some validation performed but only so much can be done by Riak itself.  Solr provides no mechanism for validating a schema before creating an index.  It's a long discussion and not as straightforward as it seems.  In the future I'd like to see Riak have the ability to "prepare" or "test" an index before "committing" it.  This would allow you to more easily determine if a schema is broken before final creation.  But that is not something that can be done for 2.0.0 as the feature cutoff has long passed.

> or is there a command to check the status for the Solr core that gets created via the above command. Since #545 ("All use of Solr's HTTP port should be avoided") suggests keeping well a way from Solr's HTTP interface there needs to be a way to check the status for the schema.

For HTTP you can perform a `GET /search/index/Index` to determine if an index exists and is up (there is also a PB msg which the clients should support).  I tested this myself by uploading a schema with a duplicate field.  Here is what I saw:

Upload a schema with duplicate field:

```
# curl -i -X PUT -H 'content-type: application/xml' 'http://localhost:8098/search/schema/dup' --data-binary @/root/
duplicate-field.xml
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Server: MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)
Date: Thu, 29 May 2014 16:16:16 GMT
Content-Type: application/xml
Content-Length: 0
```

Create an index using `dup` field:

```
# curl -i -X PUT -H 'content-type: application/json' 'http://localhost:8098/search/index/dup' -d '{"schema":"dup"}'

HTTP/1.1 204 No Content
Server: MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)
Date: Thu, 29 May 2014 16:16:56 GMT
Content-Type: application/json
Content-Length: 0
```

Perform a GET against the index:

```
#
[root@basho_dev ~/work/riak]# curl -i 'http://localhost:8098/search/index/dup'
HTTP/1.1 404 Object Not Found
Server: MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)
Date: Thu, 29 May 2014 16:17:24 GMT
Content-Type: text/plain
Content-Length: 10

not found
```

Contents of the console.log:

```
2014-05-29 16:16:56.842 [error] <0.550.0>@yz_index:local_create:193 Couldn't create index dup: {ok,"400",[{"Content-Type","application/xml; charset=UTF-8"},{"Transfer-Encoding","chunked"}],<<"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<response>\n<lst name=\"responseHeader\"><int name=\"status\">400</int><int name=\"QTime\">645</int></lst><lst name=\"error\"><str name=\"msg\">Error CREATEing SolrCore 'dup': Unable to create core: dup Caused by: [schema.xml] Duplicate field definition for 'text' [[[text{type=text_general,properties=indexed,tokenized,multiValued}]]] and [[[text{type=text_general,properties=indexed,tokenized,multiValued}]]]</str><int name=\"code\">400</int></lst>\n</response>\n">>}
```

Contents of the solr.log:

```
2014-05-29 16:16:56,836 [ERROR] <qtp751799423-20>@CoreContainer.java:988 Unable to create core: dup
org.apache.solr.common.SolrException: [schema.xml] Duplicate field definition for 'text' [[[text{type=text_general,properties=indexed,tokenized,multiValued}]]] and [[[text{type=text_general,properties=indexed,tokenized,multiValued}]]]. Schema file is /root/work/riak/rel/riak/data/yz/dup/./dup.xml
    at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:614)
    at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:166)
    at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55)
    at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java
...
```

Until the index and schema administration can be made more fluid it may be best to vet a schema in development with the method above before uploading to production.

**Comment by rzezeski** [comment]
Re-reading your original issue I decided to try `GET /search/index` with the failed index creation and sure enough it returns `dup` in the list even though it failed to create.

```
# curl -i 'http://localhost:8098/search/index'
HTTP/1.1 200 OK
Server: MochiWeb/1.1 WebMachine/1.10.5 (jokes are better explained)
Date: Thu, 29 May 2014 16:30:52 GMT
Content-Type: application/json
Content-Length: 41

[{"name":"dup","n_val":3,"schema":"dup"}]
```

That is definitely confusing.  I'll create an issue.

**Comment by rzezeski** [comment]
I'm closing this in favor of basho/yokozuna#395.
