### ISSUE TITLE
Building RIAK from Source crashes at rebar generate on open suse [JIRA: RIAK-2069]

### ISSUE THREAD

**Issue by itsavvy-ankur** [basho/riak#551]
Having spent the entire day trying to build RIAK from source and resolving associated problems, I am running into problems potentially towards the final stages of the build during rebar generate phase.

The below error message does not help me identify the problem ( or fix it). Hoping for some assistance : 
Error : Message : 
./rebar generate 
==> rel (generate)
ERROR: Unexpected error: {'EXIT',{{badmatch,{error,enoent}},
                                  [{rebar_reltool,execute_overlay,4,[]},
                                   {rebar_reltool,generate,2,[]},
                                   {rebar_core,run_modules,4,[]},
                                   {rebar_core,execute,5,[]},
                                   {rebar_core,process_dir1,6,[]},
                                   {rebar_core,process_each,5,[]},
                                   {rebar_core,process_dir1,6,[]},
                                   {rebar_core,process_commands,2,[]}]}}
ERROR: generate failed while processing /home/ankur/riak/rel: rebar_abort
make: **\* [generate] Error 1

Configuration : 
OpenSUSE 13.1 on Oracle Virtual Box VT-x / AMD-V accelaration
eleveldb checked out tag is 1.1.0 ( due to : https://github.com/basho/eleveldb/issues/106 )
- Also tried with eleveldb 1.2.0 (same issue)

Erlang is R16B01, reltool installed separately(since it was not installed by default)

**Comment by jaredmorrow** [comment]
If you are trying to build develop, right now we are shipping a R16 with patches from R17 included.  You can build erlang from the following tarball http://s3.amazonaws.com/downloads.basho.com/erlang/otp_src_R16B02-basho5.tar.gz
 as you normally would.

Every one of the patches have already been accepted by the OTP team.  So there will be forward compatibility when we move to R17 in the future.

Sorry for your issues.

**Comment by taurusser** [comment]
issue still be there.
ubuntu 14.04 trusty
erlang : otp_src_R16B02-basho5
eleveldb : rolling tag 1.2.0

make rel
==> riak_ensemble (compile)
==> pbkdf2 (compile)
==> riak_core (compile)
==> riak_pipe (compile)
==> protobuffs (compile)
==> riak_pb (compile)
==> mochiweb (compile)
==> ibrowse (compile)
==> webmachine (compile)
==> riak_api (compile)
==> riak_dt (compile)
==> eunit_formatters (compile)
==> riak_kv (compile)
==> merge_index (compile)
==> lucene_parser (compile)
==> riak_search (compile)
==> erlydtl (compile)
==> riak_control (compile)
Compiled handlebars asset priv/admin/js/generated/templates.js
==> riaknostic (compile)
==> kvc (compile)
==> yokozuna (compile)
==> canola (compile)
==> riak_auth_mods (compile)
==> rebar_lock_deps_plugin (compile)
==> rel (compile)
==> riak (compile)
==> riak (compile)
./rebar generate 
==> rel (generate)
ERROR: Unexpected error: {'EXIT',{{badmatch,{error,enoent}},
                                  [{rebar_reltool,execute_overlay,4,[]},
                                   {rebar_reltool,generate,2,[]},
                                   {rebar_core,run_modules,4,[]},
                                   {rebar_core,execute,5,[]},
                                   {rebar_core,process_dir1,6,[]},
                                   {rebar_core,process_each,5,[]},
                                   {rebar_core,process_dir1,6,[]},
                                   {rebar_core,process_commands,2,[]}]}}
ERROR: generate failed while processing /home/pandora/download/riak/rel: rebar_abort
make: **\* [generate] 错误 1

**Comment by NoKriK** [comment]
Hi,

I just hit the same issue while trying to compile Riak on Scaleway.

```
./rebar generate
==> rel (generate)
ERROR: Unexpected error: {'EXIT',
                             {{badmatch,{error,enoent}},
                              [{rebar_reltool,execute_overlay,4,
                                   [{file,"src/rebar_reltool.erl"},
                                    {line,388}]},
                               {rebar_reltool,generate,2,
                                   [{file,"src/rebar_reltool.erl"},{line,60}]},
                               {rebar_core,run_modules,4,
                                   [{file,"src/rebar_core.erl"},{line,491}]},
                               {rebar_core,execute,6,
                                   [{file,"src/rebar_core.erl"},{line,416}]},
                               {rebar_core,maybe_execute,8,
                                   [{file,"src/rebar_core.erl"},{line,300}]},
                               {rebar_core,process_dir1,7,
                                   [{file,"src/rebar_core.erl"},{line,259}]},
                               {rebar_core,process_each,5,
                                   [{file,"src/rebar_core.erl"},{line,349}]},
                               {rebar_core,process_dir1,7,
                                   [{file,"src/rebar_core.erl"},
                                    {line,251}]}]}}
ERROR: generate failed while processing /root/riak/rel: rebar_abort
Makefile:34: recipe for target 'generate' failed
make: *** [generate] Error 1
```

Here is the environment in which I'm trying to compile Riak:
Erlang version: R16B02-basho8 built using kerl
OS: Ubuntu 15.04 (Vivid)
Riak tag: 2.1.1
ElevelDB: 1.1.1

I just found that version 1.1.1 of ElevelDB didn't have the two configuration template files which rebar is awaiting.
This solves the issue:

```
curl https://raw.githubusercontent.com/basho/eleveldb/2.1.1/priv/eleveldb.schema > deps/eleveldb/priv/eleveldb.schema
curl https://raw.githubusercontent.com/basho/eleveldb/2.1.1/priv/eleveldb_multi.schema > deps/eleveldb/priv/eleveldb_multi.schema
```

The complete build now succeed but Riak is giving a nice Segmentation Fault.
