### ISSUE TITLE
Riak fails to start on Ubuntu/Debian

### ISSUE THREAD

**Issue by jburwell** [basho/riak#561]
Upon installing the Riak 2.0.0beta7 packages on Debian 7 and Ubuntu 12.04.4, Riak fails to start due to the following error:

``` shell
  root@riak-01:~# riak console
  config is OK
  -config /var/lib/riak/generated.configs/app.2014.06.17.14.30.16.config -args_file /var/lib/riak/generated.configs/vm.2014.06.17.14.30.16.args -vm_args /var/lib/riak/generated.configs/vm.2014.06.17.14.30.16.args
  Exec:  /usr/lib/riak/erts-5.10.3/bin/erlexec -boot /usr/lib/riak/releases/2.0.0beta7/riak               -config /var/lib/riak/generated.configs/app.2014.06.17.14.30.16.config -args_file /var/lib/riak/generated.configs/vm.2014.06.17.14.30.16.args -vm_args /var/lib/riak/generated.configs/vm.2014.06.17.14.30.16.args              -pa /usr/lib/riak/lib/basho-patches -- console
  Root: /usr/lib/riak
  {error_logger,{{2014,6,17},{14,30,17}},"Protocol: ~tp: the name riak@10.42.0.6 seems to be in use by another Erlang node",["inet_tcp"]}
  {error_logger,{{2014,6,17},{14,30,17}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.21.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.223>,<0.18.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,753}],[]]}
  {error_logger,{{2014,6,17},{14,30,17}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['riak@10.42.0.6',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
  {error_logger,{{2014,6,17},{14,30,17}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
  {error_logger,{{2014,6,17},{14,30,17}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,164}],[]]}
  {error_logger,{{2014,6,17},{14,30,17}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
  {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}
```

Adding -x to the shell directive of the /usr/sbin/riak script revealed the following error while attempting to start riak:

``` shell
  =ERROR REPORT==== 17-Jun-2014::16:54:24 ===
  Error when reading /var/lib/riak/.erlang.cookie: eaccesescript: exception error: no match of right hand side value
                   {error,
                       {{shutdown,
                            {failed_to_start_child,auth,
                                {"Error when reading /var/lib/riak/.erlang.cookie: eacces",
                                 [{auth,init_cookie,0,
                                      [{file,"auth.erl"},{line,285}]},
                                  {auth,init,1,[{file,"auth.erl"},{line,139}]},
                                  {gen_server,init_it,6,
                                      [{file,"gen_server.erl"},{line,304}]},
                                  {proc_lib,init_p_do_apply,3,
                                      [{file,"proc_lib.erl"},{line,239}]}]}}},
                        {child,undefined,net_sup_dynamic,
                            {erl_distribution,start_link,
                                [['riak_maint_9948@10.42.0.6',longnames]]},
                            permanent,1000,supervisor,
                            [erl_distribution]}}}
```

Following the failed start, the permissions of the files in /var/lib/riak are as follows:

``` shell
root@riak-01:~# ls -al /var/lib/riak
total 40
drwxrwxr-x  9 riak riak 4096 Jun 17 14:24 .
drwxr-xr-x 36 root root 4096 Jun 17 14:23 ..
drwxrwxr-x 66 riak riak 4096 Jun 17 14:24 anti_entropy
drwxrwxr-x 66 riak riak 4096 Jun 17 14:24 bitcask
drwxrwxr-x  3 riak riak 4096 Jun 17 14:23 cluster_meta
-r--------  1 root root   20 Jun 17 00:00 .erlang.cookie
drwxrwxr-x  2 riak riak 4096 Jun 17 18:37 generated.configs
drwxrwxr-x  2 riak riak 4096 Jun 17 14:24 kv_vnode
drwxrwxr-x  2 riak riak 4096 Jun 17 18:46 riak_kv_exchange_fsm
drwxr-xr-x  2 riak riak 4096 Jun 17 18:37 ring
```

It appears that Erlang process is being started as root, dropping the cookie with root:root ownership, before the Riak Erlang process start as riak -- preventing the Riak Erlang process from accessing the cookie.

A complete log of my investigate is captured in this [gist](https://gist.github.com/jburwell/d406326a1b128c9a7d8e).  It includes a Vagrantfile with a simple shell script provisioner that install the Ubuntu, Debian, and CentOS packages and attempts to start Riak.  These tests isolated the issue to Ubuntu/Debian.

During the course of investigating this issue, I also noticed that the [runner script](https://github.com/basho/node_package/blob/develop/priv/base/runner) swallows console output to a `MUTE` variable in a variety of places -- inhibiting debugging efforts.  As part of the fix, we should remove this variable and pipe stderr and stdout to a log file in /var/log/riak to provide complete visibility into the errors during startup/shutdown.

/cc @jaredmorrow @kellymclaughlin

**Comment by jburwell** [comment]
Debugging/investigation revealed that the [Ubuntu/Debian init.d script](https://github.com/basho/node_package/blob/develop/priv/templates/deb/init.script#L91) performs a ping before starting Riak.  In contrast, the [Red Hat init.d script](https://github.com/basho/node_package/blob/develop/priv/templates/rpm/rhel.init.script#L114) does not perform a ping on start.  The [runner:ping function](https://github.com/basho/node_package/blob/develop/priv/base/runner#L268) spins up a Erlang VM without dropping privileges -- causing the .erlang.cookie to be created with root:root ownership.  Adding a call to `boostrapd $@` to the runner:ping function fixes the issue.

I am now adding a Vagantfile to the riak project builds packages for a specified platform in order to test  the fix, and regression test affected functionality.

**Comment by jaredmorrow** [comment]
Honestly the easy solution is just removing that ping before `riak start`.  We don't want to add the `bootstrapd` function call to ping then you wouldn't be able to ping from a non-root or non-riak user.

**Comment by jaredmorrow** [comment]
@hectcastro I think removing that ping and just trying a start if it is already started is a reasonable method if we just plan to catch it.  Thoughts?

**Comment by jaredmorrow** [comment]
See https://github.com/basho/node_package/pull/145

**Comment by jburwell** [comment]
@jared I like the removal of the ping approach least invasive for 2.0 and consistent with the Red Hat behavior.  

I think it would be prudent to add a `env.sh:invoke_erl` function post-2.0 to properly drop permissions/manage execution across all of the scripts. If you agree, I will create a ticket for such a refactoring.

Finally, we also need to stop swallowing stderr/stdout output and redirect to a log.  Such a log would have literally saved me hours of debugging, and I imagine it would be same for our users and support.

**Comment by jburwell** [comment]
@jaredmorrow @hectcastro The solution we are considering will fix riak start on Ubuntu/Debian systems, but it doesn't protect against a misplaced ping wedging the permissions on the .erlang.cookie file.  Deleting the /var/lib/riak/.erlang.cookie file when the ping fails prevents the permissions from getting wedged while maintaining the non-root users to ping.  My thought is to add the following to the end of the [env.sh:ping_node function](https://github.com/basho/node_package/blob/develop/priv/base/env.sh#L135):

``` shell
     if [ "$?" -ne 0 ]; then
         rm -f $RUNNER_BASE_DIR/.erlang.cookie
    fi
```

The current user would have caused the file to be created, and thus would have the ability to delete it.  If the node is running, then we leave the .erlang.cookie file in place ensuring that we don't disturb the environment of the running node.

One issue: the rm call would override $? value relied upon by callers.  Therefore, this approach would need to be enhanced to preserve the return when the .erlang.cookie file is deleted.

**Comment by jburwell** [comment]
I think the [PR](https://github.com/basho/node_package/pull/145/files) submitted by @hectcastro to address this issue is better overall approach than the delete method I proposed above.  My suggestion  creates the potential of race condition if/when root is pinging a node while operations as the riak user need to be performed.  While the window for this race is very small, @hectcastro's PR avoids it entirely.  The only concern that I have is the removal of the other `$HOME` directory logic throughout the rest of the script.  I also wonder if it might not be better to check if the user executing the ping is root, and drop privileges in this circumstance in order to simplify/consolidate the execution logic.

/cc @jaredmorrow

**Comment by jburwell** [comment]
@hectcastro's [PR](https://github.com/basho/node_package/pull/145) needs to be closed since @jaredmorrow's [PR](https://github.com/basho/node_package/issues/146) has been selected to address this defect.

**Comment by jaredmorrow** [comment]
Fixed in https://github.com/basho/node_package/pull/146
