### ISSUE TITLE
erlang check too strong

### ISSUE THREAD

**Issue by darkchanter** [basho/riak#565]
Hi
I think you should check for an Erlang version >= x rather than = x.

In other words: I tried to 'make' Riak 1.4.9 on an Erlang version that is obviously too new:

ERROR: OTP release R16B01 does not match required regex R14B0[234]|R15
ERROR: compile failed while processing /home/roger/riak_src/riak-1.4.9/deps/node

Is there any way to supress this verification?

**Comment by darkchanter** [comment]
sorry I'm new to Github. Can't find the information of the merged bug or version tag to download. Where do I start?

**Comment by seancribbs** [comment]
We do not support Erlang/OTP R16 on the 1.4.x version of Riak. It's better to use a [packaged version](http://docs.basho.com/riak/latest/downloads/) of Riak for deployment or your local testing.

**Comment by darkchanter** [comment]
Actually I got my version from that page. I picked the Source since openSuSE isn't available there. Looks like 2.0.0 pre15 compiles, but I couldn't start dev1 yet
