### ISSUE TITLE
Crash 1 minute after starting [JIRA: RIAK-1642]

### ISSUE THREAD

**Issue by barcoyou** [basho/riak#581]
The Erlang version is R17 and the Riak is git cloned from the github master branch

2014-08-05 14:11:21.123 [info] <0.7.0> Application riak_control started on node 'riak@127.0.0.1'
2014-08-05 14:11:21.123 [info] <0.7.0> Application erlydtl started on node 'riak@127.0.0.1'
2014-08-05 14:11:21.136 [info] <0.7.0> Application riak_auth_mods started on node 'riak@127.0.0.1'
2014-08-05 14:11:30.551 [error] <0.1222.0> gen_fsm <0.1222.0> in state started terminated with reason: no function clause matc
hing riak_kv_vnode:terminate({{badmatch,{error,{1,file_io_server,invalid_unicode}}},[{riak_kv_vnode,init,1,[{file,"src/riak...
"},...]},...]}, undefined) line 1027
2014-08-05 14:11:30.551 [error] <0.1222.0> CRASH REPORT Process <0.1222.0> with 0 neighbours exited with reason: no function c
lause matching riak_kv_vnode:terminate({{badmatch,{error,{1,file_io_server,invalid_unicode}}},[{riak_kv_vnode,init,1,[{file,"s
rc/riak..."},...]},...]}, undefined) line 1027 in gen_fsm:terminate/7 line 598
2014-08-05 14:11:30.551 [error] <0.152.0> Supervisor riak_core_vnode_sup had child undefined started with {riak_core_vnode,sta
rt_link,undefined} at <0.1222.0> exit with reason no function clause matching riak_kv_vnode:terminate({{badmatch,{error,{1,fil
e_io_server,invalid_unicode}}},[{riak_kv_vnode,init,1,[{file,"src/riak..."},...]},...]}, undefined) line 1027 in context child
_terminated
2014-08-05 14:11:30.552 [error] <0.149.0> Supervisor riak_core_sup had child riak_core_vnode_manager started with riak_core_vn
ode_manager:start_link() at <0.181.0> exit with reason {{function_clause,[{riak_kv_vnode,terminate,[{{badmatch,{error,{1,file_
io_server,invalid_unicode}}},[{riak_kv_vnode,init,1,[{file,"src/riak_kv_vnode.erl"},{line,400}]},{riak_core_vnode,do_init,1,[{
file,"src/riak_core_vnode.erl"},{line,222}]},{riak_core_vnode,started,2,[{file,"src/riak_core_vnode.erl"},{line,205}]},{gen_fs
m,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},undefined]
,[{file,"src/riak_kv_vnode.erl"},{line,1027}]},...]},...} in context child_terminated
2014-08-05 14:11:35.824 [info] <0.408.0>@riak_kv_entropy_manager:perhaps_log_throttle_change:849 Changing AAE throttle from un
defined -> 0 msec/key, based on maximum vnode mailbox size 0 from 'riak@127.0.0.1'
2014-08-05 14:11:40.353 [error] <0.1542.0> gen_fsm <0.1542.0> in state started terminated with reason: no function clause matc
hing riak_kv_vnode:terminate({{badmatch,{error,{1,file_io_server,invalid_unicode}}},[{riak_kv_vnode,init,1,[{file,"src/riak...
"},...]},...]}, undefined) line 1027

**Comment by jrwest** [comment]
we do not support building with R17 at this time -- the error seems very related to the erlang version. closing.

**Comment by 5HT** [comment]
Just replace here
https://github.com/basho/riak_kv/blob/develop/src/riak_kv_vnode.erl#L1983
"~p" with "~tp"
and also update vnode status on any error not just enoent.
That will fix R17 vnode status updates.

**Comment by enewhuis** [comment]
@5HT it looks like the code in the development branch has changed since your suggestion.  I am having the same problem you did back then now also trying to hack together an R17 release.

@jrwest I realize this isn't supported but is there any info that might help me?

**Comment by cmeiklejohn** [comment]
While Riak should compile on Erlang 17 now, we're not officially supporting it until we release a Erlang 17-based Riak, which won't be our next immediate release, but should follow shortly after.

**Comment by 5HT** [comment]
you can you our version of riak: https://github.com/riak-synrc
this is production ready riak for erlang > 17.0

**Comment by enewhuis** [comment]
That is quite righteous of you, thanks!

**Comment by masudjbd** [comment]
# I'm having the following crash.log

2016-06-27 14:25:27 =ERROR REPORT====
*\* Generic server yz_solr_proc terminating 
*\* Last message in was {check_solr,0}
*\* When Server state == {state,"./data/yz",#Port<0.9350>,8093,8985}
*\* Reason for termination == 
*\* "solr didn't start in alloted time"
2016-06-27 14:25:27 =CRASH REPORT====
  crasher:
    initial call: yz_solr_proc:init/1
    pid: <0.581.0>
    registered_name: yz_solr_proc
    exception exit: {"solr didn't start in alloted time",[{gen_server,terminate,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [yz_solr_sup,yz_sup,<0.578.0>]
    messages: [{'EXIT',#Port<0.9350>,normal}]
    links: [<0.580.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 16181
  neighbours:
2016-06-27 14:25:27 =SUPERVISOR REPORT====
     Supervisor: {local,yz_solr_sup}
     Context:    child_terminated
     Reason:     "solr didn't start in alloted time"
     Offender:   [{pid,<0.581.0>},{name,yz_solr_proc},{mfargs,{yz_solr_proc,start_link,["./data/yz","./data/yz_temp",8093,8985]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2016-06-27 14:25:28 =ERROR REPORT====
*\* Generic server yz_solr_proc terminating 
*\* Last message in was {#Port<0.12213>,{exit_status,1}}
*\* When Server state == {state,"./data/yz",#Port<0.12213>,8093,8985}
*\* Reason for termination == 
*\* {"solr OS process exited",1}
2016-06-27 14:25:28 =CRASH REPORT====
  crasher:
    initial call: yz_solr_proc:init/1
    pid: <0.2339.0>
    registered_name: yz_solr_proc
    exception exit: {{"solr OS process exited",1},[{gen_server,terminate,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [yz_solr_sup,yz_sup,<0.578.0>]
    messages: [{'EXIT',#Port<0.12213>,normal}]
    links: [<0.580.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 9207
  neighbours:
2016-06-27 14:25:28 =SUPERVISOR REPORT====
     Supervisor: {local,yz_solr_sup}
     Context:    child_terminated
     Reason:     {"solr OS process exited",1}
     Offender:   [{pid,<0.2339.0>},{name,yz_solr_proc},{mfargs,{yz_solr_proc,start_link,["./data/yz","./data/yz_temp",8093,8985]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2016-06-27 14:25:28 =SUPERVISOR REPORT====
     Supervisor: {local,yz_solr_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.2339.0>},{name,yz_solr_proc},{mfargs,{yz_solr_proc,start_link,["./data/yz","./data/yz_temp",8093,8985]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2016-06-27 14:25:28 =SUPERVISOR REPORT====
     Supervisor: {local,yz_sup}
     Context:    child_terminated
     Reason:     shutdown
     Offender:   [{pid,<0.580.0>},{name,yz_solr_sup},{mfargs,{yz_solr_sup,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,supervisor}]

2016-06-27 14:25:28 =SUPERVISOR REPORT====
     Supervisor: {local,yz_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.580.0>},{name,yz_solr_sup},{mfargs,{yz_solr_sup,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,supervisor}]
