### ISSUE TITLE
Riak Upgrade ISSUE 

### ISSUE THREAD

**Issue by ashwinak08** [basho/riak#583]
![image](https://cloud.githubusercontent.com/assets/8417087/3876490/84a3adda-215c-11e4-992a-046d20fe347a.png)

after upgrading riak to 2.0 below is the error i am seeing any help please

**Comment by jrwest** [comment]
@ashwinak08 the [riak mailing list](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com) is a better place for your inquiry. There you can also attach the files in Riak's log directory, which will aid in debugging. You may want to try addressing the file limit (ulimit) warning and see if that resolves your issue first. 

I'm going to close this issue. Please email the mailing list if the issue persists.
