### ISSUE TITLE
No response to `rel/bin/riak version`

### ISSUE THREAD

**Issue by shalako** [basho/riak#599]
The documentation says this can be accomplished by running command-line tools. 

http://docs.basho.com/riak/latest/ops/running/tools/riak/#version

```
riak version
```

On the machine, this returns a blank line.
After a good amount of googling, I found that riak-admin status returned a version for riak_kv_version.

![screen shot 2014-09-19 at 3 46 25 pm](https://cloud.githubusercontent.com/assets/156568/4343259/5983a47e-4052-11e4-8fdf-15a64be8914d.png)

Seeing the same issue with Riak, Riak CS, and Stanchion

**Comment by shalako** [comment]
Looks like `rel/bin/riak version` simply calls `echo $APP_VERSION` and rel/lib/env.sh is supposed to set `APP_VERSION=` but isn't.

![screen shot 2014-09-19 at 4 35 19 pm](https://cloud.githubusercontent.com/assets/156568/4343402/aaea049a-4055-11e4-9c21-d67242aa2038.png)

**Comment by jaredmorrow** [comment]
If this was built from source, that setting doesn't get set.  This only gets set when packaged with 'make package'.

All builds from source will report an empty `riak version` string.

**Comment by shalako** [comment]
Thank you, Jared. We are building from source. We'll look into whether `make package` is an option.

Could you please tell me how to discover the running version of riak, riak cs, and stanchion in this case? Seems like there ought to be a more direct way to query the version than relying on an environment variable.

**Comment by shalako** [comment]
Also, even if `make package` is used, how could one environment variable `APP_VERSION` provide the version of both Riak and Riak CS? Latest compatible versions are Riak 1.4.10 and Riak CS 1.5.0. Even if APP_VERSION were set, it would be incorrect for one of these (Riak and Riak CS run on the same VMs).

**Comment by jaredmorrow** [comment]
If you are doing `make package`, both Riak and RiakCS will get their own
copy of the VM and have their own libraries.  So they will not share the
same VM or runner scripts.

**Comment by shalako** [comment]
Not sure I understand; will have to look into `make package` more. We expect Riak and Riak CS to run on the same VM. Doubling the number of VMs in a cluster seems unnecessary.

Regardless, could you please tell me how to discover the running version of Riak, Riak CS, and Stanchion when APP_VERSION is not set?

**Comment by jaredmorrow** [comment]
All erlang apps built with reltool build an erlang 'rel' which includes a small copy of the VM for the app to run on.  Making a proper self-contained package for each will ensure you can have different versions of libraries for each app, as well as possibly different Erlang VM versions.  This is a very common thing to do in the Erlang world http://www.erlang.org/doc/design_principles/release_structure.html

As far as how to get the Riak version if you don't have APP_VERSION set, the easiest way I can think of is to just use `riak-admin status` and parse the `riak_kv_version`.  I quickly did this and it worked fine from source 

```
./bin/riak-admin status | grep riak_kv_version | sed -e 's/.*<<"\(.*\)">>/\1/'
2.0.0
```

**Comment by jaredmorrow** [comment]
I'm closing this as this is part of the design and not at this time considered a bug.

**Comment by shalako** [comment]
Thank you, Jared. However `riak-admin status` only works for riak. There doesn't appear to be a similar solution for Riak CS or Stanchion.

**Comment by jaredmorrow** [comment]
Well when you build from source you can always just add the 'git describe --tags' version to the runner script as part of your build.
