### ISSUE TITLE
Enabling webmachine access logging causes crash

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#603]
See issue basho/webmachine#183

Mailing list threads:
http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-September/015962.html
http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-September/015986.html

**Comment by nickelization** [comment]
basho/webmachine#183 is now fixed, so I'm closing this issue as well.

**Comment by nickelization** [comment]
Oh, one more note to add though, to avoid any potential confusion....

The version of webmachine used in the develop branch of riak is currently 1.10.5, which doesn't yet include the necessary fix. Once a newer version of webmachine is added to riak, this will actually be fixed.
