### ISSUE TITLE
binary 2i ~broken on 1.4.4+ (~swapping/floating results) BUG [JIRA: RIAK-1604]

### ISSUE THREAD

**Issue by pigmej** [basho/riak#608]
Please consider this script:

```
# coding=utf-8
import random
import string

import riak

HOST = 'HOST_THERE'  # SET IT

print '*' * 30
print "One print for index - ok, more than one - not ok"
print '*' * 30

riak_client = riak.RiakClient(protocol='http', host=HOST, port=8098)


def rnd():
    return ''.join(random.choice(string.ascii_lowercase) for _ in xrange(10))


bucket_name = 'test_' + rnd()
print 'Bucket', bucket_name
bucket = riak_client.bucket(bucket_name)

print 'Test:'


def test_index(index_name):
    print '\ttest index', index_name
    for _ in xrange(50):
        bucket.new(str(rnd()), data={'x': 'x'}).add_index(index_name,
                                                          rnd()).store()
    last = set()
    for x in xrange(200):
        now = set(bucket.get_index(index_name, '0', 'z', max_results=2).results)
        if last != now:
            print '\t\t', last, '!=', now
            last = now


for i in xrange(10):
    test_index('test%d_bin' % i)

```
1. It creates binary index on random new records.
2. Then it queries 200 times that index.
3. It compares previous and current `results`
4. If it differs it prints the difference

If everything would be working correctly, you should have one print per bucket (the very first one), but instead you will probably have something like:

```
    test index test0_bin
        set([]) != set([u'okkgpuekov', u'refxjyjyvw'])
    test index test1_bin
        set([]) != set([u'xnpjzmwvee', u'xlsbrychnh'])
        set([u'xnpjzmwvee', u'xlsbrychnh']) != set([u'xlsbrychnh', u'ejoaebbwrz'])
        set([u'xlsbrychnh', u'ejoaebbwrz']) != set([u'xnpjzmwvee', u'xlsbrychnh'])
    test index test2_bin
        set([]) != set([u'cnrhelxudj', u'dgmwrkbvtw'])
    test index test3_bin
        set([]) != set([u'xrnbcxrtux', u'bysybrdeux'])
    test index test4_bin
        set([]) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])
        set([u'vaxdnrkqpg', u'atthrbuese']) != set([u'oudbvnrrpn', u'atthrbuese'])
        set([u'oudbvnrrpn', u'atthrbuese']) != set([u'vaxdnrkqpg', u'atthrbuese'])

```

on `test0_bin`, `test3_bin`, `test2_bin` everything is fine. 

**However on `test2_bin` and `test4_bin` you can easily see results floating.**

Default setup with leveldb backend.

That script works prefectly fine on riak 1.4.x

**Comment by joecaswell** [comment]
The 2I results seem to be returning incorrectly when small numbers are used for max_results.  Testing this with curl https://gist.github.com/joecaswell/ed2d095a90cece5751fa, 7 seems to be the magic number for this instance where the results become stable.  Smaller result sets intermittently miss some terms.

**Comment by pigmej** [comment]
So @joecaswell, I assume that the bug is confirmed ?

Thanks for poiting about _magic 7 number_. I can resolve some testing issues with client side fix for it.

**Comment by russelldb** [comment]
I started looking into this a bit, and found that using these two scripts https://gist.github.com/russelldb/90db1a31a4aaeb30d6cb there is a non-deterministic result from at least 1.4.8 up (will try earlier versions too)

I think I'd rather look at fixing that first, and see if it isn't the cause of the above too.

**Comment by pigmej** [comment]
As we talked, I can confirm that your script is doing similar thing, it's the same problem. 1.4.2 is fine.

**Comment by russelldb** [comment]
Yeah, for the record, 1.4.2 does not show the issue from my scripts, but 1.4.4 does. I can't find a 1.4.3 release. So I'll start looking at commits next.

**Comment by shino** [comment]
I'm digging the same symptom (but originated from riak_cs) with riak 1.4 branch.
Not yet find the root cause, just a interim memo.

With single node cluster with ring size 16.
Added the following print debug to `riak_core_coverage_fsm`:

```
diff --git a/src/riak_core_coverage_fsm.erl b/src/riak_core_coverage_fsm.erl
index cd648bb..24dea91 100644
--- a/src/riak_core_coverage_fsm.erl
+++ b/src/riak_core_coverage_fsm.erl
@@ -243,6 +243,12 @@ waiting_results({{ReqId, VNode}, Results},
                                  req_id=ReqId,
                                  timeout=Timeout,
                                  process_fun = ProcessFun}) ->
+case VNode of
+    {1004782375664995756265033322492444576013453623296, 'dev1@127.0.0.1'} ->
+        lager:log(warning, self(), "********** waiting_results: ~p~n", [Results]),
+        ok;
+    _ -> ok
+end,
     case ProcessFun(VNode, Results, ModState) of
         {ok, UpdModState} ->
             UpdStateData = StateData#state{mod_state=UpdModState},
```

Then, not always, the log reports duplicated key (`<<"1415092978_118">>` for this case)
 by executing a streaming 2i request:

```
10:19:07.565 [warning] ********** waiting_results: {{<0.857.0>,#Ref<0.0.0.28237>},<<"riak-cs-gc">>,[<<"1415092979_102">>,<<"1415092978_118">>]}
10:19:07.566 [warning] ********** waiting_results: {{<0.857.0>,#Ref<0.0.0.28238>},<<"riak-cs-gc">>,[<<"1415092978_118">>]}
```

This seems to break the assumption by `riak_kv_index_fsm` that keys should be orderd.
So `riak_kv_index_fsm` and `sms` does not work correctly.

**Comment by russelldb** [comment]
I think we have it. Looks like an off by one somewhere between the fold and the FSM. I have a hack fix that passes my script test. Should have updated the issue last night, sorry.
On 6 Nov 2014 01:28, Shunichi Shinohara notifications@github.com wrote:I'm digging the same symptom (but originated from riak_cs) with riak 1.4 branch.
Not yet find the root cause, just a interim memo.

With single node cluster with ring size 16.
Added the following print debug to riak_core_coverage_fsm:

diff --git a/src/riak_core_coverage_fsm.erl b/src/riak_core_coverage_fsm.erl
index cd648bb..24dea91 100644
--- a/src/riak_core_coverage_fsm.erl
+++ b/src/riak_core_coverage_fsm.erl
@@ -243,6 +243,12 @@ waiting_results({{ReqId, VNode}, Results},
                                  req_id=ReqId,
                                  timeout=Timeout,
                                  process_fun = ProcessFun}) ->
+case VNode of
-    {1004782375664995756265033322492444576013453623296, 'dev1@127.0.0.1'} ->
-        lager:log(warning, self(), "*********\* waiting_results: ~p~n", [Results]),
-        ok;
-    _ -> ok
  +end,
   case ProcessFun(VNode, Results, ModState) of
       {ok, UpdModState} ->
           UpdStateData = StateData#state{mod_state=UpdModState},

Then, not always, the log reports duplicated key:

10:19:07.565 [warning] *********\* waiting_results: {{<0.857.0>,#Ref<0.0.0.28237>},<<"riak-cs-gc">>,[<<"1415092979_102">>,<<"1415092978_118">>]}
10:19:07.566 [warning] *********\* waiting_results: {{<0.857.0>,#Ref<0.0.0.28238>},<<"riak-cs-gc">>,[<<"1415092978_118">>]}

This seems to break the assumption by riak_kv_index_fsm that keys should be orderd.
So riak_kv_index_fsm and sms does not work correctly.

**Comment by pigmej** [comment]
Russell, I can test your patch about 9am CET.

-----Original Message-----

**Comment by shino** [comment]
Thank you for update. It may be same or may be not, please let me add
my memo of digging around.

My case:
- index is `$key`
- paginated 2i with max_results=2

It seems for me that the point is accumulator (buffer) treatment in
`stoppable_fold` of `riak_kv_eleveldb_backend` [1].  By calling
`Fun(...)`, the inside buffer (`riak_kv_fold_buffer`) is updated, but
the exeption (`throw(stop_fold)`) can be thrown and the updated buffer
is lost in catch clause. Then previous accumulator (buffer) is sent by
`FinishFun`.

call / message sequence:
- `Acc` is a buffer used in `stoppable_fold`
- only one vnode worker is written for simplicity

```
| index fsm                | Acc = buffer (size=2) | vnode worker        |
|--------------------------+-----------------------+---------------------|
|                          |                       | push k1 to buffer   |
|                          | [k1]                  |                     |
|                          |                       | push k2 to buffer   |
|                          | Fun(k2, [k1])         |                     |
|                          | <- ! [k1, k2]         |                     |
| process_results([k1,k2]) |                       |                     |
| [the vnode suffices      |                       |                     |
|  max_results]            |                       |                     |
| -> ! stop_fold           |                       |                     |
|                          | throw(stop_fold)      |                     |
|                          | (in riak_kv_vnode:    |                     |
|                          |  result_fun_ack/2)    |                     |
|                          |                       | FinishFun([k1])     |
|                          |                       | (flush buffer [k1]) |
| process_results([k1])    |                       |                     |
```

[1] https://github.com/basho/riak_kv/blob/1.4/src/riak_kv_eleveldb_backend.erl#L798

**Comment by pigmej** [comment]
@russelldb a check that you gave to me (this is not a fix, just for testing):

```
diff --git src/riak_kv_vnode.erl src/riak_kv_vnode.erl
index ec97036..9403cdb 100644
--- src/riak_kv_vnode.erl
+++ src/riak_kv_vnode.erl
@@ -830,9 +830,9 @@ prepare_index_query(Q) ->
 %% @doc Batch size for results is set to 2i max_results if that is less
 %% than the default size. Without this the vnode may send back to the FSM
 %% more items than could ever be sent back to the client.
-buffer_size_for_index_query(#riak_kv_index_v3{max_results=N}, DefaultSize)
-  when is_integer(N), N < DefaultSize ->
-    N;
+%% buffer_size_for_index_query(#riak_kv_index_v3{max_results=N}, DefaultSize)
+%%   when is_integer(N), N < DefaultSize ->
+%%     N;
 buffer_size_for_index_query(_Q, DefaultSize) ->
     DefaultSize.
```

solves this on 2.0.1.

@shino you can probably try to apply the same for 1.4.4+ series to confirm that it's the same problem. 

**Above patch is NOT a fix**

**Comment by seancribbs** [comment]
@Basho-JIRA ping

**Comment by shino** [comment]
I think this is fixed by https://github.com/basho/riak_kv/pull/1155
