### ISSUE TITLE
Don't include SSL private keys in riak-debug

### ISSUE THREAD

**Issue by runesl** [basho/riak#610]
Currently, the output of the riak-debug command includes everything from riak's etc dir, which usually includes the private ssl-key key.pem.
ssl keys are seldom needed for debugging, and when they are, they can be manually retrieved then.
We can avoid spreading private keys unnecessarily by making sure that no `*.pem`-files are included in riak-debug output when it dumps the etc dir.
https://github.com/basho/riak/blob/develop/rel/files/riak-debug

**Comment by macintux** [comment]
Thanks for raising the issue.

I'm not sure `.pem` is sufficient; there are other common certificate extensions to watch out for (http://blogs.msdn.com/b/kaushal/archive/2010/11/05/ssl-certificates.aspx via a quick search looks useful).

**Comment by pyrrho** [comment]
Two pull requests that relate to this, #676 will add this functionality to the 2.0 branch and #678 will add it to the 1.4 brach.
Currently, the extensions that will (by default) be ignored are `.pfx`, `.p12`, `.csr`, `.sst`, `.sto`, `.stl`, `.pem`, and `.key`.

**Comment by pyrrho** [comment]
As the above PRs have been merged, I'm going to go ahead and close this issue. Feel free to reopen if there's more to discuss.
