### ISSUE TITLE
Installing Riak 2.0.1 on Debian 7.0

### ISSUE THREAD

**Issue by davidx** [basho/riak#616]
Installing Riak 2.0.1 on Debian 7.0 results in unusable state of scripts and confusing error message.
Thanks!

root@ip-10-202-157-207:~# cat /etc/issue
Debian GNU/Linux 7.0 \n \l

root@ip-10-202-157-207:~# ls
riak_2.0.1-1_amd64.deb

root@ip-10-202-157-207:~# dpkg -i riak_2.0.1-1_amd64.deb 
Selecting previously unselected package riak.
(Reading database ... 15994 files and directories currently installed.)
Unpacking riak (from riak_2.0.1-1_amd64.deb) ...
Setting up riak (2.0.1-1) ...
Installing new version of config file /etc/init.d/riak ...
Processing triggers for man-db ...

root@ip-10-202-157-207:~# /etc/init.d/riak start
/usr/sbin/riak: 1: ulimit: error setting limit (Operation not permitted)
!!!!
!!!! WARNING: ulimit -n is 65336; 65536 is the recommended minimum.
!!!!
/usr/sbin/riak: 323: [: Other:: unexpected operator
/usr/sbin/riak: 323: [: Illegal number: Other: ["-kernel","net_ticktime","10","getpid"]
Usage: nodetool {ping|stop|restart|reboot|chkconfig}

root@ip-10-202-157-207:~# riak ping
/usr/sbin/riak: 1: ulimit: error setting limit (Operation not permitted)
Other: ["-kernel","net_ticktime","10","ping"]
Usage: nodetool {ping|stop|restart|reboot|chkconfig}

root@ip-10-202-157-207:~# riak-admin status
Other: ["-kernel","net_ticktime","10","rpc","riak_kv_console","status"]
Usage: nodetool {ping|stop|restart|reboot|chkconfig}

root@ip-10-202-157-207:~# nodetool
bash: nodetool: command not found

root@ip-10-202-157-207:~# riak-admin
Usage: riak-admin { cluster | join | leave | backup | restore | test | 
                    reip | js-reload | erl-reload | wait-for-service | 
                    ringready | transfers | force-remove | down |
                    cluster-info | member-status | ring-status | vnode-status |
                    aae-status | diag | status | transfer-limit | reformat-indexes |
                    top [-interval N] [-sort reductions|memory|msg_q] [-lines N] |
                    downgrade-objects | security | bucket-type | repair-2i |
                    search | services | ensemble-status }
root@ip-10-202-157-207:~# riak-admin test
Successfully completed 1 read/write cycle to 'riak@10.202.157.207'

root@ip-10-202-157-207:~# riak-debug
.............................................. /root/riak@10.202.157.207-riak-debug.tar.gz
root@ip-10-202-157-207:~# riak-admin member_status
Other: ["-kernel","net_ticktime","10","rpc","riak_core_console",
        "member_status"]
Usage: nodetool {ping|stop|restart|reboot|chkconfig}
root@ip-10-202-157-207:~#

**Comment by seancribbs** [comment]
This resolved by basho/node_package#170 and will be fixed in 2.0.3.
