### ISSUE TITLE
Can't achieve to have a perfect consistancy

### ISSUE THREAD

**Issue by Quentin01** [basho/riak#617]
We use 4 differents physical servers, each hosting a Riak node (v1.4.10).
We're connecting using riak-js lib with Node.js.

Our buckets configuration is :

```
{default_bucket_props, [
  {n_val, 3 },
  {r, 2 },
  {w, 2 },
  {last_write_wins, true}
]}
```

We want to store some serialized JSON data, with the ability to update documents (re-send the whole JSON) or get them. Our request will be randomly sent to each node (we will send some data on a node then get those data on another node just after).

We do not want to get some old values, the Riak's consistancy has to be perfect and we believe it shoud be achieved with the previous configuration.

Here is the log (these request can be sent with 20 ms between them):

```
PUT /buckets/bucket_name/keys/key (We create our data for the first time)
PUT /buckets/bucket_name/keys/key (We update them)
GET /buckets/bucket_name/keys/key (We get them)
```

Don't forget that we randomly ping one of our four Riak nodes for each request.

In this case, when we get the data, riak respond with the first data or the second data, randomly. This is specifically what we don't want :(
In every case, we want to get the latest value.

Is there something wrong with our config ? Is it simply impossible ?

PS: If we send our request to a single node, we always get the latest value.

We also tried with these buckets params, without any success:

```
{default_bucket_props, [
  {n_val, 3 },
  {r, 2 },
  {pr, 2 },
  {dw, 2 },
  {w, 2 },
  {pw, 2 },
  {allow_mult, false},
  {last_write_wins, true}
]}
```

**Comment by seancribbs** [comment]
Configuration of buckets is insufficient to get "perfect consistency" (which seems to mean "recency" in your case). What you want is [Strong Consistency](http://docs.basho.com/riak/latest/dev/advanced/strong-consistency/).

**Comment by Quentin01** [comment]
This link is for Riak 2.0, but we use Riak 1.X :(
Is there a similar option / configuration in Riak 1.X?

**Comment by seancribbs** [comment]
No, this functionality is not in 1.x. 

Your other option is to refetch if the expected value is not received, or turn on the "return body" option that replies to writes with the updated value. There is a probabilistic bound on the staleness of any item, so simply refetching the item may work. However, there is no guarantee that you will read your own writes and sessions are not sticky.

If you cannot tolerate eventual consistency in its essential behavior, maybe Riak is not a good fit. Alternately, you can upgrade to 2.0 for those items that specifically cannot tolerate staleness. For the rest of your data that doesn't need strong recency, regular eventually-consistent Riak might still work for you.

**Comment by Quentin01** [comment]
Thank you for your reply, I will use this informations.
