### ISSUE TITLE
ring_size in configuration not working

### ISSUE THREAD

**Issue by sandeepbisht** [basho/riak#660]
I set up 

ring_size=16

But when i checking it using

**1** --> _riak-admin status|grep -i ring i got following output_

ring_members : ['riak@10.20.2.180','riak@10.20.2.182']
ring_num_partitions : 64
ring_ownership : <<"[{'riak@10.20.2.180',32},{'riak@10.20.2.182',32}]">>
ring_creation_size : 16

**2** --> riak control  -  it is showing 64 partitions (As per looking into https://10.20.2.180:8069/admin/#/ring)

**Comment by seancribbs** [comment]
If you started the node before changing the ring_size, it will be already persisted to disk. Stop all the nodes, remove `/var/lib/riak/ring` (assuming a Linux install), ensure the ring_size is set correctly on both nodes, and then restart and rejoin.

**Comment by sandeepbisht** [comment]
Thank you it works.

But is it needed to remove /var/lib/riak/ring if some changes made in riak.conf related to ring_size ?

Because till now changes on riak.conf automatically reflected.It not needed manual deletion.Whenever i have to modify riak.conf.I modify it  on all nodes and restart all nodes.Change reflected.
