### ISSUE TITLE
Regression in dealing with bad PB message data.

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#666]
In Riak 1.4.X, you can send a `RpbPutReq` while leaving the `bucket` field set to NULL and Riak will return an error.

In Riak 2.0.X, doing that results in this crash and the connection is unexpectedly aborted:

```
2015-01-15 12:18:31.199 [error] <0.7068.0> CRASH REPORT Process <0.7068.0> with 1 neighbours exited with reason: bad argument in call to erlang:size(undefined) in riak_kv_bitcask_backend:make_bk/3 line 132 in gen_fsm:terminate/7 line 622
```

I will add code to the C# client to disallow this scenario (the Ruby client disallows null or empty bucket names).

**Comment by seancribbs** [comment]
That should not be possible if you are following the protobufs spec, the `bucket` field is marked `required`.

**Comment by lukebakken** [comment]
Unfortunately, the C# protobuf library doesn't throw exceptions when required data is missing (https://code.google.com/p/protobuf-net/issues/detail?id=262).

**Comment by Basho-JIRA** [comment]
Fix version and PR removed since not related per Doug. 

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment]
Something was fixed in the .net client, not here /Riak 

**_[posted via JIRA by Patricia Brewer]**_
