### ISSUE TITLE
Compiling  error  error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token  

### ISSUE THREAD

**Issue by molele2** [basho/riak#671]
Install riask 2.0.1 2.0.2 2.0.3 on centos6 ,hava some probolem ,I use erlang 16B03

/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:36:31: error: security/pam_appl.h: No such file or directory
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:38: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:42: warning: ‘struct pam_response’ declared inside parameter list
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:42: warning: ‘struct pam_message’ declared inside parameter list
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c: In function ‘conv_fun’:
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:46: error: ‘PAM_MAX_NUM_MSG’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:46: error: (Each undeclared identifier is reported only once
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:46: error: for each function it appears in.)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:50: error: ‘PAM_CONV_ERR’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:53: error: invalid application of ‘sizeof’ to incomplete type ‘struct pam_response’
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:54: error: ‘PAM_BUF_ERR’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:58: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:65: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:66: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:68: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:69: error: ‘PAM_PROMPT_ECHO_OFF’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:72: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:73: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:75: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:78: error: ‘PAM_ERROR_MSG’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:80: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:83: error: ‘PAM_TEXT_INFO’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:85: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:88: error: ‘PAM_PROMPT_ECHO_ON’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:90: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:95: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:99: error: increment of pointer to unknown structure
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:99: error: arithmetic on pointer to an incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:100: error: increment of pointer to unknown structure
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:100: error: arithmetic on pointer to an incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:102: error: ‘PAM_SUCCESS’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:106: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:108: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:108: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:109: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:111: error: increment of pointer to unknown structure
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:111: error: arithmetic on pointer to an incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:114: error: dereferencing pointer to incomplete type
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c: In function ‘main’:
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:171: error: invalid use of undefined type ‘struct pam_conv’
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:172: error: invalid use of undefined type ‘struct pam_conv’
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:176: warning: implicit declaration of function ‘pam_start’
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:176: error: ‘pamh’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:177: error: ‘PAM_SUCCESS’ undeclared (first use in this function)
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:190: warning: implicit declaration of function ‘pam_authenticate’
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:196: warning: implicit declaration of function ‘pam_acct_mgmt’
/riak/riak-riak-2.0.1/deps/canola/c_src/canola-port.c:209: warning: implicit declaration of function ‘pam_end’
ERROR: compile failed while processing /riak/riak-riak-2.0.1/deps/canola: rebar_abort
make: *_\* [compile] Error 1

**Comment by molele2** [comment]
no  boy  ansow my problem?The  project is dead ???????

**Comment by kesslerm** [comment]
Hi molele2,

I can assure you that the riak project is very much alive. Riak has been created by basho (http://www.basho.com) and is actively maintained and developed further by this company.

Regarding your issue, I note that the very first error relates to a missing header file. Please make sure that you install the development packages for your system. In particular you will want to have the pam-dev package.

Hope this helps.

Regards,

Magnus Kessler

Basho Client Services Engineer

**Comment by molele2** [comment]
Hi kesslerm ,I try use this project to my new case,But not intall from network,So,  I assumed it was dead,I feel so  sorry, But I hope the project was strong ,Becase I plan to develop new case  for my boss,Thanks for your  support
