### ISSUE TITLE
Editing Never compiler success, it seems that I give up riak

### ISSUE THREAD

**Issue by molele2** [basho/riak#674]
Compiling /riak/riak-develop/deps/canola/c_src/canola-port.c /riak/riak-develop/deps/canola/c_src/canola-port.c:36:31: error: security/pam_ap pl.h: No such file or directory /riak/riak-develop/deps/canola/c_src/canola-port.c:38: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘attribute’ before ‘’ token /riak/riak-develop/deps/canola/c_src/canola-port.c:42: warning: ‘struct pam_resp onse’ declared inside parameter list /riak/riak-develop/deps/canola/c_src/canola-port.c:42: warning: ‘struct pam_mess age’ declared inside parameter list /riak/riak-develop/deps/canola/c_src/canola-port.c: In function ‘conv_fun’: /riak/riak-develop/deps/canola/c_src/canola-port.c:46: error: ‘PAM_MAX_NUM_MSG’ undeclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:46: error: (Each undeclared i dentifier is reported only once /riak/riak-develop/deps/canola/c_src/canola-port.c:46: error: for each function it appears in.) /riak/riak-develop/deps/canola/c_src/canola-port.c:50: error: ‘PAM_CONV_ERR’ und eclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:53: error: invalid applicatio n of ‘sizeof’ to incomplete type ‘struct pam_response’ /riak/riak-develop/deps/canola/c_src/canola-port.c:54: error: ‘PAM_BUF_ERR’ unde clared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:58: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:65: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:66: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:68: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:69: error: ‘PAM_PROMPT_ECHO_O FF’ undeclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:72: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:73: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:75: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:78: error: ‘PAM_ERROR_MSG’ un declared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:80: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:83: error: ‘PAM_TEXT_INFO’ un declared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:85: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:88: error: ‘PAM_PROMPT_ECHO_O N’ undeclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:90: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:95: error: dereferencing poin ter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:99: error: increment of point er to unknown structure /riak/riak-develop/deps/canola/c_src/canola-port.c:99: error: arithmetic on poin ter to an incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:100: error: increment of poin ter to unknown structure /riak/riak-develop/deps/canola/c_src/canola-port.c:100: error: arithmetic on poi nter to an incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:102: error: ‘PAM_SUCCESS’ und eclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:106: error: dereferencing poi nter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:108: error: dereferencing poi nter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:108: error: dereferencing poi nter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:109: error: dereferencing poi nter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:111: error: increment of poin ter to unknown structure /riak/riak-develop/deps/canola/c_src/canola-port.c:111: error: arithmetic on poi nter to an incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c:114: error: dereferencing poi nter to incomplete type /riak/riak-develop/deps/canola/c_src/canola-port.c: In function ‘main’: /riak/riak-develop/deps/canola/c_src/canola-port.c:171: error: invalid use of un defined type ‘struct pam_conv’ /riak/riak-develop/deps/canola/c_src/canola-port.c:172: error: invalid use of un defined type ‘struct pam_conv’ /riak/riak-develop/deps/canola/c_src/canola-port.c:176: warning: implicit declar ation of function ‘pam_start’ /riak/riak-develop/deps/canola/c_src/canola-port.c:176: error: ‘pamh’ undeclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:177: error: ‘PAM_SUCCESS’ und eclared (first use in this function) /riak/riak-develop/deps/canola/c_src/canola-port.c:190: warning: implicit declar ation of function ‘pam_authenticate’ /riak/riak-develop/deps/canola/c_src/canola-port.c:196: warning: implicit declar ation of function ‘pam_acct_mgmt’ /riak/riak-develop/deps/canola/c_src/canola-port.c:209: warning: implicit declar ation of function ‘pam_end’ ERROR: compile failed while processing /riak/riak-develop/deps/canola: rebar_abo rt make: *\* [compile] Error 1

**Comment by molele2** [comment]
ERlang 16B   centos6.5  64 riak-develop .2.0.3,2.0.4,2.0.2 no a way

**Comment by seancribbs** [comment]
We have binary packages for CentOS 6. Please use those to install Riak.

On Thu, Jan 29, 2015 at 10:21 PM, molele2 notifications@github.com wrote:

> ERlang 16B centos6.5 64 riak-develop .2.0.3,2.0.4,2.0.2 no a way
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak/issues/674#issuecomment-72159433.

## 

Sean Cribbs sean@basho.com
Sr. Software Engineer
Basho Technologies, Inc.
http://basho.com/

**Comment by kesslerm** [comment]
Hi molele2,

As already advised on #671 and #672, you have to have the development packages available for your system. You don't seem to have the necessary header files for 'pam' installed. According to http://www.rpmseek.com/rpm-pl/pam-devel.html?hl=com&cx=0:: for CentOS 6 you need pam-devel-1.1.1. I don't have that version of CentOS available to me to verify this exact version.

Unless you make sure you have the necessary header files in place you will never be able to compile Riak from source.

But as Sean advised, you can also download Basho's pre-compiled binary packages.

For a successful installation of Riak on CentOS, please follow the instructions on http://docs.basho.com/riak/latest/ops/building/installing/rhel-centos/

Regards,

Magnus

Customer Services Engineer @ Basho
