### ISSUE TITLE
Starting Riak 2.0.1 and 2.0.4 on Debian 8 [JIRA: RIAK-1740]

### ISSUE THREAD

**Issue by khauser** [basho/riak#675]
Hello, I'm having a problem installing riak:

root@eis-staging:/tmp# dpkg -i riak_2.0.4-1_amd64.deb 
(Reading database ... 44718 files and directories currently installed.)
Preparing to unpack riak_2.0.4-1_amd64.deb ...
Unpacking riak (2.0.4-1) over (2.0.4-1) ...
Setting up riak (2.0.4-1) ...
Processing triggers for man-db (2.7.0.2-3) ...
root@eis-staging:/tmp# riak start
root@eis-staging:/tmp# riak stop
ok
root@eis-staging:/tmp# /etc/init.d/riak start
[....] Starting riak (via systemctl): riak.serviceFailed to start riak.service: Unit riak.service failed to load: No such fil
e or directory.
 failed!

**Comment by kayabendroth-epages** [comment]
@khauser Can you update the summary to something like: Starting Riak on Debian 8 fails?

**Comment by khauser** [comment]
fixed in 2.1.0
