### ISSUE TITLE
Riak Control broken on develop [JIRA: RIAK-1507]

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak#680]
Riak Control is currently broken on develop:

```
15:28:37.764 [error] CRASH REPORT Process <0.346.0> with 0 neighbours crashed with reason: no case clause matching {ok,{http_error,[22,3,1,1,12,1,0,1,8,3,3,242,46,30,166,250,196,214,120,239,20,111,221,78,112,161,48,84,218,131,144,228,141,143,109,165,165,151,110,107,133,227,59,0,0,118,192,48,192,44,192,40,192,36,192,20,192,10]},<<>>} in mochiweb_http:request/3 line 107
```

**Comment by cmeiklejohn** [comment]
Now that everything's been merged up and the dependencies resolved, this is no longer an issue.

**Comment by Basho-JIRA** [comment]
This was fixed this weekend. 

**_[posted via JIRA by Chris Meiklejohn]**_

**Comment by Basho-JIRA** [comment]
This was assigned to me, but I just pulled the latest version of Riak EE and it appears to be working just fine? 

**_[posted via JIRA by Chris Meiklejohn]**_
