### ISSUE TITLE
Cross-Origin Resource Sharing    about riak

### ISSUE THREAD

**Issue by xiaoliuliu2050** [basho/riak#694]
recently i am using riak and riak cs ,
and i happend to a problem ,
that is i want to upload a file directly to my database ,
but the brower has a problem ,you know it is Cross-Origin Resource Sharing,
i am here to ask help ,
how should i solve this problem ?

**Comment by kuenishi** [comment]
Riak will not support CORS and may be this is about CS S3 API.
