### ISSUE TITLE
I want to know which one to use on riak 2.0.5 for java lib client

### ISSUE THREAD

**Issue by molele2** [basho/riak#702]
Do you know ,tell me please.Thanks very much

**Comment by molele2** [comment]
Which 2.0?Which 1.4 ?

**Comment by kesslerm** [comment]
Hi @molele2,

The github issue tracker is not a support forum. Please subscribe to our public mailing list. Instructions to do this are available at http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com

That said, you should use version 2.0 of the [riak-java-client](https://github.com/basho/riak-java-client/tree/riak-client-2.0.0) with Riak-2.0.x.

I hope to see your further questions on the mailing list and will be happy to answer them there.

Regards,

Magnus
