### ISSUE TITLE
FreeBSD Port databases/riak 2.0.5 [JIRA: RIAK-1578]

### ISSUE THREAD

**Issue by nbari** [basho/riak#704]
I created a patch for the FreeBSD port databases/riak https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198355

So far working but would be nice if more experienced users could test it.

**Comment by nbari** [comment]
Cleaned and updated the patch: https://bz-attachments.freebsd.org/attachment.cgi?id=153931

New patch to avoid the BASH dependecy :   https://github.com/basho/yokozuna/issues/461

```
==> yokozuna (compile)
env: bash: No such file or directory
ERROR: Command [compile] failed!
```

https://bz-attachments.freebsd.org/attachment.cgi?id=153981

To install it, update the [FreeBDS](https://www.freebsd.org/doc/en/books/handbook/ports-using.html) ports:

```
# portsnap fetch extract
# portsnap fetch update
```

Patch current riak port:

```
# cd /usr/ports/databases/riak
# patch -E -p1 < /path/to/riak.diff 
# find . -name "*.orig" -exec rm -f {} \;
```

Install, create package:

```
# make install
# make package
```

**Comment by nbari** [comment]
New patch passing poudriere testport:  https://bz-attachments.freebsd.org/attachment.cgi?id=154128

Is there a way to avoid solr / yokozuna when compiling ? 

It would be nice to have yokozuna as an extension rather than a dependency while compiling

**Comment by nbari** [comment]
New patch removing yokozuna: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=154161

A second port could be created to include yokozuna, mainly because of the solr dependency

**Comment by nbari** [comment]
Maybe a good idea to have a riak2 port so that both 1.4.x and 2.0.x are available. 

For riak 2 (2.0.5) I created this shar file: https://bz-attachments.freebsd.org/attachment.cgi?id=154212 https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198517 

To use (in FreeBSD):

```
# fetch "https://bz-attachments.freebsd.org/attachment.cgi?id=154212" -o /tmp/riak2.shar
# cd /usr/ports/databases
# sh /tmp/riak2.shar
# cd /usr/ports/databases/riak2
# make install 
```

**Comment by nbari** [comment]
I created a port: [lang/riak-erlang](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198656) to compile riak using Bashio's custom erlang port:

To use:

```
# fetch "https://bz-attachments.freebsd.org/attachment.cgi?id=154452" -o /tmp/riak-erlang.sh
# fetch "https://bz-attachments.freebsd.org/attachment.cgi?id=154455" -o /tmp/riak2.sh
# cd /usr/ports/lang
# sh /tmp/riak-erlang.sh
# cd /usr/ports/databases
# sh /tmp/riak2.sh
# cd /usr/ports/databases/riak2
# make install 
```

**Comment by seancribbs** [comment]
@Basho-JIRA ping

**Comment by nbari** [comment]
Hi, I am currently testing port, software and so far working as expected, I am just waiting feedback from FreeBSD guys to see if they can accept the port.

**Comment by sdebnath** [comment]
@nbari removing yokozuna disables all of search 2.0 which is critical in riak 2.0+

**Comment by nbari** [comment]
Hi, new port depending on lang/riak-erlang includes yokozuna, in one patch I disable it just to try to pass the ports rules, but I agree that disabling it removes all search stuff, therefore I put them back, basically my last port should compile as bashio recomends.

**Comment by nbari** [comment]
I tried my best, but I think the port wont be accepted by the FreeBSD committers, more details here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198517#c15 https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198656#c18

Anyway the port compiles and work nice, just in case someone interested or want to use with tools like poudriere.

Maybe the only way is to create another port than just install basho's binaries as suggested, but well problem here is that you don´t know if it will crash or if it will perfectly fit your architecture, since is more difficult to trust talking in term of stability, compiling, build, etc etc.

**Comment by william-gr** [comment]
I have committed databases/riak2 and lang/erlang-riak yesterday to FreeBSD ports tree, I'll be adding stanchion and riak-cs today.

**Comment by nbari** [comment]
http://www.freshports.org/databases/riak2/

Many thanks
