### ISSUE TITLE
one node manages multiple disks? [JIRA: RIAK-1602]

### ISSUE THREAD

**Issue by pingyym** [basho/riak#706]
it looks like that one node of riak only can manager one disk(the node's data is only can be wrote to the  directory is Configured ).if one server has four disks, i need to open four nodes to make full use of disks? why not go to implement the feature that on node can manage multiple disks?

**Comment by seancribbs** [comment]
It is something we have discussed internally in the past (we called them "storage zones"), however isn't this something generally better handled by your volume manager? There are existing solutions to the problem.

**Comment by slfritchie** [comment]
Basho engineering has not been able to settle on a "storage zone" design that isn't horrible in at least one common scenario.

Workaround: use ZFS or a RAID-style logical volume manager.

**Comment by pingyym** [comment]
volume manager  may have a lower performance than riak manage disks itself?

@slfritchie As more and more nodes, communication between nodes will become the system bottleneck, so we have to reduce nodes by "storage zone" or other way like volume manager? can you tell me why riak not been able to settle on a "storage zone"  design, It is difficult or just think don't need at present?

**Comment by slfritchie** [comment]
If a person were to accept the idea that Basho's developers have a very thorough knowledge of Riak's internals, and if no Basho developer has been able to make a per-disk "storage zone"-like proposal that can satisfy the rest of Basho internally, then it's quite likely that there is no easy way to implement per-disk "storage zone"-like things within Riak today. And every proposal for a future Riak has had serious negative consequences that Basho (internally) has rejected.

If you have a PR that demonstrates that we've overlooked a good idea, we'd be happy to take a look at it.  ^_^

Meanwhile, use RAID today.
