### ISSUE TITLE
Failed make rel on canola_port.c on Ubuntu 12.04 and R17.4 [JIRA: RIAK-1678]

### ISSUE THREAD

**Issue by mkuznetsov** [basho/riak#724]
Get error while compilation from source. Tried develop and 2.1 branches. Get same result. 
Tried to install canola with apt-get, but it does not change situation. 
I need compiled version for development.  Binary package installed from packagecloud runs ok, but I need to compile from source to make local 3 node cluster for development. 

If u post instructions how to make 3 node package with binary package from it may solve my problem. 

R17.4
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 6.3.1

System:
Linux dev 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:51:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Fail of make rel:
==> yokozuna (compile)
==> canola (compile)
Compiling /root/riak/deps/canola/c_src/canola-port.c
/root/riak/deps/canola/c_src/canola-port.c:36:31: fatal error: security/pam_appl.h: No such file or directory
compilation terminated.
ERROR: compile failed while processing /root/riak/deps/canola: rebar_abort
make: **\* [compile] Error 1

**Comment by jadeallenx** [comment]
On my system, `/usr/include/security/pam_appl.h` is part of the pam-devel package. Looks like on 12.04 Ubuntu that's [libpam0g-dev](http://packages.ubuntu.com/precise/libpam0g-dev).

**Comment by mkuznetsov** [comment]
installed libpam0g-dev and finish my compilation. Thanks a lot

**Comment by BinyuHuang-nju** [comment]
> installed libpam0g-dev and finish my compilation. Thanks a lot

I encountered this problem too like you did and installed what you recommended, and now I successfully passed the "make rel" . Thanks very much.
