### ISSUE TITLE
Riak devrel failing to start with message: "handoff.ip invalid, must be a valid IP address" [JIRA: RIAK-1742]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#733]
This is the same issue reported in basho/riak_core#670, but applies to a devrel built from the `riak-2.1.0` tag.

A fix is included in PR #731

**Comment by JeetKunDoug** [comment]
This is handled by https://github.com/basho/riak/pull/734, which was released in 2.1.1. Can we close this and the related PR?

**Comment by lukebakken** [comment]
Fine by me!

**Comment by Basho-JIRA** [comment]
Closing this based on the comment above stating it was resolved with PR 734 in release 2.1.1 

**_[posted via JIRA by Patricia Brewer]**_
