### ISSUE TITLE
changing queue_size has no effect for the riak-repl realtime queue [JIRA: RIAK-1799]

### ISSUE THREAD

**Issue by cipy** [basho/riak#737]
Our app.config has the new value (1 GB): 
root@riak-1:~# grep queue /etc/riak/app.config 
{queue_size, 1073741824}

But after a restart, the riak-repl status still shows the default (100 MB): 
root@riak-1:~# riak-repl status | grep max_bytes 
{max_bytes,104857600},

**Comment by cipy** [comment]
we found the following versions to be affected: 1.4.12+ and 2.0.5+

**Comment by jonmeredith** [comment]
I believe the setting you need is `rtq_max_bytes` under riak_repl.
You can also 'do it live' with `riak_repl_rtq:set_max_bytes(1073741824)`, but that won't survive a restart (or process crash).

In future, we should probably make JIRA file RiakEE issues against https://github.com/basho/riak_ee-issues.

**Comment by boosty** [comment]
@jonmeredith Thanks! I was the one asking @cipy for help in this case :wink: 

Just wanted to let you know that setting it live via `riak attach` does not seem to work with 1.4.12:

```
riak_repl_rtq:set_max_bytes(1073741824).
** exception error: undefined function riak_repl_rtq:set_max_bytes/1
```

However, I am happy that setting `rtq_max_bytes` works via `app.config`.

**Comment by jonmeredith** [comment]
Apologies, got the wrong module... the price of rolling upgrade compatibility. `riak_repl2_rtq:set_max_bytes(1073741824)`

**Comment by sramakr** [comment]
I understand this thread is very old, do anyone know how to do this in riak 2.2.
Figured it out, had to use riak attach instead of direct erlang.
Fixed with, ```
riak attach $
riak_repl2_rtq:set_max_bytes(2073741824).
ok ```
