### ISSUE TITLE
Riak-debug throws error during execution  [JIRA: RIAK-1874]

### ISSUE THREAD

**Issue by jenafermiller** [basho/riak#748]
The `riak/rel/files/riak-debug` file throws the following error during execution: 

```
........E......EE......................dev2/bin/riak-debug: line 863: [: too many arguments
```

This error originates from the following line:

```
    if [ -n $exclude ]; then
```

To fix this, the `$exclude` must be in quotation marks as follows:

```
    if [ -n "$exclude" ]; then
```

**Comment by jenafermiller** [comment]
PR for fix:  https://github.com/basho/riak/pull/749

**Comment by cmeiklejohn** [comment]
:+1: 09ed9f3, please open backports for 2.0 and 2.1 if necessary.
