### ISSUE TITLE
Build fails on compiling protobufs [JIRA: RIAK-1908]

### ISSUE THREAD

**Issue by JaakkoKi** [basho/riak#755]
fatal: Not a git repository (or any of the parent directories): .git
Using rebar.config.lock file to fetch dependencies
./rebar -C rebar.config.lock get-deps
==> rebar_lock_deps_plugin (get-deps)
==> node_package (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> syslog (get-deps)
==> lager_syslog (get-deps)
==> cluster_info (get-deps)
==> sidejob (get-deps)
==> erlang_js (get-deps)
==> meck (get-deps)
==> getopt (get-deps)
==> neotoma (get-deps)
==> cuttlefish (get-deps)
==> bitcask (get-deps)
==> eper (get-deps)
==> edown (get-deps)
==> sext (get-deps)
==> poolboy (get-deps)
==> basho_stats (get-deps)
==> riak_sysmon (get-deps)
==> eleveldb (get-deps)
==> riak_ensemble (get-deps)
==> pbkdf2 (get-deps)
==> parse_trans (get-deps)
==> bear (get-deps)
==> folsom (get-deps)
==> setup (get-deps)
==> src (get-deps)
==> exometer_core (get-deps)
==> clique (get-deps)
==> riak_core (get-deps)
==> riak_pipe (get-deps)
==> protobuffs (get-deps)
==> riak_pb (get-deps)
==> mochiweb (get-deps)
==> webmachine (get-deps)
==> riak_api (get-deps)
==> riak_dt (get-deps)
==> eunit_formatters (get-deps)
==> riak_kv (get-deps)
==> merge_index (get-deps)
==> lucene_parser (get-deps)
==> riak_search (get-deps)
==> erlydtl (get-deps)
==> riak_control (get-deps)
==> riaknostic (get-deps)
==> kvc (get-deps)
==> ibrowse (get-deps)
==> yokozuna (get-deps)
==> canola (get-deps)
==> riak_auth_mods (get-deps)
==> rel (get-deps)
==> riak (get-deps)
==> riak-2.1.1 (get-deps)
./rebar compile
==> rebar_lock_deps_plugin (compile)
==> node_package (compile)
==> goldrush (compile)
==> lager (compile)
==> syslog (compile)
==> lager_syslog (compile)
==> cluster_info (compile)
==> sidejob (compile)
==> erlang_js (compile)
make[1]: Entering directory `/home/ubuntu/riak-2.1.1/deps/erlang_js'
cd c_src; make
make[2]: Entering directory`/home/ubuntu/riak-2.1.1/deps/erlang_js/c_src'
make[2]: Nothing to be done for `js'.
make[2]: Leaving directory`/home/ubuntu/riak-2.1.1/deps/erlang_js/c_src'
make[1]: Leaving directory `/home/ubuntu/riak-2.1.1/deps/erlang_js'
==> meck (compile)
==> getopt (compile)
==> neotoma (compile)
==> cuttlefish (compile)
==> getopt (escriptize)
==> goldrush (escriptize)
==> lager (escriptize)
==> neotoma (escriptize)
==> cuttlefish (escriptize)
==> bitcask (compile)
==> eper (compile)
==> edown (compile)
==> sext (compile)
==> poolboy (compile)
==> basho_stats (compile)
==> riak_sysmon (compile)
==> eleveldb (compile)
make[1]: Entering directory`/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make  all-am
make[2]: Entering directory `/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make[2]: Nothing to be done for`all-am'.
make[2]: Leaving directory `/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Leaving directory`/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Entering directory `/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make[2]: Entering directory`/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
test -z "/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib" || /bin/mkdir -p "/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib"
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libsnappy.la '/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib'
libtool: install: /usr/bin/install -c .libs/libsnappy.so.1.1.2 /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib/libsnappy.so.1.1.2
libtool: install: (cd /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib && { ln -s -f libsnappy.so.1.1.2 libsnappy.so.1 || { rm -f libsnappy.so.1 && ln -s libsnappy.so.1.1.2 libsnappy.so.1; }; })
libtool: install: (cd /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib && { ln -s -f libsnappy.so.1.1.2 libsnappy.so || { rm -f libsnappy.so && ln -s libsnappy.so.1.1.2 libsnappy.so; }; })
libtool: install: /usr/bin/install -c .libs/libsnappy.lai /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib/libsnappy.la
libtool: install: /usr/bin/install -c .libs/libsnappy.a /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib/libsnappy.a
libtool: install: chmod 644 /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib/libsnappy.a
libtool: install: ranlib /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib/libsnappy.a
## libtool: finish: PATH="/usr/lib/erlang/erts-5.10.4/bin:/usr/lib/erlang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib

Libraries have been installed in:
   /home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
- add LIBDIR to the `LD_LIBRARY_PATH' environment variable
   during execution
- add LIBDIR to the `LD_RUN_PATH' environment variable
   during linking
- use the `-Wl,-rpath -Wl,LIBDIR' linker flag
- have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
## more information, such as the ld(1) and ld.so(8) manual pages.

test -z "/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/share/doc/snappy" || /bin/mkdir -p "/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/share/doc/snappy"
 /usr/bin/install -c -m 644 ChangeLog COPYING INSTALL NEWS README format_description.txt '/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/share/doc/snappy'
test -z "/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/include" || /bin/mkdir -p "/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/include"
 /usr/bin/install -c -m 644 snappy.h snappy-sinksource.h snappy-stubs-public.h snappy-c.h '/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/system/include'
make[2]: Leaving directory `/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Leaving directory`/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Entering directory `/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/leveldb'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/ubuntu/riak-2.1.1/deps/eleveldb/c_src/leveldb'
==> riak_ensemble (compile)
==> pbkdf2 (compile)
==> parse_trans (compile)
==> bear (compile)
==> folsom (compile)
==> setup (compile)
==> edown (escriptize)
==> setup (escriptize)
==> src (compile)
==> exometer_core (compile)
==> clique (compile)
==> riak_core (compile)
==> riak_pipe (compile)
==> protobuffs (pre_compile)
==> protobuffs (compile)
ERROR: compile failed while processing /home/ubuntu/riak-2.1.1/deps/protobuffs: {'EXIT',
    {function_clause,
        [{filename,pathtype,
             [{"src/protobuffs_scanner.xrl","src/protobuffs_scanner.erl"}],
             [{file,"filename.erl"},{line,515}]},
         {filename,absname,2,[{file,"filename.erl"},{line,79}]},
         {rebar_base_compiler,compile_queue,3,
             [{file,"src/rebar_base_compiler.erl"},{line,184}]},
         {rebar_erlc_compiler,compile,2,
             [{file,"src/rebar_erlc_compiler.erl"},{line,94}]},
         {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,491}]},
         {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,416}]},
         {rebar_core,maybe_execute,8,[{file,"src/rebar_core.erl"},{line,300}]},
         {rebar_core,process_dir1,7,
             [{file,"src/rebar_core.erl"},{line,259}]}]}}
make: **\* [compile] Error 1

I'm n00b on ubuntu, please help??

**Comment by lucasbru** [comment]
I have the same problem (Fedora 23)

**Comment by lucasbru** [comment]
Cryptic error message, easy solution.
Try a `sudo apt-get install erlang-parsetools`
