### ISSUE TITLE
handoff.ip missing from configuration on 2.0.6 devrel build  [JIRA: RIAK-1914]

### ISSUE THREAD

**Issue by binarytemple** [basho/riak#760]
Could be a bug - or perhaps just a problem with devrel 

```
[/basho/riak%]./dev/dev1/bin/riak config generate -l debug
....
09:22:56.995 [debug] ConfFiles: ["/basho/riak/dev/dev1/bin/../etc/riak.conf"]
09:22:57.105 [debug] Adding Defaults
09:22:57.106 [debug] Right Hand Side Substitutions
09:22:57.106 [debug] Applying Datatypes
09:22:57.126 [debug] Lager installed handler lager_backend_throttle into lager_event
09:22:57.128 [debug] Validation
09:22:57.128 [error] handoff.ip invalid, must be a valid IP address
09:22:57.128 [error] Error generating configuration in phase validation
09:22:57.128 [error] handoff.ip invalid, must be a valid IP address

[/basho/riak%]./dev/dev1/bin/riak config effective | less

handoff.inbound = on
handoff.ip =
handoff.max_rejects = 6
handoff.outbound = on
handoff.port = 10019
handoff.use_background_manager = off
```

Note how the handoff.ip is blank?

**Comment by JeetKunDoug** [comment]
I've reproduced this by first building the develop branch, then switching to the 2.0 branch and rebuilding without first cleaning up deps/dev directories - but it doesn't reproduce after a clean (as the problem has to do with a change made in the 2.1 series cuttlefish schema for handoff.ip). `make distclean` will do this for you, but `make clean` doesn't do enough (as it doesn't actually remove your deps, which is required to make sure you've got the correct dependencies when changing branches.
Can you please confirm that removing deps (either using `make distclean` or `rm -rf deps`) resolves this issue for you as well?

**Comment by binarytemple** [comment]
Confirmed, and thanks for your help. Perhaps this could be a future rebar enhancement. B

**Comment by JeetKunDoug** [comment]
So `make clean` means "please remove any compile-derived files from my filesystem", not necessarily "remove everything other than source from my filesystem", and cleaning the deps directory seems to fall into the latter case.
