### ISSUE TITLE
packagecloud: package for debian/jessie is absent [JIRA: RIAK-1960]

### ISSUE THREAD

**Issue by mogadanez** [basho/riak#766]
https://packagecloud.io/basho/riak?filter=debs
jessie now is last stable debian build 
and many automation script that used packagecloud not works on jessie

**Comment by kri5** [comment]
:+1:

**Comment by asyncmind0** [comment]
+1

**Comment by tatikoma** [comment]
+1

**Comment by angrycub** [comment]
Sorry about the radio silence on this ticket.  I can confirm that Riak KV 2.2.0 will be released with Debian 8 packages via packagecloud.  Stay tuned!

**Comment by Basho-JIRA** [comment]
Confirmed for Riak 2.2 

**_[posted via JIRA by Patricia Brewer]**_
