### ISSUE TITLE
Increase default Erlang port limit [JIRA: RIAK-2332]

### ISSUE THREAD

**Issue by jcapricebasho** [basho/riak#801]
Our current default of `65536` for `erlang.max_ports` is too low. This default should be increased to `262144`.

**Comment by Basho-JIRA** [comment]
[~Mark Allen] please review the attached PR - it's really simple (increase a number, and fix the test to expect that number). 

**_[posted via JIRA by Douglas Rohrer]**_

**Comment by Basho-JIRA** [comment]
Validated tests and +1'd 

**_[posted via JIRA by Mark Allen]**_
