### ISSUE TITLE
Riak needs a modern communication channel for troubleshooting. [JIRA: RIAK-2363]

### ISSUE THREAD

**Issue by Zerebokep** [basho/riak#805]
Is there any reason why there is no official forum or answers page for riak? I know there is a mailing list (which feels like 1999), but it seems no one actively moderates it. At least my messages never get approved. I really like Riak, but the missing community hub pushes me away from using it for future projects.

**Comment by lukebakken** [comment]
Hello - have you had issues joining the mailing list? That is the way to avoid moderation.

http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com

There is an extensive list of community resources here: http://docs.basho.com/riak/latest/community/

I will bring up your concerns internally, thanks.

**Comment by lukebakken** [comment]
> official forum or answers page for riak

Questions from internal team members:
- What would you suggest as a replacement for a mailing list?
- How does the mailing list or other community resources not meet your needs?

**Comment by Zerebokep** [comment]
I think a bulletin board software would be perfect (e.g. invision power board, vBulletin, etc.). Or stackexchange like Unity Answers (http://answers.unity3d.com).

Imo mailing lists have a horrible usability, they are slow (if they are moderated), they have no search (you have to use google site: to find your info), you always need to publish your email, it's an really old medium, no one wants anymore.

**Comment by lukebakken** [comment]
Thank you for your suggestions. We do moderate the riak-users mailing list on a daily basis. If you find that an email to the list awaits moderation, joining the list will bypass that step.
