### ISSUE TITLE
Move "cluster-info local" command to --extracmds [JIRA: RIAK-2530]

### ISSUE THREAD

**Issue by roooms** [basho/riak#832]
In a couple of situations where riak-debug has been run on nodes that are already very busy or overloaded, it has caused the node to either crash or pause. Gathering info is critical, but running riak-debug should not cause significant impact if it can be avoided.

Proposal is to remove `riak-admin cluster-info local`[0]  so it is not run by default and use it via `--extracmds` if required, so it can still be added to a debug. 

[0] https://github.com/basho/riak/blob/develop/rel/files/riak-debug#L484-L488

**Comment by angrycub** [comment]
@rooms, Does #857 close this issue?

**Comment by roooms** [comment]
Resolved in https://github.com/basho/riak/pull/857
