### ISSUE TITLE
Problems starting Riak TS 1.3 on OS X El Capitan [JIRA: RIAK-2668]

### ISSUE THREAD

**Issue by rhumbertgz** [basho/riak#851]
I have been trying to run Riak TS 1.3.0 (Open Source) on OS X El capitan, but every time that run the start command I get this error:

```
Humbertos-MBP:bin Humberto$ ./riak start 
vm.args needs to have a -name parameter.
  -sname is not supported.
```

I tried with the rest of the commands, but the same result :(

However, I also tried on Ubunto and works perfectly

Any suggestions about my error on Mac?

Best regards, Humberto

**Comment by seanjensengrey** [comment]
Hey Humberto,

Could you try with 1.3.1 and report back?

http://docs.basho.com/riak/ts/1.3.1/downloads/

what is the contents of 

```
/etc/hosts
/etc/resolv.conf
```

Are your running any other Erlang based services? `ps aux | grep beam`

**Comment by rhumbertgz** [comment]
Hi, thanks for the advice. I downloaded 1.3.1 and it works perfectly :)

Best regards 
Humberto

**Comment by rhumbertgz** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

rhumbertgz@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Your empowr account was reserved for you by rhumbertgz@gmail.com in order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQtGKhXj6ZmaH6IW0F73D0E3AKFWnmwt6O8LmPM%2FxvZnPV79zouXFS8kdg%2FmTgkzrp9viEm%2FDbA4k1aBNvPabtBPkVu2Af3xTq2mVRrJzA5Ri41RRwZ%2BssHcHPSAUP%2FZa%2BWjxPmPHEVB1TeSY0CBIwJ&vet=694&mlid=9132439566&fn=DmX4B%2FytPyvpaEZ5nouJrA%3D%3D.

No more emails from rhumbertgz@gmail.com (rhumbertgz@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQtGKhXj6ZmaH6IW0F73D0E3AKFWnmwt6O8LmPM%2FxvZnPV79zouXFS8kdg%2FmTgkzrp9viEm%2FDbA4k1aBNvPabtBPkVu2Af3xTq2mVRrJzA5Ri41RRwZ%2BssHcHPSAUP%2FZa%2BWjxPmPHEVB1TeSY0CBIwJ&vet=694&mlid=9132439566&fn=DmX4B%2FytPyvpaEZ5nouJrA%3D%3D

*This promotional email has been sent by rhumbertgz@gmail.com to reply@reply.github.com. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by rhumbertgz** [comment]
body {{ margin:0 !important; }}
div[style*="margin: 16px 0"] {{ margin:0 !important; font-size:100% !important; }}
#outlook a {{

padding: 0;
}}
.ReadMsgBody {{

width: 100%;
}}
.ExternalClass {{

width: 100%;
}}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {{

line-height: 100%;
}}
body, table, td, a {{

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}}
table, td {{

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}}
img {{

-ms-interpolation-mode: bicubic;
}}

body {{margin: 0;padding: 0;}}
img {{

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}}
table {{

border-collapse: collapse !important;
}}
body {{

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}}

appleBody a {{

color: #68440a;

text-decoration: none;
}}
.appleFooter a {{

color: #999999;

text-decoration: none;
}}
.faq {{

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}}
.mobile-only {{

display: none;
}}
.img-apps {{ padding:0 5px 0 0;}}

a.mobile-button:link, a.mobile-button:visited {{ color:#fff!important;}}

@media screen and (max-width: 525px) {{

table[class="wrapper"] {{

width: 100% !important;
}}

td[class="logo"] {{

text-align: left;

padding: 20px 0 20px 0 !important;
}}
td[class="logo"] img {{

margin: 0 auto!important;
}}

[class="mobile-only"] {{

display: block;
}}

br[class="mobile-hide"] {{

display: none;
}}
td[class="mobile-hide"] {{

display: none;
}}
img[class="mobile-hide"] {{

display: none !important;
}}
img[class="img-max"] {{

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}}

img[class="img-min"] {{

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}}

img[class="img-apps"] {{

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}}
img[class="img-max-profile"] {{

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}}

table[class="responsive-table"] {{

width: 100%!important;
}}

td[class="padding"] {{

padding: 10px 5% 15px 5% !important;
}}
td[class="amount"] {{

font-size: 9px!important;
}}
td[class="mobile-text-twelve"] {{

font-size: 12px!important;
}}
span[class="mobile-text-twelve"] {{

font-size: 14px!important;
}}
td[class="padding-copy"] {{

padding: 10px 5% 10px 5% !important;

text-align: center;
}}
td[class="padding-meta"] {{

padding: 30px 5% 0px 5% !important;

text-align: center;
}}
td[class="no-pad"] {{

padding: 0 0 20px 0 !important;
}}
td[class="no-pad-bottom"] {{

padding: 25px 0 0 0 !important;
}}
td[class="no-padding"] {{

padding: 0 !important;
}}
td[class="section-padding"] {{

padding: 25px 15px 25px 15px !important;
}}
td[class="section-no-padding-bottom"] {{

padding: 25px 15px 0 15px !important;
}}

td[class="section-no-padding-top"] {{

padding: 0 5% 25px 5% !important;
}}

td[class="section-no-padding-top-bottom"] {{

padding: 0 5% 0 5% !important;
}}
td[class="section-padding-bottom-image"] {{

padding: 50px 15px 0 15px !important;
}}

td[class="mobile-wrapper"] {{

padding: 10px 5% 15px 5% !important;
}}
table[class="mobile-button-container"] {{

margin: 0 auto;

width: 100% !important;
}}
a[class="mobile-button"] {{

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}}
}}

Earn $100 in 1 minute.

How?

Simply try our new social network for only 50 seconds...

..and give us your feedback in less than 10 seconds.

Give me $100 (start the clock) &#9658;

Your empowr account was reserved for you by rhumbertgz@gmail.com. In order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQtGKhXj6ZmaH6IW0F73D0E3AKFWnmwt6O8LmPM%2FxvZnPV79zouXFS8kdg%2FmTgkzrp9viEm%2FDbA4k1aBNvPabtBPkVu2Af3xTq2mVRrJzA5Ri41RRwZ%2BssHcHPSAUP%2FZa%2BWjxPmPHEVB1TeSY0CBIwJ&vet=724&mlid=9363056016.

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by rhumbertgz** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=15&amp;authToken=X%2bS1Z2jqB%2fGKv8Tr%2bo2KHxAtB%2fP8653FzEDE9vZxvWtmBRc%2fk9%2bm%2flLF0YgGbPL6vp3g9%2b%2foYmFDJ3vvbvDjSqL7jc7GB79OvxzGD%2fAdGkRf0h2O4E8hDphYACOSM9QNTBg5e8Y0prZC%2fwaJgjPJVM3xKpcWbfOZtDGt9rzF2S4zVQQL9zWoSeih7nFOOqnaIr4rvFlEOuYX6GpUM9VLez6Z00RCjy4CTlYDSAR9QU8pxYx2GVQ%2fKlFdtMR3I7ZTtPUKiEK990mTNUKYzKuOCnL8AgdMmPWPu8AfZbpU8D%2bGjbifFrUMtfM8JghUqosT&amp;PolicyAcceptance=ccu2UqtQpHlCQD%2bRQWSwkCbUST%2fr8yKRlY6WE9FPMfyac0xFmI5tdLwaCnw5VGqQrlr4JDhVBUXnrz70ACwauunL7mgeiiLMdfAE1O3XYTaUdvz15v3Jl4NiEHqLhUJ7NSMdKlVF%2fQmbYmdxy4vHKjhtujpfUuFZ%2f8z0DY39K4DuWbyRpHbiEBvIl7K7nr8clRh6TyDOmkHMCNOjOmMmAJLeHEUXjKu1xs9Vdtu7HkxQ2YuyH%2fLu4CsFhAaCeIxdNan1MFzoOm5TjdClvf9UV58A4rhLXa8ZJ2rMojc6f3rvNobqN0%2brCiFA8NdYwJYzwh37vCeG9lL20RNnp1oP9%2bu1jxfjdj8kafa9NDSlH8UnLgGeQoU8RlpAJGGyf2u3RsPbeZ12ZarJTe6hxCNu0jqTZ8TdKNFUfFWU3PXn23RmWj2EB7T7Ffj%2f4WVZhp2r8tNbdTi56Zt2zRrcg3aoKtGAF7uOQVxCHqy%2b0K7nVRth9%2bhD9NKm33HiIDRESyW08fHuXW1LsyTGtdSdXgoSjsuJfX9ByICgRoWZsoVqSmlbuNxs8x7B%2b5gDhFQxKzW2kpEGnwPdjg6S82jWba3G7mcKJTgwBzJjEYDzfKDjj%2bCg12bpawCl4bkhbER0%2fbh2cTbr1vsDDlR2FTcMZolCsOcrSn0eMVJwRIRyFwjE4%2bA26vJiXZHhGPy%2fld%2bELv2AqJr4S8v4EqRXNgqjMLqsBxxPuYonxweMeIhkHgQMj7heyWN%2fN9hJ3O64b4XEyd3%2bpH17MFqSf2kjGIQps%2bZ2%2fey%2fYrn90Q%2fC4ETMj0weOf%2f2UuZNLoWYgeENOXo7lhVNqf91bymYifzN9pWoXcgk76tU%2byG%2f4FvUsgXTT9GC0Vj0za1%2b2ctNqYtb08CRh%2fvr1PpTskVToRO%2f5GhlKRE0CKwatUmb8L1Q2uDirE6oWxJsvPskEF90oT3iKf%2fY2ubgEZimRWY99VwpDaW%2bCEjf%2bw%3d%3d&amp;vet=745&amp;dt=101717&amp;mlid=9973270273&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=51833054&amp;rt=13:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQtGKhXj6ZmaH6IW0F73D0E3AKFWnmwt6O8LmPM%2FxvZnPV79zouXFS8kdg%2FmTgkzrp9viEm%2FDbA4k1aBNvPabtBPkVu2Af3xTq2mVRrJzA5Ri41RRwZ%2BssHcHPSAUP%2FZa%2BWjxPmPHEVB1TeSY0CBIwJ&vet=745&mlid=9973270273.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppQtGKhXj6ZmaH6IW0F73D0E3AKFWnmwt6O8LmPM%2FxvZnPV79zouXFS8kdg%2FmTgkzrp9viEm%2FDbA4k1aBNvPabtBPkVu2Af3xTq2mVRrJzA5Ri41RRwZ%2BssHcHPSAUP%2FZa%2BWjxPmPHEVB1TeSY0CBIwJ&vet=745&mlid=9973270273

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by rhumbertgz** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=IfuMzMbNSQ9pCeVJCFt%2biFzBM10chuVgb%2fMFnAC2y%2bZ4tBJLIUPscBwEZRqBQ5l7RuXHs9KD%2fvkvUqgwjR0OQ6MtV%2fCY013kH9J5DCGoDmYHXfgLUYaVDkIOpmb8Jbl%2fVKwUMtZouAt1ut%2bffK%2f0lPVL1Le9eLl0pwziZL8ar9TRM8bTtWP%2fWnZBQxnDPppKhn7Eok03jjWo%2feemD1T6ZI0pvm0Tc5fQwTT2vR3mgpHwqjzvGMOTpg2r%2fjy%2f%2bAOMeQ3MFft1yweYbAzF8CD2IR3eVDIyx6YAAeuA6R1QuVqQlfaCJRH9y%2biK%2ffTD1dzq&amp;PolicyAcceptance=ZiXOhyG4IJe7JhOUocBK4p%2feyIHdS%2bC7jtauJSQ%2bOEemN2R5nmTYLuRajBJG3Cl2iaJqwOQYHb1kNXaI0Jq6N%2frZgaI0SfniRI7YkZ0PqWxOB%2bNJKVY0FSvOZNWxschOtkPnlh0MumoKA31vkNlEwOol6OIc8jNFrTiJK7f%2fz0BZdFkURotsHvGqf5QzTy0jZhBHLY2LW9QRHB1dy1c2AEUulPMf3os4KLXddeplqLx6Baylq1w4%2be31dQoCK%2flNOk1p2aA3SPIHHOq7Qyvb9sUfe1ZE0O%2fw4kT30xNb523rRiAkaid%2bKry18YBBAlZS93Ymd363KduOmtE9oEPf2AZ3%2bT3JkJH6cphLz1xGVNhIQeoivs9KMpSYd2wgvjYDf5s9%2fum5fY2evmkW7YcRN4q%2ffxz0AeJ5e3xAgxhrwQ%2bZUw%2fLzjtez0NLVH0HKvjCVYgd8YSsj17WT7zI7RgNIQeLBbI%2flmZXnL7bmY%2biuFOWEgw3UuhLCJHSkJEnvmGNG5xgQKaGB7R1xc0JgM7LZCpML6H9jEYFS758LR0PEjnzEcnrOcwP7vzvSme%2fFZa4arvN0DMqx4Gz8Po5wS2XaoqDphR%2bYWBQBPnPvVws%2bqPLOpg7UvPgoyITARvsdSTE%2f70lXHbo0MxqhxbgHTiUdZ1htj%2bcTG7l0Xal7KBxTOWNWBf7lbsZdtmNsljVgu6o6ZwJf6h92IQoPMG83ttsT476XtAooCnvGMmpWPRzVwxvTrYNRqd0Pg51YPOjV4OvQqretr0SxFxFSF09UQCCD65gYhmV8AvJagKORI3wUtO0c9y3s25MOROeTGHJaqx1M4xkNjA6VlGzgtUkAWCWdM%2fFw3dNU93jfgvC5SsCen60spPxHa02ddgFKpGU6qEA%2f5z2PquOBK0eUJ8uJ3h%2fc5czrCifGgzwezj3Ho0PxW1FXvQ5oS7oubHQoHOD5geTKOJWE%2f50YdBc3LzMKhWjxEfMlaD5R1wB9z6ZBpYvro4%3d&amp;vet=760&amp;dt=011018&amp;mlid=10152831766&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=51833054&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA
