### ISSUE TITLE
Issues when I call make rel [JIRA: RIAK-2815]

### ISSUE THREAD

**Issue by topeomot2** [basho/riak#875]
I want to install riak from source on ubuntu 16.04. When I call make rel, i get the following

topeomot@topeomot5:~/riak-develop$ make rel
fatal: Not a git repository (or any of the parent directories): .git
./rebar get-deps
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [cuttlefish_rebar_plugin,rebar_lock_deps_plugin]
==> rel (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak (get-deps)
==> riak-develop (get-deps)
Pulling rebar_lock_deps_plugin from {git,
                                     "git://github.com/seth/rebar_lock_deps_plugin.git",
                                     {branch,"master"}}
Cloning into 'rebar_lock_deps_plugin'...
Pulling node_package from {git,"git://github.com/basho/node_package.git",
                               {branch,"develop"}}
Cloning into 'node_package'...
Pulling lager_syslog from {git,"git://github.com/basho/lager_syslog.git",
                               {tag,"2.0.3"}}
Cloning into 'lager_syslog'...
Pulling cluster_info from {git,"git://github.com/basho/cluster_info.git",
                               {branch,"develop"}}
Cloning into 'cluster_info'...
Pulling riak_kv from {git,"git://github.com/basho/riak_kv.git",
                          {branch,"develop"}}
Cloning into 'riak_kv'...
Pulling riak_search from {git,"git://github.com/basho/riak_search.git",
                              {branch,"develop"}}
Cloning into 'riak_search'...
Pulling riak_control from {git,"git://github.com/basho/riak_control.git",
                               {branch,"develop"}}
Cloning into 'riak_control'...
Pulling riaknostic from {git,"git://github.com/basho/riaknostic.git",
                             {branch,"develop"}}
Cloning into 'riaknostic'...
Pulling yokozuna from {git,"git://github.com/basho/yokozuna.git",
                           {branch,"develop"}}
Cloning into 'yokozuna'...
Pulling riak_auth_mods from {git,"git://github.com/basho/riak_auth_mods.git",
                                 {branch,"develop"}}
Cloning into 'riak_auth_mods'...
Pulling meck from {git,"git://github.com/basho/meck.git",{tag,"0.8.2"}}
Cloning into 'meck'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> node_package (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> lager_syslog (get-deps)
Pulling lager from {git,"git://github.com/basho/lager.git",{tag,"2.0.3"}}
Cloning into 'lager'...
Pulling syslog from {git,"git://github.com/Vagabond/erlang-syslog.git",
                         {tag,"1.0.2"}}
Cloning into 'syslog'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> lager (get-deps)
Pulling goldrush from {git,"git://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.6"}}
Cloning into 'goldrush'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> goldrush (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> syslog (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> cluster_info (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_kv (get-deps)
Pulling sidejob from {git,"git://github.com/basho/sidejob.git",{tag,"2.0.1"}}
Cloning into 'sidejob'...
Pulling erlang_js from {git,"git://github.com/basho/erlang_js.git",
                            {tag,"1.3.0"}}
Cloning into 'erlang_js'...
Pulling bitcask from {git,"git://github.com/basho/bitcask.git",{tag,"2.0.4"}}
Cloning into 'bitcask'...
Pulling eper from {git,"git://github.com/basho/eper.git",{tag,"0.78"}}
Cloning into 'eper'...
Pulling sext from {git,"git://github.com/basho/sext.git",{tag,"1.1p3"}}
Cloning into 'sext'...
Pulling riak_pipe from {git,"git://github.com/basho/riak_pipe.git",
                            {tag,"2.1.2"}}
Cloning into 'riak_pipe'...
Pulling riak_dt from {git,"git://github.com/basho/riak_dt.git",{tag,"2.1.3"}}
Cloning into 'riak_dt'...
Pulling eunit_formatters from {git,"git://github.com/seancribbs/eunit_formatters",
                                   {tag,"0.1.2"}}
Cloning into 'eunit_formatters'...
Pulling riak_api from {git,"git://github.com/basho/riak_api.git",
                           {tag,"2.1.3"}}
Cloning into 'riak_api'...
Pulling hyper from {git,"git://github.com/basho/hyper",{tag,"1.0.0"}}
Cloning into 'hyper'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> sidejob (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> erlang_js (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> meck (get-deps)
==> bitcask (get-deps)
Pulling cuttlefish from {git,"https://github.com/basho/cuttlefish.git",
                             {tag,"2.0.8"}}
Cloning into 'cuttlefish'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> cuttlefish (get-deps)
Pulling getopt from {git,"git://github.com/jcomellas/getopt.git",
                         {tag,"v0.8.2"}}
Cloning into 'getopt'...
Pulling neotoma from {git,"git://github.com/seancribbs/neotoma.git",
                          {tag,"1.7.3"}}
Cloning into 'neotoma'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> getopt (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> neotoma (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> eper (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> sext (get-deps)
Pulling edown from {git,"git://github.com/uwiger/edown.git",{tag,"0.5"}}
Cloning into 'edown'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> edown (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_pipe (get-deps)
Pulling riak_core from {git,"git://github.com/basho/riak_core.git",
                            {tag,"2.1.6"}}
Cloning into 'riak_core'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_core (get-deps)
Pulling poolboy from {git,"git://github.com/basho/poolboy.git",
                          {tag,"0.8.1p3"}}
Cloning into 'poolboy'...
Pulling basho_stats from {git,"git://github.com/basho/basho_stats.git",
                              {tag,"1.0.3"}}
Cloning into 'basho_stats'...
Pulling riak_sysmon from {git,"https://github.com/basho/riak_sysmon.git",
                              {tag,"2.1.3"}}
Cloning into 'riak_sysmon'...
Pulling eleveldb from {git,"git://github.com/basho/eleveldb.git",
                           {tag,"2.0.29"}}
Cloning into 'eleveldb'...
Pulling riak_ensemble from {git,"https://github.com/basho/riak_ensemble",
                                {tag,"2.1.3"}}
Cloning into 'riak_ensemble'...
Pulling pbkdf2 from {git,"git://github.com/basho/erlang-pbkdf2.git",
                         {tag,"2.0.0"}}
Cloning into 'pbkdf2'...
Pulling exometer_core from {git,"git://github.com/basho/exometer_core.git",
                                {tag,"1.0.0-basho8"}}
Cloning into 'exometer_core'...
Pulling clique from {git,"https://github.com/basho/clique.git",{tag,"0.3.7"}}
Cloning into 'clique'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> poolboy (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> basho_stats (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_sysmon (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> eleveldb (get-deps)
Cloning into 'leveldb'...
Note: checking out '2.0.29'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 97eb726... Merge branch 'develop' into 2.0 for 2.0.29 release (mv-expiry-manifest)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_ensemble (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> pbkdf2 (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> src (get-deps)
==> exometer_core (get-deps)
Pulling parse_trans from {git,"git://github.com/uwiger/parse_trans.git",
                              {tag,"2.9"}}
Cloning into 'parse_trans'...
Pulling folsom from {git,"git://github.com/basho/folsom.git",{tag,"0.7.4p5"}}
Cloning into 'folsom'...
Pulling setup from {git,"git://github.com/basho/setup.git",{tag,"1.5-basho2"}}
Cloning into 'setup'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> parse_trans (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> folsom (get-deps)
Pulling bear from {git,"git://github.com/basho/bear.git",{tag,"0.1.3p1"}}
Cloning into 'bear'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> bear (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> setup (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> clique (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_dt (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> eunit_formatters (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_api (get-deps)
Pulling riak_pb from {git,"git://github.com/basho/riak_pb.git",
                          {tag,"2.2.0.0"}}
Cloning into 'riak_pb'...
Pulling webmachine from {git,"git://github.com/basho/webmachine.git",
                             {tag,"1.10.8-basho1"}}
Cloning into 'webmachine'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_pb (get-deps)
Pulling protobuffs from {git,"https://github.com/basho/erlang_protobuffs.git",
                             {tag,"0.9.0"}}
Cloning into 'protobuffs'...
Pulling hamcrest from {git,"https://github.com/basho/hamcrest-erlang.git",
                           {tag,"0.3.0-basho"}}
Cloning into 'hamcrest'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> protobuffs (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> hamcrest (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> webmachine (get-deps)
Pulling mochiweb from {git,"git://github.com/basho/mochiweb.git",
                           {tag,"v2.9.0p2"}}
Cloning into 'mochiweb'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> mochiweb (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> hyper (get-deps)
Pulling proper from {git,"https://github.com/basho/proper.git",{tag,"v1.2p1"}}
Cloning into 'proper'...
Pulling stdlib2 from {git,"https://github.com/basho/stdlib2.git",
                          {tag,"0.0.1"}}
Cloning into 'stdlib2'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> proper (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> stdlib2 (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> lucene_parser (get-deps)
==> riak_search (get-deps)
Pulling merge_index from {git,"git://github.com/basho/merge_index.git",
                              {tag,"2.0.3"}}
Cloning into 'merge_index'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> merge_index (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_control (get-deps)
Pulling erlydtl from {git,"git://github.com/erlydtl/erlydtl.git","d20b53f0"}
Cloning into 'erlydtl'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> erlydtl (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riaknostic (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> yokozuna (get-deps)
Pulling kvc from {git,"git://github.com/etrepum/kvc.git",{tag,"v1.5.0"}}
Cloning into 'kvc'...
Pulling ibrowse from {git,"git://github.com/cmullaparthi/ibrowse.git",
                          {tag,"v4.0.2"}}
Cloning into 'ibrowse'...
Pulling fuse from {git,"git@github.com:jlouis/fuse.git",{tag,"v2.1.0"}}
Cloning into 'fuse'...
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: sh(git clone -n git@github.com:jlouis/fuse.git fuse)
failed with return code 128 and the following output:
Cloning into 'fuse'...
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR: 'get-deps' failed while processing /home/topeomot/riak-develop/deps/yokozuna: rebar_abort
Makefile:25: recipe for target 'deps' failed
make: **\* [deps] Error 1

**Comment by wozniakjan** [comment]
I would like to take the liberty and provide a makeshift answer, because I faced the issue few weeks ago as well. The error message means you may have misconfigured the ssh and git on your system. I found two possible solutions:
1) take a look at ssh and git configuration and set it up
2) since the repositories are all hosted on github and protocols are for your case interchangeable, you may take a look at rebar.config and rebar.config.lock and change the lines from 'git@github.com:jlouis/fuse.git' to 'git://github.com/jlouis/fuse.git' and the others when needed. This will bypass ssh and use git protocol for the network communication (also you can use https://)

more on git here: https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

**Comment by topeomot2** [comment]
Hi Wozniakjan, I checked both files and I can't find any line with  'git@github.com:jlouis/fuse.git'.

**Comment by wozniakjan** [comment]
My apologies, I should have specified in which  dependency rebar config was attempting to use ssh. The last dependency that failed to compile is yokozuna according to the log you provided. Try checking a file in 'deps/yokozuna/rebar.config'. Also you can recursively grep through the directory where you tried building riak for hints - 'grep . --include=*.config -nrie "git@github.com" '

**Comment by topeomot2** [comment]
Hi, it worked but now I get the error
ERROR: OTP release 18 does not match required regex R16|17
ERROR: compile failed while processing /home/topeomot/riak-develop/deps/rebar_lock_deps_plugin: rebar_abort
Makefile:22: recipe for target 'compile' failed
make: *** [compile] Error 1

Is there a way to bypass the OTP version or do I need to roll back the version?

**Comment by topeomot2** [comment]
It worked. Thanks.
