### ISSUE TITLE
Set allow_mult=false & last_write_wins=false using `aws-sdk-js` [JIRA: RIAK-2890]

### ISSUE THREAD

**Issue by essapalaxo** [basho/riak#877]
We are using [aws-sdk-js](https://github.com/aws/aws-sdk-js) to interact with with `Riak`. Whenever I try to overwrite a buffer in `Riak` it creates new siblings. But looks like `aws-sdk-js` doesn't know about how to retrieve siblings.

I was wondering If I can disable the creation of siblings i.e. set `allow_mult=false` & `last_write_wins=false`. How can I set these properties so that I can retrieve buffer using `aws-sdk-js` without any error? Any idea?

I have also created an [issue here](https://github.com/aws/aws-sdk-js/issues/1172) in `aws-sdk-js` repository.

Thanks in anticipation.

**Comment by lukebakken** [comment]
Please see this document:

http://docs.basho.com/riak/kv/2.1.4/developing/api/http/set-bucket-props/

**Comment by essapalaxo** [comment]
@lukebakken Thank you for your reply. Sorry but I am using `Riak 1.2.1` and I guess setting properties like that is not possible in that version. Is there any other way?
