### ISSUE TITLE
Change default branch [JIRA: RIAK-3043]

### ISSUE THREAD

**Issue by jeroenvisser101** [basho/riak#883]
It seemed like the project was dead, but it's far from that. Can you change the default branch on GitHub to point at the active branch?

**Comment by lukebakken** [comment]
As you can see, development has been occurring on the `develop-2.2` branch. `develop` will become the default branch at some point.

In the meantime, I recommend cloning the `riak` repository and checking out a tag corresponding to the release you'd like to build from source:

```
git clone https://github.com/basho/riak.git
cd riak
git checkout riak-2.2.0
make locked-deps rel
```

If you have any questions or run into any issues, please re-open this issue. Thanks!
