### ISSUE TITLE
Documentation Error: Riak KV HTTP API [JIRA: RIAK-3184]

### ISSUE THREAD

**Issue by w-p** [basho/riak#889]
http://docs.basho.com/riak/kv/2.2.0/developing/api/http/store-search-schema/

Request shows:
```
... /search/index/ ...
```

Example shows:
```
... /search/schema/ ...
```

I believe that the request block should point to __schema__ rather than __index__.

**Comment by lukebakken** [comment]
@w-p - would you mind opening this issue in the `basho_docs` repository?

https://github.com/basho/basho_docs

Thanks.

**Comment by w-p** [comment]
Done - https://github.com/basho/basho_docs/issues/2386

**Comment by lukebakken** [comment]
Thank you so much 😃
