### ISSUE TITLE
Solr crashes in Riak 2.2.0 with java 8 [JIRA: RIAK-3284]

### ISSUE THREAD

**Issue by AliakseiMat** [basho/riak#897]
Try to run Riak 2.2.0 in mac Sierra with java 8.
riak.conf:
```sh
search = on
riak_control = on
anti_entropy = passive
storage_backend = leveldb
```
Remainig config - default.
Riak started successfully and then stopped by the error: "solr didn't start in alloted time"

See the log below:
[solr.log.txt](https://github.com/basho/riak/files/798571/solr.log.txt)
[console.log.txt](https://github.com/basho/riak/files/797906/console.log.txt)
[crash.log.txt](https://github.com/basho/riak/files/797907/crash.log.txt)
[erlang.log.1.txt](https://github.com/basho/riak/files/797908/erlang.log.1.txt)
[error.log.txt](https://github.com/basho/riak/files/797909/error.log.txt)
[run_erl.log.txt](https://github.com/basho/riak/files/797911/run_erl.log.txt)
[erl_crash.dump.txt](https://github.com/basho/riak/files/797904/erl_crash.dump.txt)

Thanks,
Alex

**Comment by lukebakken** [comment]
How did you install Riak?

What happens when you try to start Solr on its own? I got this command out of `console.log.txt`:

```
/usr/bin/java -Djava.awt.headless=true -Djetty.home=/usr/local/Cellar/riak/2.2.0/libexec/lib/yokozuna-2.1.7-0-g6cf80ad/priv/solr -Djetty.temp=/usr/local/var/lib/riak/yz_temp -Djetty.port=8093 -Dsolr.solr.home=/usr/local/var/lib/riak/yz -DhostContext=/internal_solr -cp /usr/local/Cellar/riak/2.2.0/libexec/lib/yokozuna-2.1.7-0-g6cf80ad/priv/solr/start.jar -Dlog4j.configuration=file:///usr/local/Cellar/riak/2.2.0/libexec/etc/solr-log4j.properties -Dyz.lib.dir=/usr/local/Cellar/riak/2.2.0/libexec/lib/yokozuna-2.1.7-0-g6cf80ad/priv/java_lib -d64 -Xms1g -Xmx2g -XX:+UseStringCache -XX:+UseCompressedOops -Dcom.sun.management.jmxremote.port=8985 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false org.eclipse.jetty.start.Main
```

**Comment by AliakseiMat** [comment]
I have installed Riak with homebrew:
```sh
brew install riak
```
Let me try to run Solr in standalone mode.

**Comment by AliakseiMat** [comment]
In standalone mode Solr works good. 
What doesn't mean in log : "Yokozuna has exited - shutting down Solr". Where I can find the reason of "Yokozuna has exited"
Thanks!

**Comment by AliakseiMat** [comment]
So, I have figure out the problem. Looks like the root cause of this issue is this java bug:https://bugs.openjdk.java.net/browse/JDK-8044306
The solution is add the following string into /ets/hosts
```sh
127.0.0.1       localhost     <hostname>.local
```
The \<hostname\>.local can be got with this terminal command:
```sh
...$ hostname
```
It also will fix this IntelliJ idea bug :) https://youtrack.jetbrains.com/issue/IDEA-157303
