### ISSUE TITLE
Riak KV EE 2.2 rpm centos package

### ISSUE THREAD

**Issue by sreeninair** [basho/riak#917]
Anybody know where to get Riak KV enterprise edition 2.2 rpm centos package?.

Thanks Sreenivas

**Comment by martincox** [comment]
I'm guessing the reason for wanting EE packages is to get replication? That's now been ported to OS Riak. There's an internal release 2.2.4 which is 2.2.3 with repl included - there's no packages for it though, so you would build from source and package yourself. There is an upcoming 2.2.5 release, however, which should land in Jan.

If you really need EE packages regardless, you might get some help in Slack.
