### ISSUE TITLE
docs.basho.com - 403 Forbidden

### ISSUE THREAD

**Issue by marcinrosinski** [basho/riak#922]
Any ideas why http://docs.basho.com/ is not accessible? For couple days now getting the following error:

```
403 Forbidden

Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: 029A847987F5FCD6
HostId: RcgP70hk0b6JSG7cDLDq5h57Myk00BQ591Z3u7paw2mqv59fxljzdBN9rAo40rEy/dEzRlUmAOM=
```

**Comment by zowers** [comment]
see https://github.com/basho/riak/issues/919#issuecomment-323918548

> Basho is in bankruptcy state and no longer providing the access to their package downloads, i have been trying to access it since many days but no resolution. Hence you need to rely on open source Riak Git repos.

> Tiot.jp are hosting mirrors of downloads and docs. The debs you look for are here https://files.tiot.jp/riak/kv/2.2/2.2.3/ubuntu/. The docs are here https://www.tiot.jp/riak-docs/
