### ISSUE TITLE
ERROR: OTP release 20 does not match required regex R16|17

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [basho/riak#923]
I am trying to build Riak from Github source and I am getting this error. 

```
ERROR: OTP release 20 does not match required regex R16|17
ERROR: compile failed while processing /home/osboxes/riak-build/riak/deps/rebar_lock_deps_plugin: rebar_abort
Makefile:23: recipe for target 'compile' failed
make: *** [compile] Error 1

```
It does takes a lot of time to clone repo to riak/ folder but then it pops a lot of messages about "Missing Plugins.

I know there is no release yet for 16.04 but I thought to give it a try. If this is not the way I should do it then is there any other way around? Can someone please help?

**Comment by Bob-The-Marauder** [comment]
Based on the title of your post, you'll be wanting Erlang 16 which you'll need Kerl for. Please see https://www.tiot.jp/riak-docs/riak/kv/2.2.3/setup/installing/source/erlang/#kerl-prerequisites for details.

This is also referenced in https://github.com/basho/riak/issues/920

**Comment by joshzinny** [comment]
Hi guy, I am having this same problem. Is there any solution to this? Thanks in advance
joshzinny:riak joshzinny$ make devrel
./rebar get-deps
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (get-deps)
==> riak_pb (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> mochiweb (get-deps)
==> webmachine (get-deps)
==> riak_api (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> proper (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> stdlib2 (get-deps)
==> hyper (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> chronos (get-deps)
==> riak_kv (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> rel (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak (get-deps)
==> riak (get-deps)
./rebar compile
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (compile)
ERROR: OTP release 21 does not match required regex R16|17
ERROR: compile failed while processing /Users/joshzinny/riak/deps/rebar_lock_deps_plugin: rebar_abort
make: *** [compile] Error 1

**Comment by russelldb** [comment]
You still need basho's OTP16 for riak. OTP20+ support is coming in 2019

**Comment by joshzinny** [comment]
I am using Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V10.0  (abort with ^G)

**Comment by russelldb** [comment]
Yup, that's the issue alright. Riak only supports erlang r16b0something.

**Comment by joshzinny** [comment]
Is there any work around solution now?

**Comment by russelldb** [comment]
yes, use erlang-r16. Ideally the basho patched erlang-r16b04-basho10

**Comment by joshzinny** [comment]
Okay thanks.
