### ISSUE TITLE
Broken repository: http://s3.amazonaws.com/files.basho.com/

### ISSUE THREAD

**Issue by brailateo** [basho/riak#925]
Downloading yokozuna-3.jar
--2017-09-11 19:02:02--  http://s3.amazonaws.com/files.basho.com/yokozuna/yokozuna-3.jar
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.81.19
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.81.19|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-09-11 19:02:03 ERROR 403: Forbidden.

ERROR: Command [compile] failed!

Also http://docs.basho.com/ returns an error:
403 Forbidden
Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: B9B1726C8473728D
HostId: Le1kyHxKeQnQMAhYqKqmgc3XvGW7uwybmCxcQZGbb8Ury99Ce+BP/pv2g9rljVjTn4RhLl1E/xg=

**Comment by binarytemple** [comment]
Yes. This sucks. The build grabs a patched version of Apache Solr from the basho s3 amazon account. Basho is no more - so no more s3 account. It's a bit unfortunate it wasn't uploaded somewhere like the Apache Maven repository where it could have sat forever, but that's life.

If you look in [build-solr.sh](https://github.com/basho/yokozuna/blob/develop/tools/build-solr.sh#L11) you will see an example of how to build the patched Solr. 

You could then upload it somewhere and set the environment variable [ARTIFACT_URL_PREFIX](https://github.com/basho/yokozuna/blob/develop/tools/grab-solr.sh#L28) to grab it from your chosen location.

I believe @Bob-The-Marauder has already done this and uploaded a copy to a tokyo.ti amazon account - perhaps he can comment.

**Comment by zowers** [comment]
see https://github.com/basho/riak/issues/920#issuecomment-325121500

**Comment by binarytemple** [comment]
Thanks @zowers - someone needs to close this ticket now ;-)

**Comment by SserwangaV** [comment]
Referring to @binarytemple  solution, when installing riak-2.2.3 from the source, I just edited the  file **build-solr.sh** found in the **tools** directory of **yokozuna** directory and replaced **http://s3.amazonaws.com/files.basho.com**  with **https://files.tiot.jp/riak** where ever it appears in the file. I was following the procedure of installing from the source as stated here **https://www.tiot.jp/riak-docs/riak/kv/2.2.3/setup/installing/source/#installing-from-source-package**.

**Comment by binarytemple** [comment]
Yep. The env var override ARTIFACT_URL_PREFIX only works (untested) on develop branch. I'm going to release some docker stuff over the next couple of days, and ESL are going to start adding downloads on their website. For my builds I've actually swapped out `/usr/bin/curl` with a monkey patched script that calls the original `/usr/bin/curl.bak` with a substituted URL - ugly, but works, actually not that ugly because I'm building using docker so it's not like I'm messing up a system for everyone else.
