### ISSUE TITLE
develop-3.0 compile failure 

### ISSUE THREAD

**Issue by ghost** [basho/riak#967]
[root@bdb53086ec0f riak]# rebar3 compile                                                                                                       
===> Verifying dependencies...                                                                                                                 
===> Plugin rebar3_eqc does not export init/1. It will not be used.                                                                            
===> Compiling riak_repl_pb_api                                                                                                                
===> Compiling _build/default/lib/riak_repl_pb_api/src/riak_repl_pb_api.erl failed                                                             
_build/default/lib/riak_repl_pb_api/src/riak_repl_pb_api.erl:44: record 'RpbGetResp' undefined                                                 
_build/default/lib/riak_repl_pb_api/src/riak_repl_pb_api.erl:45: variable 'VClock' is unbound                                                  
_build/default/lib/riak_repl_pb_api/src/riak_repl_pb_api.erl:46: record 'RpbGetResp' undefined                                                 
_build/default/lib/riak_repl_pb_api/src/riak_repl_pb_api.erl:47: variable 'RpbContents' is unbound                                             
_build/default/lib/riak_repl_pb_api/src/riak_repl_pb_api.erl:48: variable 'Vclock' is unbound

**Comment by ghost** [comment]
But change into `_build/default/lib/riak_repl_pb_api` and it compiles fine. 

```

[root@bdb53086ec0f riak]# cd _build/default/lib/riak_repl_pb_api
[root@bdb53086ec0f riak_repl_pb_api]# 
[root@bdb53086ec0f riak_repl_pb_api]# rebar3 compile
===> Verifying dependencies...
===> Fetching riak_pb ({git,"https://github.com/basho/riak_pb.git",
                                  {ref,
                                      "bf5449e1f660c83041c73387b4a090e8b92da6c1"}})
===> Fetching rebar3_gpb_plugin ({pkg,<<"rebar3_gpb_plugin">>,
                                         <<"2.8.0">>})
===> Version cached at /root/.cache/rebar3/hex/hexpm/packages/rebar3_gpb_plugin-2.8.0.tar is up to date, reusing it
===> Fetching gpb ({pkg,<<"gpb">>,<<"4.7.1">>})
===> Version cached at /root/.cache/rebar3/hex/hexpm/packages/gpb-4.7.1.tar is up to date, reusing it
===> Compiling gpb
Compiling descriptor.proto...
Compiling gpb_descriptor.erl...
Compiling gpb_compile_descr.erl...
===> Compiling rebar3_gpb_plugin
===> Fetching rebar3_eqc ({git,"https://github.com/Vagabond/rebar3-eqc-plugin",
                                      {branch,"master"}})
===> Fetching cf ({pkg,<<"cf">>,<<"0.1.2">>})
===> Version cached at /root/.cache/rebar3/hex/hexpm/packages/cf-0.1.2.tar is up to date, reusing it
===> Compiling cf
===> Compiling rebar3_eqc
===> Plugin rebar3_eqc does not export init/1. It will not be used.
===> Fetching rebar3_riak_pb_msgcodegen ({git,
                                                 "https://github.com/Vagabond/rebar3_riak_pb_msgcodegen",
                                                 {branch,"master"}})
===> Compiling rebar3_riak_pb_msgcodegen
_build/default/plugins/rebar3_riak_pb_msgcodegen/src/rebar3_riak_pb_msgcodegen.erl:151: Warning: function delete_each/1 is unused

===> Compiling riak_pb
===> Generated /root/riak/_build/default/lib/riak_repl_pb_api/_build/default/lib/riak_pb/src/riak_pb_messages.erl

===> Compiling riak_repl_pb_api
```

**Comment by ghost** [comment]
different deps in the lock files : 

```
[root@bdb53086ec0f riak_repl_pb_api]# grep -A2 riak_pb /root/riak/rebar.lock 
 {<<"riak_pb">>,
  {git,"git://github.com/basho/riak_pb.git",
       {ref,"fec66b67115e5e37ac0d27ebf1f442bf21375784"}},
  2},
[root@bdb53086ec0f riak_repl_pb_api]# grep -A2 riak_pb ./rebar.lock 
[{<<"riak_pb">>,
  {git,"https://github.com/basho/riak_pb.git",
       {ref,"bf5449e1f660c83041c73387b4a090e8b92da6c1"}},
  0}].
[root@bdb53086ec0f riak_repl_pb_api]# 
```

**Comment by martincox** [comment]
Is fixed now. Was some mix up with the gpb changes and camel case requirement.
