### ISSUE TITLE
Running Riak on a modern OTP version (19-22)

### ISSUE THREAD

**Issue by tomciopp** [basho/riak#978]
We're working on updating the erlang package for homebrew and we have an open question surrounding the version of erlang required for riak. It looks like version 17 is the most recent version of erlang that is compatible based on my reading of the rebar config. However, the most recent release of v17 is 4 years old, and there have been many developments in the language since then. 

I'm not an expert in riak so I'm uncertain if there is a reason why we shouldn't be able to upgrade. If anyone could provide a bit more detail on the specifics for this choice I would greatly appreciate it.

**Comment by martincox** [comment]
@tomciopp there's quite a bit of ongoing work to run riak on OTP20. It's at a point where it compiles, but is not yet releasable. I'd anticipate that it might be around 3 - 6 months before we get to that point.
