### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by patgpraj** [basho/riak#998]
Sorry to ask this question here, but I don't know where to post it. Does Riak community has any slack channel that followers can join? If not, is there any plan to open slack channel for community in future? Thank you.

**Comment by martinsumner** [comment]
postriak.slack.com - I don't believe an invite is required.

**Comment by patgpraj** [comment]
Thank you for the link. But it says - contact the workspace administrator for an invitation.

**Comment by llelf** [comment]
There is an invitation link there somewhere…
But I sent you an invite, @patgpraj

**Comment by patgpraj** [comment]
I got the invitation and joined the channel. Thank you. I will close this issue.

**Comment by nurugger07** [comment]
@llelf sorry to join this closed issue but tried to join the slack channel and had the same problem. Can I get an invite?

**Comment by asyncmind0** [comment]
https://join.slack.com/t/postriak/shared_invite/zt-3h381ljq-MM5JXJ26BFelVaLvzgJ25A
