### ISSUE TITLE
RIAK Node does not Start after changing IP

### ISSUE THREAD

**Issue by Ei3rb0mb3r** [basho/riak#999]
I am in the process of setting up a Riak Cluster on Raspberry Pis. Unfortunately I get the following error message after changing the IP address. Versions I used: Debian Jessie (Raspberry PI) riak (Github Clone Mar2017) riak-cs2.1.1 stanchion-2.1.1, OTP_SRC_R16B02-basho10 (Erlang)

Using this guide I tried to change the IP addresses in the various .conf files. https://docs.riak.com/riak/kv/latest/using/cluster-operations/changing-cluster-info/index.html

Works on 127.0.0.1:

$ ~/riak/rel/riak/bin/riak-admin test
Successfully completed 1 read/write cycle to 'riak@127.0.0.1'

Error Message (after changing IP:192.168.178.61):

sudo ./riak console
config is OK
-config /home/pi/neu/riak/rel/riak/data/generated.configs/app.2020.01.02.23.37.52.config -args_file /home/pi/neu/riak/rel/riak/data/generated.configs/vm.2020.01.02.23.37.52.args -vm_args /home/pi/neu/riak/rel/riak/data/generated.configs/vm.2020.01.02.23.37.52.args
Exec:  /home/pi/neu/riak/rel/riak/bin/../erts-5.10.3/bin/erlexec -boot /home/pi/neu/riak/rel/riak/bin/../releases/2.2.3/riak               -config /home/pi/neu/riak/rel/riak/data/generated.configs/app.2020.01.02.23.37.52.config -args_file /home/pi/neu/riak/rel/riak/data/generated.configs/vm.2020.01.02.23.37.52.args -vm_args /home/pi/neu/riak/rel/riak/data/generated.configs/vm.2020.01.02.23.37.52.args              -pa /home/pi/neu/riak/rel/riak/bin/../lib/basho-patches -- console
Root: /home/pi/neu/riak/rel/riak/bin/..
Erlang R16B02_basho10 (erts-5.10.3) [source] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true] [frame-pointer]

[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,riak_core,{bad_return,{{riak_core_app,start,[normal,[]]},{'EXIT',{{function_clause,[{orddict,fetch,['riak@192.168.178.61',[]],[{file,\"orddict.erl\"},{line,72}]},{riak_core_capability,renegotiate_capabilities,1,[{file,\"src/riak_core_capability.erl\"},{line,441}]},{riak_core_capability,handle_call,3,[{file,\"src/riak_core_capability.erl\"},{line,213}]},{gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,239}]}]},{gen_server,call,[riak_core_capability,{register,{riak_core,vnode_routing},{capability,[proxy,legacy],legacy,{riak_core,legacy_vnode_routing,[{true,legacy},{false,proxy}]}}},infinity]}}}}}}"}

Crash dump was written to: ./log/erl_crash.dump

**Comment by martinsumner** [comment]
I might expect to see this if you hadn't done the step of either renaming (or deleting the contents of) the ring directory.  Did you do this?

Also can you confirm if you're in the single-node or multi-node renaming scenario?

**Comment by Ei3rb0mb3r** [comment]
Many thanks for the quick feedback! 
The error has been solved after I deleted the ring directory files.

After that there were some more errors, but I could solve them and now I could create a cluster of 4 pis.

**Comment by Ei3rb0mb3r** [comment]
================================= Membership ==================================
Status     Ring    Pending    Node
-------------------------------------------------------------------------------
valid      25.0%      --      'riak@192.168.178.61'
valid      25.0%      --      'riak@192.168.178.62'
valid      25.0%      --      'riak@192.168.178.63'
valid      25.0%      --      'riak@192.168.178.64'
-------------------------------------------------------------------------------
Valid:4 / Leaving:0 / Exiting:0 / Joining:0 / Down:0
